/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { accountingV2CreateBookingProposal } from "../funcs/accounting-v2-create-booking-proposal.js";
import { accountingV2CreateContact } from "../funcs/accounting-v2-create-contact.js";
import { accountingV2ObtainDimensions } from "../funcs/accounting-v2-obtain-dimensions.js";
import { accountingV2UpdateContact } from "../funcs/accounting-v2-update-contact.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class AccountingV2 extends ClientSDK {
  async createBookingProposal(
    request: operations.CreateBookingProposalV2Request,
    options?: RequestOptions,
  ): Promise<operations.CreateBookingProposalV2Response> {
    return unwrapAsync(accountingV2CreateBookingProposal(
      this,
      request,
      options,
    ));
  }

  async createContact(
    request: operations.CreateContactV2Request,
    options?: RequestOptions,
  ): Promise<operations.CreateContactV2Response> {
    return unwrapAsync(accountingV2CreateContact(
      this,
      request,
      options,
    ));
  }

  async updateContact(
    request: operations.PutContactV2Request,
    options?: RequestOptions,
  ): Promise<operations.PutContactV2Response> {
    return unwrapAsync(accountingV2UpdateContact(
      this,
      request,
      options,
    ));
  }

  async obtainDimensions(
    request?: operations.GetDimensionsV2Request | undefined,
    options?: RequestOptions,
  ): Promise<operations.GetDimensionsV2Response> {
    return unwrapAsync(accountingV2ObtainDimensions(
      this,
      request,
      options,
    ));
  }
}
