/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { userGetUserInfo } from "../funcs/user-get-user-info.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class User extends ClientSDK {
  async getUserInfo(
    options?: RequestOptions,
  ): Promise<operations.GetUserInfoResponse> {
    return unwrapAsync(userGetUserInfo(
      this,
      options,
    ));
  }
}
