/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @maesn/typescript-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx accountingRetrieveAccount.example.ts
 */

import { Maesn } from "@maesn/typescript-sdk";

const maesn = new Maesn({
  serverURL: "https://api.example.com",
  security: {
    apiKey: process.env["MAESN_API_KEY"] ?? "",
    accountKey: process.env["MAESN_ACCOUNT_KEY"] ?? "",
  },
});

async function main() {
  const result = await maesn.accounting.retrieveAccount({
    accountId: "<id>",
  });

  console.log(result);
}

main().catch(console.error);
