workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Maesn unified API:
        inputs:
            - location: https://unified-backend-prod.azurewebsites.net/api-json
            - location: https://unified-backend-prod.azurewebsites.net/api/auth-json
            - location: https://unified-backend-prod.azurewebsites.net/api/events-json
            - location: https://unified-backend-prod.azurewebsites.net/api/webhooks-json
            - location: https://unified-backend-prod.azurewebsites.net/api/health-json
            - location: https://unified-backend-prod.azurewebsites.net/api/tenants-json
        overlays:
            - location: .speakeasy/overlays/info-overlay.yaml
            - location: .speakeasy/overlays/auth-security-overlay.yaml
            - location: .speakeasy/overlays/enum-types-overlay.yaml
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/maesndev/maesn/maesn-unified-api
targets:
    maesn:
        target: typescript
        source: Maesn unified API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/maesndev/maesn/maesn-unified-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
