/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type CallbackRequest = {
  targetSystem: string;
  code?: string | undefined;
  state: string;
  realmId?: string | undefined;
  token?: string | undefined;
};

/** @internal */
export type CallbackRequest$Outbound = {
  TARGET_SYSTEM: string;
  code?: string | undefined;
  state: string;
  realmId?: string | undefined;
  token?: string | undefined;
};

/** @internal */
export const CallbackRequest$outboundSchema: z.ZodMiniType<
  CallbackRequest$Outbound,
  CallbackRequest
> = z.pipe(
  z.object({
    targetSystem: z.string(),
    code: z.optional(z.string()),
    state: z.string(),
    realmId: z.optional(z.string()),
    token: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetSystem: "TARGET_SYSTEM",
    });
  }),
);

export function callbackRequestToJSON(
  callbackRequest: CallbackRequest,
): string {
  return JSON.stringify(CallbackRequest$outboundSchema.parse(callbackRequest));
}
