/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type CallbackRequest = {
  targetSystem: string;
  /**
   * OAuth state parameter returned by the target system, encoding tenant and user context
   */
  state: string;
  /**
   * Authorization code returned by the target system after successful OAuth consent
   */
  code?: string | undefined;
  /**
   * Realm ID returned by QuickBooks Online after OAuth consent
   */
  realmId?: string | undefined;
  /**
   * Access token returned directly by some target systems that do not use an authorization code flow
   */
  token?: string | undefined;
};

/**
 * OAuth callback processed and redirect URL returned successfully
 */
export type CallbackResponse = {
  url?: string | undefined;
};

/** @internal */
export type CallbackRequest$Outbound = {
  TARGET_SYSTEM: string;
  state: string;
  code?: string | undefined;
  realmId?: string | undefined;
  token?: string | undefined;
};

/** @internal */
export const CallbackRequest$outboundSchema: z.ZodMiniType<
  CallbackRequest$Outbound,
  CallbackRequest
> = z.pipe(
  z.object({
    targetSystem: z.string(),
    state: z.string(),
    code: z.optional(z.string()),
    realmId: z.optional(z.string()),
    token: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetSystem: "TARGET_SYSTEM",
    });
  }),
);

export function callbackRequestToJSON(
  callbackRequest: CallbackRequest,
): string {
  return JSON.stringify(CallbackRequest$outboundSchema.parse(callbackRequest));
}

/** @internal */
export const CallbackResponse$inboundSchema: z.ZodMiniType<
  CallbackResponse,
  unknown
> = z.object({
  url: types.optional(types.string()),
});

export function callbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<CallbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CallbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CallbackResponse' from JSON`,
  );
}
