/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBillLineItemRequest = {
  billId: string;
  companyId?: string | undefined;
  body: models.CreateBillLineItemRequestDto;
};

export type CreateBillLineItemErrors = {};

export type CreateBillLineItemRawData = {};

export type CreateBillLineItemResponse = {
  meta: models.MetaResponse;
  data: Array<models.BillLineItemResponseDto>;
  errors: CreateBillLineItemErrors;
  rawData: CreateBillLineItemRawData;
};

/** @internal */
export type CreateBillLineItemRequest$Outbound = {
  billId: string;
  companyId?: string | undefined;
  body: models.CreateBillLineItemRequestDto$Outbound;
};

/** @internal */
export const CreateBillLineItemRequest$outboundSchema: z.ZodMiniType<
  CreateBillLineItemRequest$Outbound,
  CreateBillLineItemRequest
> = z.object({
  billId: z.string(),
  companyId: z.optional(z.string()),
  body: models.CreateBillLineItemRequestDto$outboundSchema,
});

export function createBillLineItemRequestToJSON(
  createBillLineItemRequest: CreateBillLineItemRequest,
): string {
  return JSON.stringify(
    CreateBillLineItemRequest$outboundSchema.parse(createBillLineItemRequest),
  );
}

/** @internal */
export const CreateBillLineItemErrors$inboundSchema: z.ZodMiniType<
  CreateBillLineItemErrors,
  unknown
> = z.object({});

export function createBillLineItemErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemErrors' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemRawData$inboundSchema: z.ZodMiniType<
  CreateBillLineItemRawData,
  unknown
> = z.object({});

export function createBillLineItemRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemRawData' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemResponse$inboundSchema: z.ZodMiniType<
  CreateBillLineItemResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.BillLineItemResponseDto$inboundSchema),
  errors: z.lazy(() => CreateBillLineItemErrors$inboundSchema),
  rawData: z.lazy(() => CreateBillLineItemRawData$inboundSchema),
});

export function createBillLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemResponse' from JSON`,
  );
}
