/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateAccountRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateAccountRequestDto;
};

export type CreateAccountErrors = {};

export type CreateAccountRawData = {};

export type CreateAccountResponse = {
  meta: models.MetaResponse;
  data: models.AccountResponseDto;
  errors: CreateAccountErrors;
  rawData: CreateAccountRawData;
};

/** @internal */
export type CreateAccountRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateAccountRequestDto$Outbound;
};

/** @internal */
export const CreateAccountRequest$outboundSchema: z.ZodMiniType<
  CreateAccountRequest$Outbound,
  CreateAccountRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.CreateAccountRequestDto$outboundSchema,
});

export function createAccountRequestToJSON(
  createAccountRequest: CreateAccountRequest,
): string {
  return JSON.stringify(
    CreateAccountRequest$outboundSchema.parse(createAccountRequest),
  );
}

/** @internal */
export const CreateAccountErrors$inboundSchema: z.ZodMiniType<
  CreateAccountErrors,
  unknown
> = z.object({});

export function createAccountErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountErrors' from JSON`,
  );
}

/** @internal */
export const CreateAccountRawData$inboundSchema: z.ZodMiniType<
  CreateAccountRawData,
  unknown
> = z.object({});

export function createAccountRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountRawData' from JSON`,
  );
}

/** @internal */
export const CreateAccountResponse$inboundSchema: z.ZodMiniType<
  CreateAccountResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.AccountResponseDto$inboundSchema,
  errors: z.lazy(() => CreateAccountErrors$inboundSchema),
  rawData: z.lazy(() => CreateAccountRawData$inboundSchema),
});

export function createAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateAccountResponse' from JSON`,
  );
}
