/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateTransactionFile = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type CreateTransactionRequestBody = {
  files?: Array<CreateTransactionFile> | undefined;
  transaction?: models.CreateTransactionRequestDto | undefined;
};

export type CreateTransactionRequest = {
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  body: CreateTransactionRequestBody;
};

export type CreateTransactionPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateTransactionMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateTransactionPagination | null | undefined;
};

export type CreateTransactionErrors = {};

export type CreateTransactionRawData = {};

/**
 * Transaction created successfully
 */
export type CreateTransactionResponse = {
  meta?: CreateTransactionMeta | null | undefined;
  data: models.TransactionResponseDto;
  errors: CreateTransactionErrors | null;
  rawData: CreateTransactionRawData | null;
};

/** @internal */
export type CreateTransactionFile$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateTransactionFile$outboundSchema: z.ZodMiniType<
  CreateTransactionFile$Outbound,
  CreateTransactionFile
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createTransactionFileToJSON(
  createTransactionFile: CreateTransactionFile,
): string {
  return JSON.stringify(
    CreateTransactionFile$outboundSchema.parse(createTransactionFile),
  );
}

/** @internal */
export type CreateTransactionRequestBody$Outbound = {
  files?: Array<CreateTransactionFile$Outbound> | undefined;
  transaction?: models.CreateTransactionRequestDto$Outbound | undefined;
};

/** @internal */
export const CreateTransactionRequestBody$outboundSchema: z.ZodMiniType<
  CreateTransactionRequestBody$Outbound,
  CreateTransactionRequestBody
> = z.object({
  files: z.optional(
    z.array(z.lazy(() => CreateTransactionFile$outboundSchema)),
  ),
  transaction: z.optional(models.CreateTransactionRequestDto$outboundSchema),
});

export function createTransactionRequestBodyToJSON(
  createTransactionRequestBody: CreateTransactionRequestBody,
): string {
  return JSON.stringify(
    CreateTransactionRequestBody$outboundSchema.parse(
      createTransactionRequestBody,
    ),
  );
}

/** @internal */
export type CreateTransactionRequest$Outbound = {
  companyId?: string | undefined;
  body: CreateTransactionRequestBody$Outbound;
};

/** @internal */
export const CreateTransactionRequest$outboundSchema: z.ZodMiniType<
  CreateTransactionRequest$Outbound,
  CreateTransactionRequest
> = z.object({
  companyId: z.optional(z.string()),
  body: z.lazy(() => CreateTransactionRequestBody$outboundSchema),
});

export function createTransactionRequestToJSON(
  createTransactionRequest: CreateTransactionRequest,
): string {
  return JSON.stringify(
    CreateTransactionRequest$outboundSchema.parse(createTransactionRequest),
  );
}

/** @internal */
export const CreateTransactionPagination$inboundSchema: z.ZodMiniType<
  CreateTransactionPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createTransactionPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateTransactionPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTransactionPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTransactionPagination' from JSON`,
  );
}

/** @internal */
export const CreateTransactionMeta$inboundSchema: z.ZodMiniType<
  CreateTransactionMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateTransactionPagination$inboundSchema)),
  ),
});

export function createTransactionMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateTransactionMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTransactionMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTransactionMeta' from JSON`,
  );
}

/** @internal */
export const CreateTransactionErrors$inboundSchema: z.ZodMiniType<
  CreateTransactionErrors,
  unknown
> = z.object({});

export function createTransactionErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateTransactionErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTransactionErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTransactionErrors' from JSON`,
  );
}

/** @internal */
export const CreateTransactionRawData$inboundSchema: z.ZodMiniType<
  CreateTransactionRawData,
  unknown
> = z.object({});

export function createTransactionRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateTransactionRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTransactionRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTransactionRawData' from JSON`,
  );
}

/** @internal */
export const CreateTransactionResponse$inboundSchema: z.ZodMiniType<
  CreateTransactionResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateTransactionMeta$inboundSchema)),
  ),
  data: models.TransactionResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateTransactionErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => CreateTransactionRawData$inboundSchema)),
});

export function createTransactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateTransactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateTransactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateTransactionResponse' from JSON`,
  );
}
