/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBillRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateBillRequestDto;
};

export type CreateBillErrors = {};

export type CreateBillRawData = {};

export type CreateBillResponse = {
  meta: models.MetaResponse;
  data: models.BillResponseDto;
  errors: CreateBillErrors;
  rawData: CreateBillRawData;
};

/** @internal */
export type CreateBillRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateBillRequestDto$Outbound;
};

/** @internal */
export const CreateBillRequest$outboundSchema: z.ZodMiniType<
  CreateBillRequest$Outbound,
  CreateBillRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.CreateBillRequestDto$outboundSchema,
});

export function createBillRequestToJSON(
  createBillRequest: CreateBillRequest,
): string {
  return JSON.stringify(
    CreateBillRequest$outboundSchema.parse(createBillRequest),
  );
}

/** @internal */
export const CreateBillErrors$inboundSchema: z.ZodMiniType<
  CreateBillErrors,
  unknown
> = z.object({});

export function createBillErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillErrors' from JSON`,
  );
}

/** @internal */
export const CreateBillRawData$inboundSchema: z.ZodMiniType<
  CreateBillRawData,
  unknown
> = z.object({});

export function createBillRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillRawData' from JSON`,
  );
}

/** @internal */
export const CreateBillResponse$inboundSchema: z.ZodMiniType<
  CreateBillResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.BillResponseDto$inboundSchema,
  errors: z.lazy(() => CreateBillErrors$inboundSchema),
  rawData: z.lazy(() => CreateBillRawData$inboundSchema),
});

export function createBillResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillResponse' from JSON`,
  );
}
