/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBankAccountRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateBankAccountRequestDto;
};

export type CreateBankAccountErrors = {};

export type CreateBankAccountRawData = {};

export type CreateBankAccountResponse = {
  meta: models.MetaResponse;
  data: models.BankAccountResponseDto;
  errors: CreateBankAccountErrors;
  rawData: CreateBankAccountRawData;
};

/** @internal */
export type CreateBankAccountRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateBankAccountRequestDto$Outbound;
};

/** @internal */
export const CreateBankAccountRequest$outboundSchema: z.ZodMiniType<
  CreateBankAccountRequest$Outbound,
  CreateBankAccountRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.CreateBankAccountRequestDto$outboundSchema,
});

export function createBankAccountRequestToJSON(
  createBankAccountRequest: CreateBankAccountRequest,
): string {
  return JSON.stringify(
    CreateBankAccountRequest$outboundSchema.parse(createBankAccountRequest),
  );
}

/** @internal */
export const CreateBankAccountErrors$inboundSchema: z.ZodMiniType<
  CreateBankAccountErrors,
  unknown
> = z.object({});

export function createBankAccountErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBankAccountErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBankAccountErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBankAccountErrors' from JSON`,
  );
}

/** @internal */
export const CreateBankAccountRawData$inboundSchema: z.ZodMiniType<
  CreateBankAccountRawData,
  unknown
> = z.object({});

export function createBankAccountRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBankAccountRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBankAccountRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBankAccountRawData' from JSON`,
  );
}

/** @internal */
export const CreateBankAccountResponse$inboundSchema: z.ZodMiniType<
  CreateBankAccountResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.BankAccountResponseDto$inboundSchema,
  errors: z.lazy(() => CreateBankAccountErrors$inboundSchema),
  rawData: z.lazy(() => CreateBankAccountRawData$inboundSchema),
});

export function createBankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBankAccountResponse' from JSON`,
  );
}
