/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateVendorCreditGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type CreateVendorCreditRequest = {
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
  body: models.CreateVendorCreditRequestDto;
};

export type CreateVendorCreditPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateVendorCreditMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateVendorCreditPagination | null | undefined;
};

export type CreateVendorCreditErrors = {};

export type CreateVendorCreditRawData = {};

/**
 * Vendor credit created successfully
 */
export type CreateVendorCreditResponse = {
  meta?: CreateVendorCreditMeta | null | undefined;
  data: models.VendorCreditResponseDto;
  errors: CreateVendorCreditErrors | null;
  rawData: CreateVendorCreditRawData | null;
};

/** @internal */
export type CreateVendorCreditRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
  body: models.CreateVendorCreditRequestDto$Outbound;
};

/** @internal */
export const CreateVendorCreditRequest$outboundSchema: z.ZodMiniType<
  CreateVendorCreditRequest$Outbound,
  CreateVendorCreditRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
  body: models.CreateVendorCreditRequestDto$outboundSchema,
});

export function createVendorCreditRequestToJSON(
  createVendorCreditRequest: CreateVendorCreditRequest,
): string {
  return JSON.stringify(
    CreateVendorCreditRequest$outboundSchema.parse(createVendorCreditRequest),
  );
}

/** @internal */
export const CreateVendorCreditPagination$inboundSchema: z.ZodMiniType<
  CreateVendorCreditPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createVendorCreditPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateVendorCreditPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVendorCreditPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVendorCreditPagination' from JSON`,
  );
}

/** @internal */
export const CreateVendorCreditMeta$inboundSchema: z.ZodMiniType<
  CreateVendorCreditMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateVendorCreditPagination$inboundSchema)),
  ),
});

export function createVendorCreditMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateVendorCreditMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVendorCreditMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVendorCreditMeta' from JSON`,
  );
}

/** @internal */
export const CreateVendorCreditErrors$inboundSchema: z.ZodMiniType<
  CreateVendorCreditErrors,
  unknown
> = z.object({});

export function createVendorCreditErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateVendorCreditErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVendorCreditErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVendorCreditErrors' from JSON`,
  );
}

/** @internal */
export const CreateVendorCreditRawData$inboundSchema: z.ZodMiniType<
  CreateVendorCreditRawData,
  unknown
> = z.object({});

export function createVendorCreditRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateVendorCreditRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVendorCreditRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVendorCreditRawData' from JSON`,
  );
}

/** @internal */
export const CreateVendorCreditResponse$inboundSchema: z.ZodMiniType<
  CreateVendorCreditResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateVendorCreditMeta$inboundSchema)),
  ),
  data: models.VendorCreditResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateVendorCreditErrors$inboundSchema)),
  rawData: types.nullable(
    z.lazy(() => CreateVendorCreditRawData$inboundSchema),
  ),
});

export function createVendorCreditResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateVendorCreditResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateVendorCreditResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateVendorCreditResponse' from JSON`,
  );
}
