/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateExpenseFile = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type CreateExpenseRequestBody = {
  files?: Array<CreateExpenseFile> | undefined;
  expense?: models.CreateExpenseDto | undefined;
};

export type CreateExpenseRequest = {
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  body: CreateExpenseRequestBody;
};

export type CreateExpensePagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateExpenseMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateExpensePagination | null | undefined;
};

export type CreateExpenseErrors = {};

export type CreateExpenseRawData = {};

/**
 * Expense created successfully
 */
export type CreateExpenseResponse = {
  meta?: CreateExpenseMeta | null | undefined;
  data: models.ExpenseResponseDto;
  errors: CreateExpenseErrors | null;
  rawData: CreateExpenseRawData | null;
};

/** @internal */
export type CreateExpenseFile$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateExpenseFile$outboundSchema: z.ZodMiniType<
  CreateExpenseFile$Outbound,
  CreateExpenseFile
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createExpenseFileToJSON(
  createExpenseFile: CreateExpenseFile,
): string {
  return JSON.stringify(
    CreateExpenseFile$outboundSchema.parse(createExpenseFile),
  );
}

/** @internal */
export type CreateExpenseRequestBody$Outbound = {
  files?: Array<CreateExpenseFile$Outbound> | undefined;
  expense?: models.CreateExpenseDto$Outbound | undefined;
};

/** @internal */
export const CreateExpenseRequestBody$outboundSchema: z.ZodMiniType<
  CreateExpenseRequestBody$Outbound,
  CreateExpenseRequestBody
> = z.object({
  files: z.optional(z.array(z.lazy(() => CreateExpenseFile$outboundSchema))),
  expense: z.optional(models.CreateExpenseDto$outboundSchema),
});

export function createExpenseRequestBodyToJSON(
  createExpenseRequestBody: CreateExpenseRequestBody,
): string {
  return JSON.stringify(
    CreateExpenseRequestBody$outboundSchema.parse(createExpenseRequestBody),
  );
}

/** @internal */
export type CreateExpenseRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: CreateExpenseRequestBody$Outbound;
};

/** @internal */
export const CreateExpenseRequest$outboundSchema: z.ZodMiniType<
  CreateExpenseRequest$Outbound,
  CreateExpenseRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: z.lazy(() => CreateExpenseRequestBody$outboundSchema),
});

export function createExpenseRequestToJSON(
  createExpenseRequest: CreateExpenseRequest,
): string {
  return JSON.stringify(
    CreateExpenseRequest$outboundSchema.parse(createExpenseRequest),
  );
}

/** @internal */
export const CreateExpensePagination$inboundSchema: z.ZodMiniType<
  CreateExpensePagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createExpensePaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateExpensePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExpensePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExpensePagination' from JSON`,
  );
}

/** @internal */
export const CreateExpenseMeta$inboundSchema: z.ZodMiniType<
  CreateExpenseMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateExpensePagination$inboundSchema)),
  ),
});

export function createExpenseMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateExpenseMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExpenseMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExpenseMeta' from JSON`,
  );
}

/** @internal */
export const CreateExpenseErrors$inboundSchema: z.ZodMiniType<
  CreateExpenseErrors,
  unknown
> = z.object({});

export function createExpenseErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateExpenseErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExpenseErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExpenseErrors' from JSON`,
  );
}

/** @internal */
export const CreateExpenseRawData$inboundSchema: z.ZodMiniType<
  CreateExpenseRawData,
  unknown
> = z.object({});

export function createExpenseRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateExpenseRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExpenseRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExpenseRawData' from JSON`,
  );
}

/** @internal */
export const CreateExpenseResponse$inboundSchema: z.ZodMiniType<
  CreateExpenseResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => CreateExpenseMeta$inboundSchema))),
  data: models.ExpenseResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateExpenseErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => CreateExpenseRawData$inboundSchema)),
});

export function createExpenseResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateExpenseResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateExpenseResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateExpenseResponse' from JSON`,
  );
}
