/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBillLineItemGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type CreateBillLineItemRequest = {
  billId: string;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
  body: models.CreateBillLineItemRequestDto;
};

export type CreateBillLineItemPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateBillLineItemMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateBillLineItemPagination | null | undefined;
};

export type CreateBillLineItemErrors = {};

export type CreateBillLineItemRawData = {};

/**
 * Bill line item created successfully
 */
export type CreateBillLineItemResponse = {
  meta?: CreateBillLineItemMeta | null | undefined;
  data: Array<models.BillLineItemResponseDto>;
  errors: CreateBillLineItemErrors | null;
  rawData: CreateBillLineItemRawData | null;
};

/** @internal */
export type CreateBillLineItemRequest$Outbound = {
  billId: string;
  companyId?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
  body: models.CreateBillLineItemRequestDto$Outbound;
};

/** @internal */
export const CreateBillLineItemRequest$outboundSchema: z.ZodMiniType<
  CreateBillLineItemRequest$Outbound,
  CreateBillLineItemRequest
> = z.object({
  billId: z.string(),
  companyId: z.optional(z.string()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
  body: models.CreateBillLineItemRequestDto$outboundSchema,
});

export function createBillLineItemRequestToJSON(
  createBillLineItemRequest: CreateBillLineItemRequest,
): string {
  return JSON.stringify(
    CreateBillLineItemRequest$outboundSchema.parse(createBillLineItemRequest),
  );
}

/** @internal */
export const CreateBillLineItemPagination$inboundSchema: z.ZodMiniType<
  CreateBillLineItemPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createBillLineItemPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemPagination' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemMeta$inboundSchema: z.ZodMiniType<
  CreateBillLineItemMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateBillLineItemPagination$inboundSchema)),
  ),
});

export function createBillLineItemMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemMeta' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemErrors$inboundSchema: z.ZodMiniType<
  CreateBillLineItemErrors,
  unknown
> = z.object({});

export function createBillLineItemErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemErrors' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemRawData$inboundSchema: z.ZodMiniType<
  CreateBillLineItemRawData,
  unknown
> = z.object({});

export function createBillLineItemRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemRawData' from JSON`,
  );
}

/** @internal */
export const CreateBillLineItemResponse$inboundSchema: z.ZodMiniType<
  CreateBillLineItemResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateBillLineItemMeta$inboundSchema)),
  ),
  data: z.array(models.BillLineItemResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => CreateBillLineItemErrors$inboundSchema)),
  rawData: types.nullable(
    z.lazy(() => CreateBillLineItemRawData$inboundSchema),
  ),
});

export function createBillLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBillLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBillLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBillLineItemResponse' from JSON`,
  );
}
