/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePaymentTermRequest = {
  companyId?: string | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
  body: models.CreatePaymentTermRequestDto;
};

export type CreatePaymentTermErrors = {};

export type CreatePaymentTermRawData = {};

export type CreatePaymentTermResponse = {
  meta: models.MetaResponse;
  data: models.PaymentTermResponseDto;
  errors: CreatePaymentTermErrors;
  rawData: CreatePaymentTermRawData;
};

/** @internal */
export type CreatePaymentTermRequest$Outbound = {
  companyId?: string | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
  body: models.CreatePaymentTermRequestDto$Outbound;
};

/** @internal */
export const CreatePaymentTermRequest$outboundSchema: z.ZodMiniType<
  CreatePaymentTermRequest$Outbound,
  CreatePaymentTermRequest
> = z.pipe(
  z.object({
    companyId: z.optional(z.string()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
    body: models.CreatePaymentTermRequestDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function createPaymentTermRequestToJSON(
  createPaymentTermRequest: CreatePaymentTermRequest,
): string {
  return JSON.stringify(
    CreatePaymentTermRequest$outboundSchema.parse(createPaymentTermRequest),
  );
}

/** @internal */
export const CreatePaymentTermErrors$inboundSchema: z.ZodMiniType<
  CreatePaymentTermErrors,
  unknown
> = z.object({});

export function createPaymentTermErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermErrors' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermRawData$inboundSchema: z.ZodMiniType<
  CreatePaymentTermRawData,
  unknown
> = z.object({});

export function createPaymentTermRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermRawData' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermResponse$inboundSchema: z.ZodMiniType<
  CreatePaymentTermResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.PaymentTermResponseDto$inboundSchema,
  errors: z.lazy(() => CreatePaymentTermErrors$inboundSchema),
  rawData: z.lazy(() => CreatePaymentTermRawData$inboundSchema),
});

export function createPaymentTermResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermResponse' from JSON`,
  );
}
