/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBookingsRequest = {
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  body: models.CreateBookingsRequestDto;
};

export type CreateBookingsPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateBookingsMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateBookingsPagination | null | undefined;
};

export type CreateBookingsErrors = {};

export type CreateBookingsRawData = {};

/**
 * Booking created successfully
 */
export type CreateBookingsResponse = {
  meta?: CreateBookingsMeta | null | undefined;
  data: models.BookingsResponseDto;
  errors: CreateBookingsErrors | null;
  rawData: CreateBookingsRawData | null;
};

/** @internal */
export type CreateBookingsRequest$Outbound = {
  companyId?: string | undefined;
  body: models.CreateBookingsRequestDto$Outbound;
};

/** @internal */
export const CreateBookingsRequest$outboundSchema: z.ZodMiniType<
  CreateBookingsRequest$Outbound,
  CreateBookingsRequest
> = z.object({
  companyId: z.optional(z.string()),
  body: models.CreateBookingsRequestDto$outboundSchema,
});

export function createBookingsRequestToJSON(
  createBookingsRequest: CreateBookingsRequest,
): string {
  return JSON.stringify(
    CreateBookingsRequest$outboundSchema.parse(createBookingsRequest),
  );
}

/** @internal */
export const CreateBookingsPagination$inboundSchema: z.ZodMiniType<
  CreateBookingsPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createBookingsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsPagination' from JSON`,
  );
}

/** @internal */
export const CreateBookingsMeta$inboundSchema: z.ZodMiniType<
  CreateBookingsMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateBookingsPagination$inboundSchema)),
  ),
});

export function createBookingsMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsMeta' from JSON`,
  );
}

/** @internal */
export const CreateBookingsErrors$inboundSchema: z.ZodMiniType<
  CreateBookingsErrors,
  unknown
> = z.object({});

export function createBookingsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsErrors' from JSON`,
  );
}

/** @internal */
export const CreateBookingsRawData$inboundSchema: z.ZodMiniType<
  CreateBookingsRawData,
  unknown
> = z.object({});

export function createBookingsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsRawData' from JSON`,
  );
}

/** @internal */
export const CreateBookingsResponse$inboundSchema: z.ZodMiniType<
  CreateBookingsResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => CreateBookingsMeta$inboundSchema))),
  data: models.BookingsResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateBookingsErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => CreateBookingsRawData$inboundSchema)),
});

export function createBookingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsResponse' from JSON`,
  );
}
