/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePaymentRequest = {
  companyId?: string | undefined;
  body: models.CreatePaymentRequestDto;
};

export type CreatePaymentErrors = {};

export type CreatePaymentRawData = {};

export type CreatePaymentResponse = {
  meta: models.MetaResponse;
  data: models.PaymentResponseDto;
  errors: CreatePaymentErrors;
  rawData: CreatePaymentRawData;
};

/** @internal */
export type CreatePaymentRequest$Outbound = {
  companyId?: string | undefined;
  body: models.CreatePaymentRequestDto$Outbound;
};

/** @internal */
export const CreatePaymentRequest$outboundSchema: z.ZodMiniType<
  CreatePaymentRequest$Outbound,
  CreatePaymentRequest
> = z.object({
  companyId: z.optional(z.string()),
  body: models.CreatePaymentRequestDto$outboundSchema,
});

export function createPaymentRequestToJSON(
  createPaymentRequest: CreatePaymentRequest,
): string {
  return JSON.stringify(
    CreatePaymentRequest$outboundSchema.parse(createPaymentRequest),
  );
}

/** @internal */
export const CreatePaymentErrors$inboundSchema: z.ZodMiniType<
  CreatePaymentErrors,
  unknown
> = z.object({});

export function createPaymentErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentErrors' from JSON`,
  );
}

/** @internal */
export const CreatePaymentRawData$inboundSchema: z.ZodMiniType<
  CreatePaymentRawData,
  unknown
> = z.object({});

export function createPaymentRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentRawData' from JSON`,
  );
}

/** @internal */
export const CreatePaymentResponse$inboundSchema: z.ZodMiniType<
  CreatePaymentResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.PaymentResponseDto$inboundSchema,
  errors: z.lazy(() => CreatePaymentErrors$inboundSchema),
  rawData: z.lazy(() => CreatePaymentRawData$inboundSchema),
});

export function createPaymentResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentResponse' from JSON`,
  );
}
