/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBookingProposalAsyncGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type CreateBookingProposalAsyncFile = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export const CreateBookingProposalAsyncBookingType = {
  Invoice: "INVOICE",
  Bill: "BILL",
  CreditNote: "CREDIT_NOTE",
  VendorCredit: "VENDOR_CREDIT",
} as const;
export type CreateBookingProposalAsyncBookingType = ClosedEnum<
  typeof CreateBookingProposalAsyncBookingType
>;

export type CreateBookingProposalAsyncFolderManagement = {
  category?: string | undefined;
  folder?: string | undefined;
  register?: string | undefined;
};

export type CreateBookingProposalAsyncRequestBody = {
  files?: Array<CreateBookingProposalAsyncFile> | undefined;
  bookingType?: CreateBookingProposalAsyncBookingType | undefined;
  bookingProposal?: models.CreateBookingProposalRequestDtoV2 | undefined;
  folderManagement?: CreateBookingProposalAsyncFolderManagement | undefined;
};

export type CreateBookingProposalAsyncRequest = {
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
  body: CreateBookingProposalAsyncRequestBody;
};

export type CreateBookingProposalAsyncPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateBookingProposalAsyncMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateBookingProposalAsyncPagination | null | undefined;
};

export type CreateBookingProposalAsyncErrors = {};

export type CreateBookingProposalAsyncRawData = {};

/**
 * Booking proposal queued successfully. Processed asynchronously and returns 202 with taskId.
 */
export type CreateBookingProposalAsyncResponse = {
  meta?: CreateBookingProposalAsyncMeta | null | undefined;
  data: models.TaskIdResponseDto;
  errors: CreateBookingProposalAsyncErrors | null;
  rawData: CreateBookingProposalAsyncRawData | null;
};

/** @internal */
export type CreateBookingProposalAsyncFile$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateBookingProposalAsyncFile$outboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncFile$Outbound,
  CreateBookingProposalAsyncFile
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createBookingProposalAsyncFileToJSON(
  createBookingProposalAsyncFile: CreateBookingProposalAsyncFile,
): string {
  return JSON.stringify(
    CreateBookingProposalAsyncFile$outboundSchema.parse(
      createBookingProposalAsyncFile,
    ),
  );
}

/** @internal */
export const CreateBookingProposalAsyncBookingType$outboundSchema:
  z.ZodMiniEnum<typeof CreateBookingProposalAsyncBookingType> = z.enum(
    CreateBookingProposalAsyncBookingType,
  );

/** @internal */
export type CreateBookingProposalAsyncFolderManagement$Outbound = {
  category?: string | undefined;
  folder?: string | undefined;
  register?: string | undefined;
};

/** @internal */
export const CreateBookingProposalAsyncFolderManagement$outboundSchema:
  z.ZodMiniType<
    CreateBookingProposalAsyncFolderManagement$Outbound,
    CreateBookingProposalAsyncFolderManagement
  > = z.object({
    category: z.optional(z.string()),
    folder: z.optional(z.string()),
    register: z.optional(z.string()),
  });

export function createBookingProposalAsyncFolderManagementToJSON(
  createBookingProposalAsyncFolderManagement:
    CreateBookingProposalAsyncFolderManagement,
): string {
  return JSON.stringify(
    CreateBookingProposalAsyncFolderManagement$outboundSchema.parse(
      createBookingProposalAsyncFolderManagement,
    ),
  );
}

/** @internal */
export type CreateBookingProposalAsyncRequestBody$Outbound = {
  files?: Array<CreateBookingProposalAsyncFile$Outbound> | undefined;
  bookingType?: string | undefined;
  bookingProposal?:
    | models.CreateBookingProposalRequestDtoV2$Outbound
    | undefined;
  folderManagement?:
    | CreateBookingProposalAsyncFolderManagement$Outbound
    | undefined;
};

/** @internal */
export const CreateBookingProposalAsyncRequestBody$outboundSchema:
  z.ZodMiniType<
    CreateBookingProposalAsyncRequestBody$Outbound,
    CreateBookingProposalAsyncRequestBody
  > = z.object({
    files: z.optional(
      z.array(z.lazy(() => CreateBookingProposalAsyncFile$outboundSchema)),
    ),
    bookingType: z.optional(
      CreateBookingProposalAsyncBookingType$outboundSchema,
    ),
    bookingProposal: z.optional(
      models.CreateBookingProposalRequestDtoV2$outboundSchema,
    ),
    folderManagement: z.optional(
      z.lazy(() => CreateBookingProposalAsyncFolderManagement$outboundSchema),
    ),
  });

export function createBookingProposalAsyncRequestBodyToJSON(
  createBookingProposalAsyncRequestBody: CreateBookingProposalAsyncRequestBody,
): string {
  return JSON.stringify(
    CreateBookingProposalAsyncRequestBody$outboundSchema.parse(
      createBookingProposalAsyncRequestBody,
    ),
  );
}

/** @internal */
export type CreateBookingProposalAsyncRequest$Outbound = {
  companyId?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
  body: CreateBookingProposalAsyncRequestBody$Outbound;
};

/** @internal */
export const CreateBookingProposalAsyncRequest$outboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncRequest$Outbound,
  CreateBookingProposalAsyncRequest
> = z.object({
  companyId: z.optional(z.string()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
  body: z.lazy(() => CreateBookingProposalAsyncRequestBody$outboundSchema),
});

export function createBookingProposalAsyncRequestToJSON(
  createBookingProposalAsyncRequest: CreateBookingProposalAsyncRequest,
): string {
  return JSON.stringify(
    CreateBookingProposalAsyncRequest$outboundSchema.parse(
      createBookingProposalAsyncRequest,
    ),
  );
}

/** @internal */
export const CreateBookingProposalAsyncPagination$inboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createBookingProposalAsyncPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalAsyncPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingProposalAsyncPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalAsyncPagination' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalAsyncMeta$inboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(
      z.lazy(() => CreateBookingProposalAsyncPagination$inboundSchema),
    ),
  ),
});

export function createBookingProposalAsyncMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalAsyncMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalAsyncMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalAsyncMeta' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalAsyncErrors$inboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncErrors,
  unknown
> = z.object({});

export function createBookingProposalAsyncErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalAsyncErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalAsyncErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalAsyncErrors' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalAsyncRawData$inboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncRawData,
  unknown
> = z.object({});

export function createBookingProposalAsyncRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalAsyncRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalAsyncRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalAsyncRawData' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalAsyncResponse$inboundSchema: z.ZodMiniType<
  CreateBookingProposalAsyncResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateBookingProposalAsyncMeta$inboundSchema)),
  ),
  data: models.TaskIdResponseDto$inboundSchema,
  errors: types.nullable(
    z.lazy(() => CreateBookingProposalAsyncErrors$inboundSchema),
  ),
  rawData: types.nullable(
    z.lazy(() => CreateBookingProposalAsyncRawData$inboundSchema),
  ),
});

export function createBookingProposalAsyncResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalAsyncResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      CreateBookingProposalAsyncResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalAsyncResponse' from JSON`,
  );
}
