/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateProjectRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
  body: models.CreateProjectRequestDto;
};

export type CreateProjectErrors = {};

export type CreateProjectRawData = {};

export type CreateProjectResponse = {
  meta: models.MetaResponse;
  data: models.ProjectResponseDto;
  errors: CreateProjectErrors;
  rawData: CreateProjectRawData;
};

/** @internal */
export type CreateProjectRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
  body: models.CreateProjectRequestDto$Outbound;
};

/** @internal */
export const CreateProjectRequest$outboundSchema: z.ZodMiniType<
  CreateProjectRequest$Outbound,
  CreateProjectRequest
> = z.pipe(
  z.object({
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
    body: models.CreateProjectRequestDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function createProjectRequestToJSON(
  createProjectRequest: CreateProjectRequest,
): string {
  return JSON.stringify(
    CreateProjectRequest$outboundSchema.parse(createProjectRequest),
  );
}

/** @internal */
export const CreateProjectErrors$inboundSchema: z.ZodMiniType<
  CreateProjectErrors,
  unknown
> = z.object({});

export function createProjectErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateProjectErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProjectErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProjectErrors' from JSON`,
  );
}

/** @internal */
export const CreateProjectRawData$inboundSchema: z.ZodMiniType<
  CreateProjectRawData,
  unknown
> = z.object({});

export function createProjectRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateProjectRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProjectRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProjectRawData' from JSON`,
  );
}

/** @internal */
export const CreateProjectResponse$inboundSchema: z.ZodMiniType<
  CreateProjectResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.ProjectResponseDto$inboundSchema,
  errors: z.lazy(() => CreateProjectErrors$inboundSchema),
  rawData: z.lazy(() => CreateProjectRawData$inboundSchema),
});

export function createProjectResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateProjectResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateProjectResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateProjectResponse' from JSON`,
  );
}
