/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type CreateWebhookRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateWebhookRequestDto;
};

/** @internal */
export type CreateWebhookRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.CreateWebhookRequestDto$Outbound;
};

/** @internal */
export const CreateWebhookRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookRequest$Outbound,
  CreateWebhookRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.CreateWebhookRequestDto$outboundSchema,
});

export function createWebhookRequestToJSON(
  createWebhookRequest: CreateWebhookRequest,
): string {
  return JSON.stringify(
    CreateWebhookRequest$outboundSchema.parse(createWebhookRequest),
  );
}
