/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateContactsV1Request = {
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  body: models.CreateContactByBatchMetaDataDto;
};

export type CreateContactsV1Pagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateContactsV1Meta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateContactsV1Pagination | null | undefined;
};

export type CreateContactsV1Errors = {};

export type CreateContactsV1RawData = {};

/**
 * Contacts created successfully in bulk
 */
export type CreateContactsV1Response = {
  meta?: CreateContactsV1Meta | null | undefined;
  data: models.ContactByBatchMetaDataResponseDto;
  errors: CreateContactsV1Errors | null;
  rawData: CreateContactsV1RawData | null;
};

/** @internal */
export type CreateContactsV1Request$Outbound = {
  companyId?: string | undefined;
  body: models.CreateContactByBatchMetaDataDto$Outbound;
};

/** @internal */
export const CreateContactsV1Request$outboundSchema: z.ZodMiniType<
  CreateContactsV1Request$Outbound,
  CreateContactsV1Request
> = z.object({
  companyId: z.optional(z.string()),
  body: models.CreateContactByBatchMetaDataDto$outboundSchema,
});

export function createContactsV1RequestToJSON(
  createContactsV1Request: CreateContactsV1Request,
): string {
  return JSON.stringify(
    CreateContactsV1Request$outboundSchema.parse(createContactsV1Request),
  );
}

/** @internal */
export const CreateContactsV1Pagination$inboundSchema: z.ZodMiniType<
  CreateContactsV1Pagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createContactsV1PaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateContactsV1Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateContactsV1Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateContactsV1Pagination' from JSON`,
  );
}

/** @internal */
export const CreateContactsV1Meta$inboundSchema: z.ZodMiniType<
  CreateContactsV1Meta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateContactsV1Pagination$inboundSchema)),
  ),
});

export function createContactsV1MetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateContactsV1Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateContactsV1Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateContactsV1Meta' from JSON`,
  );
}

/** @internal */
export const CreateContactsV1Errors$inboundSchema: z.ZodMiniType<
  CreateContactsV1Errors,
  unknown
> = z.object({});

export function createContactsV1ErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateContactsV1Errors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateContactsV1Errors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateContactsV1Errors' from JSON`,
  );
}

/** @internal */
export const CreateContactsV1RawData$inboundSchema: z.ZodMiniType<
  CreateContactsV1RawData,
  unknown
> = z.object({});

export function createContactsV1RawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateContactsV1RawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateContactsV1RawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateContactsV1RawData' from JSON`,
  );
}

/** @internal */
export const CreateContactsV1Response$inboundSchema: z.ZodMiniType<
  CreateContactsV1Response,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateContactsV1Meta$inboundSchema)),
  ),
  data: models.ContactByBatchMetaDataResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateContactsV1Errors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => CreateContactsV1RawData$inboundSchema)),
});

export function createContactsV1ResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateContactsV1Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateContactsV1Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateContactsV1Response' from JSON`,
  );
}
