/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBookingProposalV2File = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

export type CreateBookingProposalV2FolderManagement = {
  category?: string | undefined;
  folder?: string | undefined;
  register?: string | undefined;
};

export type CreateBookingProposalV2RequestBody = {
  files?: Array<CreateBookingProposalV2File> | undefined;
  bookingType?: string | undefined;
  bookingProposal?: models.CreateBookingProposalRequestDtoV2 | undefined;
  folderManagement?: CreateBookingProposalV2FolderManagement | undefined;
};

export type CreateBookingProposalV2Request = {
  companyId?: string | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
  body: CreateBookingProposalV2RequestBody;
};

export type CreateBookingProposalV2Errors = {};

export type CreateBookingProposalV2RawData = {};

export type CreateBookingProposalV2Response = {
  meta: models.MetaResponse;
  data: models.BookingProposalResponseDtoV2;
  errors: CreateBookingProposalV2Errors;
  rawData: CreateBookingProposalV2RawData;
};

/** @internal */
export type CreateBookingProposalV2File$Outbound = {
  fileName: string;
  content: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Uint8Array;
};

/** @internal */
export const CreateBookingProposalV2File$outboundSchema: z.ZodMiniType<
  CreateBookingProposalV2File$Outbound,
  CreateBookingProposalV2File
> = z.object({
  fileName: z.string(),
  content: z.union([
    z.custom<ReadableStream<Uint8Array>>(x => x instanceof ReadableStream),
    z.custom<Blob>(x => x instanceof Blob),
    z.custom<ArrayBuffer>(x => x instanceof ArrayBuffer),
    z.custom<Uint8Array>(x => x instanceof Uint8Array),
  ]),
});

export function createBookingProposalV2FileToJSON(
  createBookingProposalV2File: CreateBookingProposalV2File,
): string {
  return JSON.stringify(
    CreateBookingProposalV2File$outboundSchema.parse(
      createBookingProposalV2File,
    ),
  );
}

/** @internal */
export type CreateBookingProposalV2FolderManagement$Outbound = {
  category?: string | undefined;
  folder?: string | undefined;
  register?: string | undefined;
};

/** @internal */
export const CreateBookingProposalV2FolderManagement$outboundSchema:
  z.ZodMiniType<
    CreateBookingProposalV2FolderManagement$Outbound,
    CreateBookingProposalV2FolderManagement
  > = z.object({
    category: z.optional(z.string()),
    folder: z.optional(z.string()),
    register: z.optional(z.string()),
  });

export function createBookingProposalV2FolderManagementToJSON(
  createBookingProposalV2FolderManagement:
    CreateBookingProposalV2FolderManagement,
): string {
  return JSON.stringify(
    CreateBookingProposalV2FolderManagement$outboundSchema.parse(
      createBookingProposalV2FolderManagement,
    ),
  );
}

/** @internal */
export type CreateBookingProposalV2RequestBody$Outbound = {
  files?: Array<CreateBookingProposalV2File$Outbound> | undefined;
  bookingType?: string | undefined;
  bookingProposal?:
    | models.CreateBookingProposalRequestDtoV2$Outbound
    | undefined;
  folderManagement?:
    | CreateBookingProposalV2FolderManagement$Outbound
    | undefined;
};

/** @internal */
export const CreateBookingProposalV2RequestBody$outboundSchema: z.ZodMiniType<
  CreateBookingProposalV2RequestBody$Outbound,
  CreateBookingProposalV2RequestBody
> = z.object({
  files: z.optional(
    z.array(z.lazy(() => CreateBookingProposalV2File$outboundSchema)),
  ),
  bookingType: z.optional(z.string()),
  bookingProposal: z.optional(
    models.CreateBookingProposalRequestDtoV2$outboundSchema,
  ),
  folderManagement: z.optional(
    z.lazy(() => CreateBookingProposalV2FolderManagement$outboundSchema),
  ),
});

export function createBookingProposalV2RequestBodyToJSON(
  createBookingProposalV2RequestBody: CreateBookingProposalV2RequestBody,
): string {
  return JSON.stringify(
    CreateBookingProposalV2RequestBody$outboundSchema.parse(
      createBookingProposalV2RequestBody,
    ),
  );
}

/** @internal */
export type CreateBookingProposalV2Request$Outbound = {
  companyId?: string | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
  body: CreateBookingProposalV2RequestBody$Outbound;
};

/** @internal */
export const CreateBookingProposalV2Request$outboundSchema: z.ZodMiniType<
  CreateBookingProposalV2Request$Outbound,
  CreateBookingProposalV2Request
> = z.pipe(
  z.object({
    companyId: z.optional(z.string()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
    body: z.lazy(() => CreateBookingProposalV2RequestBody$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function createBookingProposalV2RequestToJSON(
  createBookingProposalV2Request: CreateBookingProposalV2Request,
): string {
  return JSON.stringify(
    CreateBookingProposalV2Request$outboundSchema.parse(
      createBookingProposalV2Request,
    ),
  );
}

/** @internal */
export const CreateBookingProposalV2Errors$inboundSchema: z.ZodMiniType<
  CreateBookingProposalV2Errors,
  unknown
> = z.object({});

export function createBookingProposalV2ErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalV2Errors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalV2Errors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalV2Errors' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalV2RawData$inboundSchema: z.ZodMiniType<
  CreateBookingProposalV2RawData,
  unknown
> = z.object({});

export function createBookingProposalV2RawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalV2RawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalV2RawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalV2RawData' from JSON`,
  );
}

/** @internal */
export const CreateBookingProposalV2Response$inboundSchema: z.ZodMiniType<
  CreateBookingProposalV2Response,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.BookingProposalResponseDtoV2$inboundSchema,
  errors: z.lazy(() => CreateBookingProposalV2Errors$inboundSchema),
  rawData: z.lazy(() => CreateBookingProposalV2RawData$inboundSchema),
});

export function createBookingProposalV2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingProposalV2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingProposalV2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingProposalV2Response' from JSON`,
  );
}
