/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreatePaymentTermRequest = {
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  body: models.CreatePaymentTermRequestDto;
};

export type CreatePaymentTermPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreatePaymentTermMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreatePaymentTermPagination | null | undefined;
};

export type CreatePaymentTermErrors = {};

export type CreatePaymentTermRawData = {};

/**
 * Payment term created successfully
 */
export type CreatePaymentTermResponse = {
  meta?: CreatePaymentTermMeta | null | undefined;
  data: models.PaymentTermResponseDto;
  errors: CreatePaymentTermErrors | null;
  rawData: CreatePaymentTermRawData | null;
};

/** @internal */
export type CreatePaymentTermRequest$Outbound = {
  companyId?: string | undefined;
  body: models.CreatePaymentTermRequestDto$Outbound;
};

/** @internal */
export const CreatePaymentTermRequest$outboundSchema: z.ZodMiniType<
  CreatePaymentTermRequest$Outbound,
  CreatePaymentTermRequest
> = z.object({
  companyId: z.optional(z.string()),
  body: models.CreatePaymentTermRequestDto$outboundSchema,
});

export function createPaymentTermRequestToJSON(
  createPaymentTermRequest: CreatePaymentTermRequest,
): string {
  return JSON.stringify(
    CreatePaymentTermRequest$outboundSchema.parse(createPaymentTermRequest),
  );
}

/** @internal */
export const CreatePaymentTermPagination$inboundSchema: z.ZodMiniType<
  CreatePaymentTermPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createPaymentTermPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermPagination' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermMeta$inboundSchema: z.ZodMiniType<
  CreatePaymentTermMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreatePaymentTermPagination$inboundSchema)),
  ),
});

export function createPaymentTermMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermMeta' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermErrors$inboundSchema: z.ZodMiniType<
  CreatePaymentTermErrors,
  unknown
> = z.object({});

export function createPaymentTermErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermErrors' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermRawData$inboundSchema: z.ZodMiniType<
  CreatePaymentTermRawData,
  unknown
> = z.object({});

export function createPaymentTermRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermRawData' from JSON`,
  );
}

/** @internal */
export const CreatePaymentTermResponse$inboundSchema: z.ZodMiniType<
  CreatePaymentTermResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreatePaymentTermMeta$inboundSchema)),
  ),
  data: models.PaymentTermResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreatePaymentTermErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => CreatePaymentTermRawData$inboundSchema)),
});

export function createPaymentTermResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreatePaymentTermResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreatePaymentTermResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreatePaymentTermResponse' from JSON`,
  );
}
