/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateBookingsRequest = {
  companyId?: string | undefined;
  body: models.CreateBookingsRequestDto;
};

export type CreateBookingsErrors = {};

export type CreateBookingsRawData = {};

export type CreateBookingsResponse = {
  meta: models.MetaResponse;
  data: models.BookingsResponseDto;
  errors: CreateBookingsErrors;
  rawData: CreateBookingsRawData;
};

/** @internal */
export type CreateBookingsRequest$Outbound = {
  companyId?: string | undefined;
  body: models.CreateBookingsRequestDto$Outbound;
};

/** @internal */
export const CreateBookingsRequest$outboundSchema: z.ZodMiniType<
  CreateBookingsRequest$Outbound,
  CreateBookingsRequest
> = z.object({
  companyId: z.optional(z.string()),
  body: models.CreateBookingsRequestDto$outboundSchema,
});

export function createBookingsRequestToJSON(
  createBookingsRequest: CreateBookingsRequest,
): string {
  return JSON.stringify(
    CreateBookingsRequest$outboundSchema.parse(createBookingsRequest),
  );
}

/** @internal */
export const CreateBookingsErrors$inboundSchema: z.ZodMiniType<
  CreateBookingsErrors,
  unknown
> = z.object({});

export function createBookingsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsErrors' from JSON`,
  );
}

/** @internal */
export const CreateBookingsRawData$inboundSchema: z.ZodMiniType<
  CreateBookingsRawData,
  unknown
> = z.object({});

export function createBookingsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsRawData' from JSON`,
  );
}

/** @internal */
export const CreateBookingsResponse$inboundSchema: z.ZodMiniType<
  CreateBookingsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.BookingsResponseDto$inboundSchema,
  errors: z.lazy(() => CreateBookingsErrors$inboundSchema),
  rawData: z.lazy(() => CreateBookingsRawData$inboundSchema),
});

export function createBookingsResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateBookingsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateBookingsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateBookingsResponse' from JSON`,
  );
}
