/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type CreateWebhookConfigPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type CreateWebhookConfigMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: CreateWebhookConfigPagination | null | undefined;
};

export type CreateWebhookConfigErrors = {};

export type CreateWebhookConfigRawData = {};

/**
 * Webhook created successfully
 */
export type CreateWebhookConfigResponse = {
  meta?: CreateWebhookConfigMeta | null | undefined;
  data: models.WebhookResponseDto;
  errors: CreateWebhookConfigErrors | null;
  rawData: CreateWebhookConfigRawData | null;
};

/** @internal */
export const CreateWebhookConfigPagination$inboundSchema: z.ZodMiniType<
  CreateWebhookConfigPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function createWebhookConfigPaginationFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookConfigPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookConfigPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookConfigPagination' from JSON`,
  );
}

/** @internal */
export const CreateWebhookConfigMeta$inboundSchema: z.ZodMiniType<
  CreateWebhookConfigMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => CreateWebhookConfigPagination$inboundSchema)),
  ),
});

export function createWebhookConfigMetaFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookConfigMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookConfigMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookConfigMeta' from JSON`,
  );
}

/** @internal */
export const CreateWebhookConfigErrors$inboundSchema: z.ZodMiniType<
  CreateWebhookConfigErrors,
  unknown
> = z.object({});

export function createWebhookConfigErrorsFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookConfigErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookConfigErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookConfigErrors' from JSON`,
  );
}

/** @internal */
export const CreateWebhookConfigRawData$inboundSchema: z.ZodMiniType<
  CreateWebhookConfigRawData,
  unknown
> = z.object({});

export function createWebhookConfigRawDataFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookConfigRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookConfigRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookConfigRawData' from JSON`,
  );
}

/** @internal */
export const CreateWebhookConfigResponse$inboundSchema: z.ZodMiniType<
  CreateWebhookConfigResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => CreateWebhookConfigMeta$inboundSchema)),
  ),
  data: models.WebhookResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => CreateWebhookConfigErrors$inboundSchema)),
  rawData: types.nullable(
    z.lazy(() => CreateWebhookConfigRawData$inboundSchema),
  ),
});

export function createWebhookConfigResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateWebhookConfigResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateWebhookConfigResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateWebhookConfigResponse' from JSON`,
  );
}
