/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeletePaymentRequest = {
  paymentId: string;
  companyId?: string | undefined;
};

/** @internal */
export type DeletePaymentRequest$Outbound = {
  paymentId: string;
  companyId?: string | undefined;
};

/** @internal */
export const DeletePaymentRequest$outboundSchema: z.ZodMiniType<
  DeletePaymentRequest$Outbound,
  DeletePaymentRequest
> = z.object({
  paymentId: z.string(),
  companyId: z.optional(z.string()),
});

export function deletePaymentRequestToJSON(
  deletePaymentRequest: DeletePaymentRequest,
): string {
  return JSON.stringify(
    DeletePaymentRequest$outboundSchema.parse(deletePaymentRequest),
  );
}
