/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteRegisteredSystemGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type DeleteRegisteredSystemRequest = {
  targetSystem: string;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

/** @internal */
export type DeleteRegisteredSystemRequest$Outbound = {
  targetSystem: string;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const DeleteRegisteredSystemRequest$outboundSchema: z.ZodMiniType<
  DeleteRegisteredSystemRequest$Outbound,
  DeleteRegisteredSystemRequest
> = z.object({
  targetSystem: z.string(),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function deleteRegisteredSystemRequestToJSON(
  deleteRegisteredSystemRequest: DeleteRegisteredSystemRequest,
): string {
  return JSON.stringify(
    DeleteRegisteredSystemRequest$outboundSchema.parse(
      deleteRegisteredSystemRequest,
    ),
  );
}
