/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type DeleteEndUserGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type DeleteEndUserRequest = {
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

/**
 * Operation completed successfully
 */
export type DeleteEndUserResponse = {
  message?: string | undefined;
};

/** @internal */
export type DeleteEndUserRequest$Outbound = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const DeleteEndUserRequest$outboundSchema: z.ZodMiniType<
  DeleteEndUserRequest$Outbound,
  DeleteEndUserRequest
> = z.object({
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function deleteEndUserRequestToJSON(
  deleteEndUserRequest: DeleteEndUserRequest,
): string {
  return JSON.stringify(
    DeleteEndUserRequest$outboundSchema.parse(deleteEndUserRequest),
  );
}

/** @internal */
export const DeleteEndUserResponse$inboundSchema: z.ZodMiniType<
  DeleteEndUserResponse,
  unknown
> = z.object({
  message: types.optional(types.string()),
});

export function deleteEndUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteEndUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteEndUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteEndUserResponse' from JSON`,
  );
}
