/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCreditNotesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetCreditNotesErrors = {};

export type GetCreditNotesRawData = {};

export type GetCreditNotesResponse = {
  meta: models.MetaResponse;
  data: Array<models.CreditNoteResponseDto>;
  errors: GetCreditNotesErrors;
  rawData: GetCreditNotesRawData;
};

/** @internal */
export type GetCreditNotesRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetCreditNotesRequest$outboundSchema: z.ZodMiniType<
  GetCreditNotesRequest$Outbound,
  GetCreditNotesRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getCreditNotesRequestToJSON(
  getCreditNotesRequest: GetCreditNotesRequest,
): string {
  return JSON.stringify(
    GetCreditNotesRequest$outboundSchema.parse(getCreditNotesRequest),
  );
}

/** @internal */
export const GetCreditNotesErrors$inboundSchema: z.ZodMiniType<
  GetCreditNotesErrors,
  unknown
> = z.object({});

export function getCreditNotesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesErrors' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesRawData$inboundSchema: z.ZodMiniType<
  GetCreditNotesRawData,
  unknown
> = z.object({});

export function getCreditNotesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesRawData' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesResponse$inboundSchema: z.ZodMiniType<
  GetCreditNotesResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.CreditNoteResponseDto$inboundSchema),
  errors: z.lazy(() => GetCreditNotesErrors$inboundSchema),
  rawData: z.lazy(() => GetCreditNotesRawData$inboundSchema),
});

export function getCreditNotesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesResponse' from JSON`,
  );
}
