/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetSalesOrderRequest = {
  salesOrderId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetSalesOrderErrors = {};

export type GetSalesOrderRawData = {};

export type GetSalesOrderResponse = {
  meta: models.MetaResponse;
  data: Array<models.SalesOrderResponseDto>;
  errors: GetSalesOrderErrors;
  rawData: GetSalesOrderRawData;
};

/** @internal */
export type GetSalesOrderRequest$Outbound = {
  salesOrderId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetSalesOrderRequest$outboundSchema: z.ZodMiniType<
  GetSalesOrderRequest$Outbound,
  GetSalesOrderRequest
> = z.object({
  salesOrderId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getSalesOrderRequestToJSON(
  getSalesOrderRequest: GetSalesOrderRequest,
): string {
  return JSON.stringify(
    GetSalesOrderRequest$outboundSchema.parse(getSalesOrderRequest),
  );
}

/** @internal */
export const GetSalesOrderErrors$inboundSchema: z.ZodMiniType<
  GetSalesOrderErrors,
  unknown
> = z.object({});

export function getSalesOrderErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrderErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrderErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrderErrors' from JSON`,
  );
}

/** @internal */
export const GetSalesOrderRawData$inboundSchema: z.ZodMiniType<
  GetSalesOrderRawData,
  unknown
> = z.object({});

export function getSalesOrderRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrderRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrderRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrderRawData' from JSON`,
  );
}

/** @internal */
export const GetSalesOrderResponse$inboundSchema: z.ZodMiniType<
  GetSalesOrderResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.SalesOrderResponseDto$inboundSchema),
  errors: z.lazy(() => GetSalesOrderErrors$inboundSchema),
  rawData: z.lazy(() => GetSalesOrderRawData$inboundSchema),
});

export function getSalesOrderResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrderResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrderResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrderResponse' from JSON`,
  );
}
