/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Filter invoices by unified status
 */
export const GetInvoicesStatus = {
  Draft: "DRAFT",
  Corrective: "CORRECTIVE",
  Submitted: "SUBMITTED",
  DocumentCreated: "DOCUMENT_CREATED",
  Open: "OPEN",
  PartiallyPaid: "PARTIALLY_PAID",
  Paid: "PAID",
  PartiallyOverdue: "PARTIALLY_OVERDUE",
  Overdue: "OVERDUE",
  Voided: "VOIDED",
} as const;
/**
 * Filter invoices by unified status
 */
export type GetInvoicesStatus = ClosedEnum<typeof GetInvoicesStatus>;

/**
 * Filter invoices by payment status
 */
export const GetInvoicesPaymentStatus = {
  NoOpenItem: "NO_OPEN_ITEM",
  Pending: "PENDING",
  PartlyPaid: "PARTLY_PAID",
  Paid: "PAID",
  Debited: "DEBITED",
  CreditNoteCleared: "CREDIT_NOTE_CLEARED",
  ClearedWithCreditNote: "CLEARED_WITH_CREDIT_NOTE",
  BadDebt: "BAD_DEBT",
  PartialCancellation: "PARTIAL_CANCELLATION",
  Canceled: "CANCELED",
  Unknown: "UNKNOWN",
} as const;
/**
 * Filter invoices by payment status
 */
export type GetInvoicesPaymentStatus = ClosedEnum<
  typeof GetInvoicesPaymentStatus
>;

/**
 * Field to sort the results by
 */
export const GetInvoicesOrderField = {
  InvoiceDate: "invoiceDate",
  InvoiceNumber: "invoiceNumber",
  CreatedDate: "createdDate",
  UpdatedDate: "updatedDate",
} as const;
/**
 * Field to sort the results by
 */
export type GetInvoicesOrderField = ClosedEnum<typeof GetInvoicesOrderField>;

/**
 * Sort direction for the ordered results
 */
export const GetInvoicesOrderDir = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Sort direction for the ordered results
 */
export type GetInvoicesOrderDir = ClosedEnum<typeof GetInvoicesOrderDir>;

export type GetInvoicesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * ISO 8601 timestamp; only records modified after this date are returned
   */
  lastModifiedAt?: string | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * Filter invoices by unified status
   */
  status?: GetInvoicesStatus | undefined;
  /**
   * Filter invoices by payment status
   */
  paymentStatus?: GetInvoicesPaymentStatus | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * Field to sort the results by
   */
  orderField?: GetInvoicesOrderField | undefined;
  /**
   * Sort direction for the ordered results
   */
  orderDir?: GetInvoicesOrderDir | undefined;
  /**
   * ISO 8601 date; only invoices with a due date on or after this date are returned
   */
  dueDateFrom?: string | undefined;
};

export type GetInvoicesPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetInvoicesMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetInvoicesPagination | null | undefined;
};

export type GetInvoicesErrors = {};

export type GetInvoicesRawData = {};

/**
 * List of invoices for the authenticated end user's connected target system
 */
export type GetInvoicesResponse = {
  meta?: GetInvoicesMeta | null | undefined;
  data: Array<models.InvoiceResponseDto>;
  errors: GetInvoicesErrors | null;
  rawData: GetInvoicesRawData | null;
};

/** @internal */
export const GetInvoicesStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesStatus
> = z.enum(GetInvoicesStatus);

/** @internal */
export const GetInvoicesPaymentStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesPaymentStatus
> = z.enum(GetInvoicesPaymentStatus);

/** @internal */
export const GetInvoicesOrderField$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesOrderField
> = z.enum(GetInvoicesOrderField);

/** @internal */
export const GetInvoicesOrderDir$outboundSchema: z.ZodMiniEnum<
  typeof GetInvoicesOrderDir
> = z.enum(GetInvoicesOrderDir);

/** @internal */
export type GetInvoicesRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: string | undefined;
  paymentStatus?: string | undefined;
  rawData?: boolean | undefined;
  orderField?: string | undefined;
  orderDir?: string | undefined;
  dueDateFrom?: string | undefined;
};

/** @internal */
export const GetInvoicesRequest$outboundSchema: z.ZodMiniType<
  GetInvoicesRequest$Outbound,
  GetInvoicesRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  status: z.optional(GetInvoicesStatus$outboundSchema),
  paymentStatus: z.optional(GetInvoicesPaymentStatus$outboundSchema),
  rawData: z.optional(z.boolean()),
  orderField: z.optional(GetInvoicesOrderField$outboundSchema),
  orderDir: z.optional(GetInvoicesOrderDir$outboundSchema),
  dueDateFrom: z.optional(z.string()),
});

export function getInvoicesRequestToJSON(
  getInvoicesRequest: GetInvoicesRequest,
): string {
  return JSON.stringify(
    GetInvoicesRequest$outboundSchema.parse(getInvoicesRequest),
  );
}

/** @internal */
export const GetInvoicesPagination$inboundSchema: z.ZodMiniType<
  GetInvoicesPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getInvoicesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicesPagination' from JSON`,
  );
}

/** @internal */
export const GetInvoicesMeta$inboundSchema: z.ZodMiniType<
  GetInvoicesMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetInvoicesPagination$inboundSchema)),
  ),
});

export function getInvoicesMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicesMeta' from JSON`,
  );
}

/** @internal */
export const GetInvoicesErrors$inboundSchema: z.ZodMiniType<
  GetInvoicesErrors,
  unknown
> = z.object({});

export function getInvoicesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicesErrors' from JSON`,
  );
}

/** @internal */
export const GetInvoicesRawData$inboundSchema: z.ZodMiniType<
  GetInvoicesRawData,
  unknown
> = z.object({});

export function getInvoicesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicesRawData' from JSON`,
  );
}

/** @internal */
export const GetInvoicesResponse$inboundSchema: z.ZodMiniType<
  GetInvoicesResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetInvoicesMeta$inboundSchema))),
  data: z.array(models.InvoiceResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetInvoicesErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetInvoicesRawData$inboundSchema)),
});

export function getInvoicesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicesResponse' from JSON`,
  );
}
