/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetUserInfoErrors = {};

export type GetUserInfoRawData = {};

export type GetUserInfoResponse = {
  meta: models.MetaResponse;
  data: models.UserInfoResponseDto;
  errors: GetUserInfoErrors;
  rawData: GetUserInfoRawData;
};

/** @internal */
export const GetUserInfoErrors$inboundSchema: z.ZodMiniType<
  GetUserInfoErrors,
  unknown
> = z.object({});

export function getUserInfoErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetUserInfoErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserInfoErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserInfoErrors' from JSON`,
  );
}

/** @internal */
export const GetUserInfoRawData$inboundSchema: z.ZodMiniType<
  GetUserInfoRawData,
  unknown
> = z.object({});

export function getUserInfoRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetUserInfoRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserInfoRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserInfoRawData' from JSON`,
  );
}

/** @internal */
export const GetUserInfoResponse$inboundSchema: z.ZodMiniType<
  GetUserInfoResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.UserInfoResponseDto$inboundSchema,
  errors: z.lazy(() => GetUserInfoErrors$inboundSchema),
  rawData: z.lazy(() => GetUserInfoRawData$inboundSchema),
});

export function getUserInfoResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserInfoResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserInfoResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserInfoResponse' from JSON`,
  );
}
