/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetExpensesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetExpensesErrors = {};

export type GetExpensesRawData = {};

export type GetExpensesResponse = {
  meta: models.MetaResponse;
  data: Array<models.ExpenseResponseDto>;
  errors: GetExpensesErrors;
  rawData: GetExpensesRawData;
};

/** @internal */
export type GetExpensesRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetExpensesRequest$outboundSchema: z.ZodMiniType<
  GetExpensesRequest$Outbound,
  GetExpensesRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getExpensesRequestToJSON(
  getExpensesRequest: GetExpensesRequest,
): string {
  return JSON.stringify(
    GetExpensesRequest$outboundSchema.parse(getExpensesRequest),
  );
}

/** @internal */
export const GetExpensesErrors$inboundSchema: z.ZodMiniType<
  GetExpensesErrors,
  unknown
> = z.object({});

export function getExpensesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetExpensesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetExpensesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetExpensesErrors' from JSON`,
  );
}

/** @internal */
export const GetExpensesRawData$inboundSchema: z.ZodMiniType<
  GetExpensesRawData,
  unknown
> = z.object({});

export function getExpensesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetExpensesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetExpensesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetExpensesRawData' from JSON`,
  );
}

/** @internal */
export const GetExpensesResponse$inboundSchema: z.ZodMiniType<
  GetExpensesResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.ExpenseResponseDto$inboundSchema),
  errors: z.lazy(() => GetExpensesErrors$inboundSchema),
  rawData: z.lazy(() => GetExpensesRawData$inboundSchema),
});

export function getExpensesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetExpensesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetExpensesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetExpensesResponse' from JSON`,
  );
}
