/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBankAccountRequest = {
  bankAccountId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetBankAccountPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetBankAccountMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetBankAccountPagination | null | undefined;
};

export type GetBankAccountErrors = {};

export type GetBankAccountRawData = {};

export type GetBankAccountResponse = {
  meta?: GetBankAccountMeta | null | undefined;
  data: models.BankAccountResponseDto;
  errors: GetBankAccountErrors | null;
  rawData: GetBankAccountRawData | null;
};

/** @internal */
export type GetBankAccountRequest$Outbound = {
  bankAccountId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetBankAccountRequest$outboundSchema: z.ZodMiniType<
  GetBankAccountRequest$Outbound,
  GetBankAccountRequest
> = z.object({
  bankAccountId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getBankAccountRequestToJSON(
  getBankAccountRequest: GetBankAccountRequest,
): string {
  return JSON.stringify(
    GetBankAccountRequest$outboundSchema.parse(getBankAccountRequest),
  );
}

/** @internal */
export const GetBankAccountPagination$inboundSchema: z.ZodMiniType<
  GetBankAccountPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getBankAccountPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountPagination' from JSON`,
  );
}

/** @internal */
export const GetBankAccountMeta$inboundSchema: z.ZodMiniType<
  GetBankAccountMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetBankAccountPagination$inboundSchema)),
  ),
});

export function getBankAccountMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountMeta' from JSON`,
  );
}

/** @internal */
export const GetBankAccountErrors$inboundSchema: z.ZodMiniType<
  GetBankAccountErrors,
  unknown
> = z.object({});

export function getBankAccountErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountErrors' from JSON`,
  );
}

/** @internal */
export const GetBankAccountRawData$inboundSchema: z.ZodMiniType<
  GetBankAccountRawData,
  unknown
> = z.object({});

export function getBankAccountRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountRawData' from JSON`,
  );
}

/** @internal */
export const GetBankAccountResponse$inboundSchema: z.ZodMiniType<
  GetBankAccountResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetBankAccountMeta$inboundSchema))),
  data: models.BankAccountResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetBankAccountErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetBankAccountRawData$inboundSchema)),
});

export function getBankAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountResponse' from JSON`,
  );
}
