/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetVendorCreditsStatus = {
  Draft: "DRAFT",
  Corrective: "CORRECTIVE",
  Submitted: "SUBMITTED",
  DocumentCreated: "DOCUMENT_CREATED",
  Open: "OPEN",
  PartiallyPaid: "PARTIALLY_PAID",
  Paid: "PAID",
  PartiallyOverdue: "PARTIALLY_OVERDUE",
  Overdue: "OVERDUE",
  Voided: "VOIDED",
} as const;
export type GetVendorCreditsStatus = ClosedEnum<typeof GetVendorCreditsStatus>;

export const GetVendorCreditsPaymentStatus = {
  NoOpenItem: "NO_OPEN_ITEM",
  Pending: "PENDING",
  PartlyPaid: "PARTLY_PAID",
  Paid: "PAID",
  Debited: "DEBITED",
  CreditNoteCleared: "CREDIT_NOTE_CLEARED",
  ClearedWithCreditNote: "CLEARED_WITH_CREDIT_NOTE",
  BadDebt: "BAD_DEBT",
  PartialCancellation: "PARTIAL_CANCELLATION",
  Canceled: "CANCELED",
  Unknown: "UNKNOWN",
} as const;
export type GetVendorCreditsPaymentStatus = ClosedEnum<
  typeof GetVendorCreditsPaymentStatus
>;

export type GetVendorCreditsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: GetVendorCreditsStatus | undefined;
  paymentStatus?: GetVendorCreditsPaymentStatus | undefined;
  rawData?: boolean | undefined;
};

export type GetVendorCreditsErrors = {};

export type GetVendorCreditsRawData = {};

export type GetVendorCreditsResponse = {
  meta: models.MetaResponse;
  data: Array<models.VendorCreditResponseDto>;
  errors: GetVendorCreditsErrors;
  rawData: GetVendorCreditsRawData;
};

/** @internal */
export const GetVendorCreditsStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetVendorCreditsStatus
> = z.enum(GetVendorCreditsStatus);

/** @internal */
export const GetVendorCreditsPaymentStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetVendorCreditsPaymentStatus
> = z.enum(GetVendorCreditsPaymentStatus);

/** @internal */
export type GetVendorCreditsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: string | undefined;
  paymentStatus?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetVendorCreditsRequest$outboundSchema: z.ZodMiniType<
  GetVendorCreditsRequest$Outbound,
  GetVendorCreditsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  status: z.optional(GetVendorCreditsStatus$outboundSchema),
  paymentStatus: z.optional(GetVendorCreditsPaymentStatus$outboundSchema),
  rawData: z.optional(z.boolean()),
});

export function getVendorCreditsRequestToJSON(
  getVendorCreditsRequest: GetVendorCreditsRequest,
): string {
  return JSON.stringify(
    GetVendorCreditsRequest$outboundSchema.parse(getVendorCreditsRequest),
  );
}

/** @internal */
export const GetVendorCreditsErrors$inboundSchema: z.ZodMiniType<
  GetVendorCreditsErrors,
  unknown
> = z.object({});

export function getVendorCreditsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetVendorCreditsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVendorCreditsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVendorCreditsErrors' from JSON`,
  );
}

/** @internal */
export const GetVendorCreditsRawData$inboundSchema: z.ZodMiniType<
  GetVendorCreditsRawData,
  unknown
> = z.object({});

export function getVendorCreditsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetVendorCreditsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVendorCreditsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVendorCreditsRawData' from JSON`,
  );
}

/** @internal */
export const GetVendorCreditsResponse$inboundSchema: z.ZodMiniType<
  GetVendorCreditsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.VendorCreditResponseDto$inboundSchema),
  errors: z.lazy(() => GetVendorCreditsErrors$inboundSchema),
  rawData: z.lazy(() => GetVendorCreditsRawData$inboundSchema),
});

export function getVendorCreditsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetVendorCreditsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetVendorCreditsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetVendorCreditsResponse' from JSON`,
  );
}
