/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPurchaseOrdersRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetPurchaseOrdersErrors = {};

export type GetPurchaseOrdersRawData = {};

export type GetPurchaseOrdersResponse = {
  meta: models.MetaResponse;
  data: Array<models.PurchaseOrderResponseDto>;
  errors: GetPurchaseOrdersErrors;
  rawData: GetPurchaseOrdersRawData;
};

/** @internal */
export type GetPurchaseOrdersRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetPurchaseOrdersRequest$outboundSchema: z.ZodMiniType<
  GetPurchaseOrdersRequest$Outbound,
  GetPurchaseOrdersRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getPurchaseOrdersRequestToJSON(
  getPurchaseOrdersRequest: GetPurchaseOrdersRequest,
): string {
  return JSON.stringify(
    GetPurchaseOrdersRequest$outboundSchema.parse(getPurchaseOrdersRequest),
  );
}

/** @internal */
export const GetPurchaseOrdersErrors$inboundSchema: z.ZodMiniType<
  GetPurchaseOrdersErrors,
  unknown
> = z.object({});

export function getPurchaseOrdersErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrdersErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrdersErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrdersErrors' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrdersRawData$inboundSchema: z.ZodMiniType<
  GetPurchaseOrdersRawData,
  unknown
> = z.object({});

export function getPurchaseOrdersRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrdersRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrdersRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrdersRawData' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrdersResponse$inboundSchema: z.ZodMiniType<
  GetPurchaseOrdersResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.PurchaseOrderResponseDto$inboundSchema),
  errors: z.lazy(() => GetPurchaseOrdersErrors$inboundSchema),
  rawData: z.lazy(() => GetPurchaseOrdersRawData$inboundSchema),
});

export function getPurchaseOrdersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrdersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrdersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrdersResponse' from JSON`,
  );
}
