/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetTaxRatesRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * ISO 8601 timestamp; only records modified after this date are returned
   */
  lastModifiedAt?: string | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * When true, returns only active tax rates; when false, returns only inactive tax rates
   */
  isActive?: boolean | undefined;
};

export type GetTaxRatesPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetTaxRatesMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetTaxRatesPagination | null | undefined;
};

export type GetTaxRatesErrors = {};

export type GetTaxRatesRawData = {};

/**
 * List of tax rates for the authenticated end user's connected target system
 */
export type GetTaxRatesResponse = {
  meta?: GetTaxRatesMeta | null | undefined;
  data: Array<models.TaxRateResponseDto>;
  errors: GetTaxRatesErrors | null;
  rawData: GetTaxRatesRawData | null;
};

/** @internal */
export type GetTaxRatesRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  isActive?: boolean | undefined;
};

/** @internal */
export const GetTaxRatesRequest$outboundSchema: z.ZodMiniType<
  GetTaxRatesRequest$Outbound,
  GetTaxRatesRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  isActive: z.optional(z.boolean()),
});

export function getTaxRatesRequestToJSON(
  getTaxRatesRequest: GetTaxRatesRequest,
): string {
  return JSON.stringify(
    GetTaxRatesRequest$outboundSchema.parse(getTaxRatesRequest),
  );
}

/** @internal */
export const GetTaxRatesPagination$inboundSchema: z.ZodMiniType<
  GetTaxRatesPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getTaxRatesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesPagination' from JSON`,
  );
}

/** @internal */
export const GetTaxRatesMeta$inboundSchema: z.ZodMiniType<
  GetTaxRatesMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetTaxRatesPagination$inboundSchema)),
  ),
});

export function getTaxRatesMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesMeta' from JSON`,
  );
}

/** @internal */
export const GetTaxRatesErrors$inboundSchema: z.ZodMiniType<
  GetTaxRatesErrors,
  unknown
> = z.object({});

export function getTaxRatesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesErrors' from JSON`,
  );
}

/** @internal */
export const GetTaxRatesRawData$inboundSchema: z.ZodMiniType<
  GetTaxRatesRawData,
  unknown
> = z.object({});

export function getTaxRatesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesRawData' from JSON`,
  );
}

/** @internal */
export const GetTaxRatesResponse$inboundSchema: z.ZodMiniType<
  GetTaxRatesResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetTaxRatesMeta$inboundSchema))),
  data: z.array(models.TaxRateResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetTaxRatesErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetTaxRatesRawData$inboundSchema)),
});

export function getTaxRatesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatesResponse' from JSON`,
  );
}
