/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWebhooksRequest = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export type GetWebhooksRequest$Outbound = {
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetWebhooksRequest$outboundSchema: z.ZodMiniType<
  GetWebhooksRequest$Outbound,
  GetWebhooksRequest
> = z.object({
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getWebhooksRequestToJSON(
  getWebhooksRequest: GetWebhooksRequest,
): string {
  return JSON.stringify(
    GetWebhooksRequest$outboundSchema.parse(getWebhooksRequest),
  );
}
