/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCodeRequest = {
  code: string;
};

/** @internal */
export type GetCodeRequest$Outbound = {
  code: string;
};

/** @internal */
export const GetCodeRequest$outboundSchema: z.ZodMiniType<
  GetCodeRequest$Outbound,
  GetCodeRequest
> = z.object({
  code: z.string(),
});

export function getCodeRequestToJSON(getCodeRequest: GetCodeRequest): string {
  return JSON.stringify(GetCodeRequest$outboundSchema.parse(getCodeRequest));
}
