/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetAccountRequest = {
  accountId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetAccountErrors = {};

export type GetAccountRawData = {};

export type GetAccountResponse = {
  meta: models.MetaResponse;
  data: models.AccountResponseDto;
  errors: GetAccountErrors;
  rawData: GetAccountRawData;
};

/** @internal */
export type GetAccountRequest$Outbound = {
  accountId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetAccountRequest$outboundSchema: z.ZodMiniType<
  GetAccountRequest$Outbound,
  GetAccountRequest
> = z.pipe(
  z.object({
    accountId: z.string(),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getAccountRequestToJSON(
  getAccountRequest: GetAccountRequest,
): string {
  return JSON.stringify(
    GetAccountRequest$outboundSchema.parse(getAccountRequest),
  );
}

/** @internal */
export const GetAccountErrors$inboundSchema: z.ZodMiniType<
  GetAccountErrors,
  unknown
> = z.object({});

export function getAccountErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountErrors' from JSON`,
  );
}

/** @internal */
export const GetAccountRawData$inboundSchema: z.ZodMiniType<
  GetAccountRawData,
  unknown
> = z.object({});

export function getAccountRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountRawData' from JSON`,
  );
}

/** @internal */
export const GetAccountResponse$inboundSchema: z.ZodMiniType<
  GetAccountResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.AccountResponseDto$inboundSchema,
  errors: z.lazy(() => GetAccountErrors$inboundSchema),
  rawData: z.lazy(() => GetAccountRawData$inboundSchema),
});

export function getAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountResponse' from JSON`,
  );
}
