/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBankAccountsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetBankAccountsErrors = {};

export type GetBankAccountsRawData = {};

export type GetBankAccountsResponse = {
  meta: models.MetaResponse;
  data: Array<models.BankAccountResponseDto>;
  errors: GetBankAccountsErrors;
  rawData: GetBankAccountsRawData;
};

/** @internal */
export type GetBankAccountsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetBankAccountsRequest$outboundSchema: z.ZodMiniType<
  GetBankAccountsRequest$Outbound,
  GetBankAccountsRequest
> = z.pipe(
  z.object({
    page: z.optional(z.number()),
    limit: z.optional(z.number()),
    lastModifiedAt: z.optional(z.string()),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getBankAccountsRequestToJSON(
  getBankAccountsRequest: GetBankAccountsRequest,
): string {
  return JSON.stringify(
    GetBankAccountsRequest$outboundSchema.parse(getBankAccountsRequest),
  );
}

/** @internal */
export const GetBankAccountsErrors$inboundSchema: z.ZodMiniType<
  GetBankAccountsErrors,
  unknown
> = z.object({});

export function getBankAccountsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountsErrors' from JSON`,
  );
}

/** @internal */
export const GetBankAccountsRawData$inboundSchema: z.ZodMiniType<
  GetBankAccountsRawData,
  unknown
> = z.object({});

export function getBankAccountsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountsRawData' from JSON`,
  );
}

/** @internal */
export const GetBankAccountsResponse$inboundSchema: z.ZodMiniType<
  GetBankAccountsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.BankAccountResponseDto$inboundSchema),
  errors: z.lazy(() => GetBankAccountsErrors$inboundSchema),
  rawData: z.lazy(() => GetBankAccountsRawData$inboundSchema),
});

export function getBankAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBankAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBankAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBankAccountsResponse' from JSON`,
  );
}
