/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetOpenItemsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  fiscalYear?: number | undefined;
  accountNumber?: string | undefined;
  documentNumber?: string | undefined;
  type?: string | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetOpenItemsErrors = {};

export type GetOpenItemsRawData = {};

export type GetOpenItemsResponse = {
  meta: models.MetaResponse;
  data: Array<models.OpenItemResponseDto>;
  errors: GetOpenItemsErrors;
  rawData: GetOpenItemsRawData;
};

/** @internal */
export type GetOpenItemsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  fiscalYear?: number | undefined;
  accountNumber?: string | undefined;
  documentNumber?: string | undefined;
  type?: string | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetOpenItemsRequest$outboundSchema: z.ZodMiniType<
  GetOpenItemsRequest$Outbound,
  GetOpenItemsRequest
> = z.pipe(
  z.object({
    page: z.optional(z.number()),
    limit: z.optional(z.number()),
    lastModifiedAt: z.optional(z.string()),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    fiscalYear: z.optional(z.number()),
    accountNumber: z.optional(z.string()),
    documentNumber: z.optional(z.string()),
    type: z.optional(z.string()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getOpenItemsRequestToJSON(
  getOpenItemsRequest: GetOpenItemsRequest,
): string {
  return JSON.stringify(
    GetOpenItemsRequest$outboundSchema.parse(getOpenItemsRequest),
  );
}

/** @internal */
export const GetOpenItemsErrors$inboundSchema: z.ZodMiniType<
  GetOpenItemsErrors,
  unknown
> = z.object({});

export function getOpenItemsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsErrors' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsRawData$inboundSchema: z.ZodMiniType<
  GetOpenItemsRawData,
  unknown
> = z.object({});

export function getOpenItemsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsRawData' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsResponse$inboundSchema: z.ZodMiniType<
  GetOpenItemsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.OpenItemResponseDto$inboundSchema),
  errors: z.lazy(() => GetOpenItemsErrors$inboundSchema),
  rawData: z.lazy(() => GetOpenItemsRawData$inboundSchema),
});

export function getOpenItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsResponse' from JSON`,
  );
}
