/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetProjectsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetProjectsErrors = {};

export type GetProjectsRawData = {};

export type GetProjectsResponse = {
  meta: models.MetaResponse;
  data: Array<models.ProjectResponseDto>;
  errors: GetProjectsErrors;
  rawData: GetProjectsRawData;
};

/** @internal */
export type GetProjectsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetProjectsRequest$outboundSchema: z.ZodMiniType<
  GetProjectsRequest$Outbound,
  GetProjectsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getProjectsRequestToJSON(
  getProjectsRequest: GetProjectsRequest,
): string {
  return JSON.stringify(
    GetProjectsRequest$outboundSchema.parse(getProjectsRequest),
  );
}

/** @internal */
export const GetProjectsErrors$inboundSchema: z.ZodMiniType<
  GetProjectsErrors,
  unknown
> = z.object({});

export function getProjectsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectsErrors' from JSON`,
  );
}

/** @internal */
export const GetProjectsRawData$inboundSchema: z.ZodMiniType<
  GetProjectsRawData,
  unknown
> = z.object({});

export function getProjectsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectsRawData' from JSON`,
  );
}

/** @internal */
export const GetProjectsResponse$inboundSchema: z.ZodMiniType<
  GetProjectsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.ProjectResponseDto$inboundSchema),
  errors: z.lazy(() => GetProjectsErrors$inboundSchema),
  rawData: z.lazy(() => GetProjectsRawData$inboundSchema),
});

export function getProjectsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetProjectsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProjectsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProjectsResponse' from JSON`,
  );
}
