/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetGoodsReceiptGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetGoodsReceiptRequest = {
  goodsReceiptId: string;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetGoodsReceiptPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetGoodsReceiptMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetGoodsReceiptPagination | null | undefined;
};

export type GetGoodsReceiptErrors = {};

export type GetGoodsReceiptRawData = {};

/**
 * Goods receipt record matching the provided ID
 */
export type GetGoodsReceiptResponse = {
  meta?: GetGoodsReceiptMeta | null | undefined;
  data: models.GoodsReceiptResponseDto;
  errors: GetGoodsReceiptErrors | null;
  rawData: GetGoodsReceiptRawData | null;
};

/** @internal */
export type GetGoodsReceiptRequest$Outbound = {
  goodsReceiptId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetGoodsReceiptRequest$outboundSchema: z.ZodMiniType<
  GetGoodsReceiptRequest$Outbound,
  GetGoodsReceiptRequest
> = z.object({
  goodsReceiptId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getGoodsReceiptRequestToJSON(
  getGoodsReceiptRequest: GetGoodsReceiptRequest,
): string {
  return JSON.stringify(
    GetGoodsReceiptRequest$outboundSchema.parse(getGoodsReceiptRequest),
  );
}

/** @internal */
export const GetGoodsReceiptPagination$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getGoodsReceiptPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptPagination' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptMeta$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetGoodsReceiptPagination$inboundSchema)),
  ),
});

export function getGoodsReceiptMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptMeta' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptErrors$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptErrors,
  unknown
> = z.object({});

export function getGoodsReceiptErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptErrors' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptRawData$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptRawData,
  unknown
> = z.object({});

export function getGoodsReceiptRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptRawData' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptResponse$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetGoodsReceiptMeta$inboundSchema))),
  data: models.GoodsReceiptResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetGoodsReceiptErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetGoodsReceiptRawData$inboundSchema)),
});

export function getGoodsReceiptResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptResponse' from JSON`,
  );
}
