/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const DebitCreditIndicator = {
  Debit: "DEBIT",
  Credit: "CREDIT",
} as const;
export type DebitCreditIndicator = ClosedEnum<typeof DebitCreditIndicator>;

export type GetAccountsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  debitCreditIndicator?: DebitCreditIndicator | undefined;
  fiscalYear?: number | undefined;
  types?: string | undefined;
  fiscalYearStartDate?: string | undefined;
  classFilter?: string | undefined;
  isActive?: boolean | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetAccountsErrors = {};

export type GetAccountsRawData = {};

export type GetAccountsResponse = {
  meta: models.MetaResponse;
  data: Array<models.AccountResponseDto>;
  errors: GetAccountsErrors;
  rawData: GetAccountsRawData;
};

/** @internal */
export const DebitCreditIndicator$outboundSchema: z.ZodMiniEnum<
  typeof DebitCreditIndicator
> = z.enum(DebitCreditIndicator);

/** @internal */
export type GetAccountsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  debitCreditIndicator?: string | undefined;
  fiscalYear?: number | undefined;
  types?: string | undefined;
  fiscalYearStartDate?: string | undefined;
  classFilter?: string | undefined;
  isActive?: boolean | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetAccountsRequest$outboundSchema: z.ZodMiniType<
  GetAccountsRequest$Outbound,
  GetAccountsRequest
> = z.pipe(
  z.object({
    page: z.optional(z.number()),
    limit: z.optional(z.number()),
    lastModifiedAt: z.optional(z.string()),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    debitCreditIndicator: z.optional(DebitCreditIndicator$outboundSchema),
    fiscalYear: z.optional(z.number()),
    types: z.optional(z.string()),
    fiscalYearStartDate: z.optional(z.string()),
    classFilter: z.optional(z.string()),
    isActive: z.optional(z.boolean()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getAccountsRequestToJSON(
  getAccountsRequest: GetAccountsRequest,
): string {
  return JSON.stringify(
    GetAccountsRequest$outboundSchema.parse(getAccountsRequest),
  );
}

/** @internal */
export const GetAccountsErrors$inboundSchema: z.ZodMiniType<
  GetAccountsErrors,
  unknown
> = z.object({});

export function getAccountsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountsErrors' from JSON`,
  );
}

/** @internal */
export const GetAccountsRawData$inboundSchema: z.ZodMiniType<
  GetAccountsRawData,
  unknown
> = z.object({});

export function getAccountsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountsRawData' from JSON`,
  );
}

/** @internal */
export const GetAccountsResponse$inboundSchema: z.ZodMiniType<
  GetAccountsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.AccountResponseDto$inboundSchema),
  errors: z.lazy(() => GetAccountsErrors$inboundSchema),
  rawData: z.lazy(() => GetAccountsRawData$inboundSchema),
});

export function getAccountsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountsResponse' from JSON`,
  );
}
