/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBillsGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export const GetBillsLimit = {
  Five: 5,
  Ten: 10,
  Twenty: 20,
  Fifty: 50,
  OneHundred: 100,
} as const;
export type GetBillsLimit = ClosedEnum<typeof GetBillsLimit>;

/**
 * Filter bills by unified status
 */
export const GetBillsStatus = {
  Draft: "DRAFT",
  Corrective: "CORRECTIVE",
  Submitted: "SUBMITTED",
  DocumentCreated: "DOCUMENT_CREATED",
  Open: "OPEN",
  PartiallyPaid: "PARTIALLY_PAID",
  Paid: "PAID",
  PartiallyOverdue: "PARTIALLY_OVERDUE",
  Overdue: "OVERDUE",
  Voided: "VOIDED",
} as const;
/**
 * Filter bills by unified status
 */
export type GetBillsStatus = ClosedEnum<typeof GetBillsStatus>;

/**
 * Filter bills by payment status
 */
export const GetBillsPaymentStatus = {
  NoOpenItem: "NO_OPEN_ITEM",
  Pending: "PENDING",
  PartlyPaid: "PARTLY_PAID",
  Paid: "PAID",
  Debited: "DEBITED",
  CreditNoteCleared: "CREDIT_NOTE_CLEARED",
  ClearedWithCreditNote: "CLEARED_WITH_CREDIT_NOTE",
  BadDebt: "BAD_DEBT",
  PartialCancellation: "PARTIAL_CANCELLATION",
  Canceled: "CANCELED",
  Unknown: "UNKNOWN",
} as const;
/**
 * Filter bills by payment status
 */
export type GetBillsPaymentStatus = ClosedEnum<typeof GetBillsPaymentStatus>;

/**
 * Field to sort the results by
 */
export const GetBillsOrderField = {
  BillDate: "billDate",
  BillNumber: "billNumber",
  CreatedDate: "createdDate",
  UpdatedDate: "updatedDate",
} as const;
/**
 * Field to sort the results by
 */
export type GetBillsOrderField = ClosedEnum<typeof GetBillsOrderField>;

/**
 * Sort direction for the ordered results
 */
export const GetBillsOrderDir = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
/**
 * Sort direction for the ordered results
 */
export type GetBillsOrderDir = ClosedEnum<typeof GetBillsOrderDir>;

export type GetBillsRequest = {
  page?: number | undefined;
  limit?: GetBillsLimit | undefined;
  /**
   * ISO 8601 timestamp; only records modified after this date are returned
   */
  lastModifiedAt?: string | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * Filter bills by unified status
   */
  status?: GetBillsStatus | undefined;
  /**
   * Filter bills by payment status
   */
  paymentStatus?: GetBillsPaymentStatus | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * Field to sort the results by
   */
  orderField?: GetBillsOrderField | undefined;
  /**
   * Sort direction for the ordered results
   */
  orderDir?: GetBillsOrderDir | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetBillsPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetBillsMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetBillsPagination | null | undefined;
};

export type GetBillsErrors = {};

export type GetBillsRawData = {};

/**
 * List of bills for the authenticated end user's connected target system
 */
export type GetBillsResponse = {
  meta?: GetBillsMeta | null | undefined;
  data: Array<models.BillResponseDto>;
  errors: GetBillsErrors | null;
  rawData: GetBillsRawData | null;
};

/** @internal */
export const GetBillsLimit$outboundSchema: z.ZodMiniEnum<typeof GetBillsLimit> =
  z.enum(GetBillsLimit);

/** @internal */
export const GetBillsStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsStatus
> = z.enum(GetBillsStatus);

/** @internal */
export const GetBillsPaymentStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsPaymentStatus
> = z.enum(GetBillsPaymentStatus);

/** @internal */
export const GetBillsOrderField$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsOrderField
> = z.enum(GetBillsOrderField);

/** @internal */
export const GetBillsOrderDir$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsOrderDir
> = z.enum(GetBillsOrderDir);

/** @internal */
export type GetBillsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: string | undefined;
  paymentStatus?: string | undefined;
  rawData?: boolean | undefined;
  orderField?: string | undefined;
  orderDir?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetBillsRequest$outboundSchema: z.ZodMiniType<
  GetBillsRequest$Outbound,
  GetBillsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(GetBillsLimit$outboundSchema),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  status: z.optional(GetBillsStatus$outboundSchema),
  paymentStatus: z.optional(GetBillsPaymentStatus$outboundSchema),
  rawData: z.optional(z.boolean()),
  orderField: z.optional(GetBillsOrderField$outboundSchema),
  orderDir: z.optional(GetBillsOrderDir$outboundSchema),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getBillsRequestToJSON(
  getBillsRequest: GetBillsRequest,
): string {
  return JSON.stringify(GetBillsRequest$outboundSchema.parse(getBillsRequest));
}

/** @internal */
export const GetBillsPagination$inboundSchema: z.ZodMiniType<
  GetBillsPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getBillsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsPagination' from JSON`,
  );
}

/** @internal */
export const GetBillsMeta$inboundSchema: z.ZodMiniType<GetBillsMeta, unknown> =
  z.object({
    warnings: z.optional(z.nullable(z.array(types.string()))),
    pagination: z.optional(
      z.nullable(z.lazy(() => GetBillsPagination$inboundSchema)),
    ),
  });

export function getBillsMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsMeta' from JSON`,
  );
}

/** @internal */
export const GetBillsErrors$inboundSchema: z.ZodMiniType<
  GetBillsErrors,
  unknown
> = z.object({});

export function getBillsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsErrors' from JSON`,
  );
}

/** @internal */
export const GetBillsRawData$inboundSchema: z.ZodMiniType<
  GetBillsRawData,
  unknown
> = z.object({});

export function getBillsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsRawData' from JSON`,
  );
}

/** @internal */
export const GetBillsResponse$inboundSchema: z.ZodMiniType<
  GetBillsResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetBillsMeta$inboundSchema))),
  data: z.array(models.BillResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetBillsErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetBillsRawData$inboundSchema)),
});

export function getBillsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsResponse' from JSON`,
  );
}
