/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetLineItemRequest = {
  invoiceId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetLineItemErrors = {};

export type GetLineItemRawData = {};

export type GetLineItemResponse = {
  meta: models.MetaResponse;
  data: Array<models.LineItemResponseDto>;
  errors: GetLineItemErrors;
  rawData: GetLineItemRawData;
};

/** @internal */
export type GetLineItemRequest$Outbound = {
  invoiceId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetLineItemRequest$outboundSchema: z.ZodMiniType<
  GetLineItemRequest$Outbound,
  GetLineItemRequest
> = z.object({
  invoiceId: z.string(),
  lineItemId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getLineItemRequestToJSON(
  getLineItemRequest: GetLineItemRequest,
): string {
  return JSON.stringify(
    GetLineItemRequest$outboundSchema.parse(getLineItemRequest),
  );
}

/** @internal */
export const GetLineItemErrors$inboundSchema: z.ZodMiniType<
  GetLineItemErrors,
  unknown
> = z.object({});

export function getLineItemErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemErrors' from JSON`,
  );
}

/** @internal */
export const GetLineItemRawData$inboundSchema: z.ZodMiniType<
  GetLineItemRawData,
  unknown
> = z.object({});

export function getLineItemRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemRawData' from JSON`,
  );
}

/** @internal */
export const GetLineItemResponse$inboundSchema: z.ZodMiniType<
  GetLineItemResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.LineItemResponseDto$inboundSchema),
  errors: z.lazy(() => GetLineItemErrors$inboundSchema),
  rawData: z.lazy(() => GetLineItemRawData$inboundSchema),
});

export function getLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetLineItemResponse' from JSON`,
  );
}
