/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type GetCodeGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetCodeRequest = {
  code: string;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

/**
 * Authorization code saved successfully
 */
export type GetCodeResponse = {};

/** @internal */
export type GetCodeRequest$Outbound = {
  code: string;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetCodeRequest$outboundSchema: z.ZodMiniType<
  GetCodeRequest$Outbound,
  GetCodeRequest
> = z.object({
  code: z.string(),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getCodeRequestToJSON(getCodeRequest: GetCodeRequest): string {
  return JSON.stringify(GetCodeRequest$outboundSchema.parse(getCodeRequest));
}

/** @internal */
export const GetCodeResponse$inboundSchema: z.ZodMiniType<
  GetCodeResponse,
  unknown
> = z.object({});

export function getCodeResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCodeResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCodeResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCodeResponse' from JSON`,
  );
}
