/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCustomerRequest = {
  contactId: string;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
};

export type GetCustomerPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetCustomerMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetCustomerPagination | null | undefined;
};

export type GetCustomerErrors = {};

export type GetCustomerRawData = {};

/**
 * Customer record matching the provided ID
 */
export type GetCustomerResponse = {
  meta?: GetCustomerMeta | null | undefined;
  data: models.ContactResponseDto;
  errors: GetCustomerErrors | null;
  rawData: GetCustomerRawData | null;
};

/** @internal */
export type GetCustomerRequest$Outbound = {
  contactId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetCustomerRequest$outboundSchema: z.ZodMiniType<
  GetCustomerRequest$Outbound,
  GetCustomerRequest
> = z.object({
  contactId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getCustomerRequestToJSON(
  getCustomerRequest: GetCustomerRequest,
): string {
  return JSON.stringify(
    GetCustomerRequest$outboundSchema.parse(getCustomerRequest),
  );
}

/** @internal */
export const GetCustomerPagination$inboundSchema: z.ZodMiniType<
  GetCustomerPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getCustomerPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerPagination' from JSON`,
  );
}

/** @internal */
export const GetCustomerMeta$inboundSchema: z.ZodMiniType<
  GetCustomerMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetCustomerPagination$inboundSchema)),
  ),
});

export function getCustomerMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerMeta' from JSON`,
  );
}

/** @internal */
export const GetCustomerErrors$inboundSchema: z.ZodMiniType<
  GetCustomerErrors,
  unknown
> = z.object({});

export function getCustomerErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerErrors' from JSON`,
  );
}

/** @internal */
export const GetCustomerRawData$inboundSchema: z.ZodMiniType<
  GetCustomerRawData,
  unknown
> = z.object({});

export function getCustomerRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerRawData' from JSON`,
  );
}

/** @internal */
export const GetCustomerResponse$inboundSchema: z.ZodMiniType<
  GetCustomerResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetCustomerMeta$inboundSchema))),
  data: models.ContactResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetCustomerErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetCustomerRawData$inboundSchema)),
});

export function getCustomerResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerResponse' from JSON`,
  );
}
