/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetOpenItemsAsyncGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export const GetOpenItemsAsyncLimit = {
  Five: 5,
  Ten: 10,
  Twenty: 20,
  Fifty: 50,
  OneHundred: 100,
} as const;
export type GetOpenItemsAsyncLimit = ClosedEnum<typeof GetOpenItemsAsyncLimit>;

export type GetOpenItemsAsyncRequest = {
  page?: number | undefined;
  limit?: GetOpenItemsAsyncLimit | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * ISO 8601 start date of the fiscal year used for balance calculation
   */
  fiscalYearStartDate?: string | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetOpenItemsAsyncPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetOpenItemsAsyncMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetOpenItemsAsyncPagination | null | undefined;
};

export type GetOpenItemsAsyncErrors = {};

export type GetOpenItemsAsyncRawData = {};

/**
 * Open items fetch queued successfully. Processed asynchronously and returns 202 with taskId.
 */
export type GetOpenItemsAsyncResponse = {
  meta?: GetOpenItemsAsyncMeta | null | undefined;
  data: models.TaskIdResponseDto;
  errors: GetOpenItemsAsyncErrors | null;
  rawData: GetOpenItemsAsyncRawData | null;
};

/** @internal */
export const GetOpenItemsAsyncLimit$outboundSchema: z.ZodMiniEnum<
  typeof GetOpenItemsAsyncLimit
> = z.enum(GetOpenItemsAsyncLimit);

/** @internal */
export type GetOpenItemsAsyncRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  fiscalYearStartDate?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetOpenItemsAsyncRequest$outboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncRequest$Outbound,
  GetOpenItemsAsyncRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(GetOpenItemsAsyncLimit$outboundSchema),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  fiscalYearStartDate: z.optional(z.string()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getOpenItemsAsyncRequestToJSON(
  getOpenItemsAsyncRequest: GetOpenItemsAsyncRequest,
): string {
  return JSON.stringify(
    GetOpenItemsAsyncRequest$outboundSchema.parse(getOpenItemsAsyncRequest),
  );
}

/** @internal */
export const GetOpenItemsAsyncPagination$inboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getOpenItemsAsyncPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsAsyncPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsAsyncPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsAsyncPagination' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsAsyncMeta$inboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetOpenItemsAsyncPagination$inboundSchema)),
  ),
});

export function getOpenItemsAsyncMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsAsyncMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsAsyncMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsAsyncMeta' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsAsyncErrors$inboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncErrors,
  unknown
> = z.object({});

export function getOpenItemsAsyncErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsAsyncErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsAsyncErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsAsyncErrors' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsAsyncRawData$inboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncRawData,
  unknown
> = z.object({});

export function getOpenItemsAsyncRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsAsyncRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsAsyncRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsAsyncRawData' from JSON`,
  );
}

/** @internal */
export const GetOpenItemsAsyncResponse$inboundSchema: z.ZodMiniType<
  GetOpenItemsAsyncResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => GetOpenItemsAsyncMeta$inboundSchema)),
  ),
  data: models.TaskIdResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetOpenItemsAsyncErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetOpenItemsAsyncRawData$inboundSchema)),
});

export function getOpenItemsAsyncResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOpenItemsAsyncResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOpenItemsAsyncResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOpenItemsAsyncResponse' from JSON`,
  );
}
