/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPaymentsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  lastModifiedAt?: string | undefined;
  invoiceId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetPaymentsErrors = {};

export type GetPaymentsRawData = {};

export type GetPaymentsResponse = {
  meta: models.MetaResponse;
  data: Array<models.PaymentResponseDto>;
  errors: GetPaymentsErrors;
  rawData: GetPaymentsRawData;
};

/** @internal */
export type GetPaymentsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  lastModifiedAt?: string | undefined;
  invoiceId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetPaymentsRequest$outboundSchema: z.ZodMiniType<
  GetPaymentsRequest$Outbound,
  GetPaymentsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  lastModifiedAt: z.optional(z.string()),
  invoiceId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getPaymentsRequestToJSON(
  getPaymentsRequest: GetPaymentsRequest,
): string {
  return JSON.stringify(
    GetPaymentsRequest$outboundSchema.parse(getPaymentsRequest),
  );
}

/** @internal */
export const GetPaymentsErrors$inboundSchema: z.ZodMiniType<
  GetPaymentsErrors,
  unknown
> = z.object({});

export function getPaymentsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentsErrors' from JSON`,
  );
}

/** @internal */
export const GetPaymentsRawData$inboundSchema: z.ZodMiniType<
  GetPaymentsRawData,
  unknown
> = z.object({});

export function getPaymentsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentsRawData' from JSON`,
  );
}

/** @internal */
export const GetPaymentsResponse$inboundSchema: z.ZodMiniType<
  GetPaymentsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.PaymentResponseDto$inboundSchema),
  errors: z.lazy(() => GetPaymentsErrors$inboundSchema),
  rawData: z.lazy(() => GetPaymentsRawData$inboundSchema),
});

export function getPaymentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPaymentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPaymentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPaymentsResponse' from JSON`,
  );
}
