/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetContactsAsyncGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetContactsAsyncRequest = {
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetContactsAsyncPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetContactsAsyncMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetContactsAsyncPagination | null | undefined;
};

export type GetContactsAsyncErrors = {};

export type GetContactsAsyncRawData = {};

/**
 * Contacts fetch queued successfully. Processed asynchronously and returns 202 with taskId.
 */
export type GetContactsAsyncResponse = {
  meta?: GetContactsAsyncMeta | null | undefined;
  data: models.TaskIdResponseDto;
  errors: GetContactsAsyncErrors | null;
  rawData: GetContactsAsyncRawData | null;
};

/** @internal */
export type GetContactsAsyncRequest$Outbound = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetContactsAsyncRequest$outboundSchema: z.ZodMiniType<
  GetContactsAsyncRequest$Outbound,
  GetContactsAsyncRequest
> = z.object({
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getContactsAsyncRequestToJSON(
  getContactsAsyncRequest: GetContactsAsyncRequest,
): string {
  return JSON.stringify(
    GetContactsAsyncRequest$outboundSchema.parse(getContactsAsyncRequest),
  );
}

/** @internal */
export const GetContactsAsyncPagination$inboundSchema: z.ZodMiniType<
  GetContactsAsyncPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getContactsAsyncPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetContactsAsyncPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactsAsyncPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactsAsyncPagination' from JSON`,
  );
}

/** @internal */
export const GetContactsAsyncMeta$inboundSchema: z.ZodMiniType<
  GetContactsAsyncMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetContactsAsyncPagination$inboundSchema)),
  ),
});

export function getContactsAsyncMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetContactsAsyncMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactsAsyncMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactsAsyncMeta' from JSON`,
  );
}

/** @internal */
export const GetContactsAsyncErrors$inboundSchema: z.ZodMiniType<
  GetContactsAsyncErrors,
  unknown
> = z.object({});

export function getContactsAsyncErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetContactsAsyncErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactsAsyncErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactsAsyncErrors' from JSON`,
  );
}

/** @internal */
export const GetContactsAsyncRawData$inboundSchema: z.ZodMiniType<
  GetContactsAsyncRawData,
  unknown
> = z.object({});

export function getContactsAsyncRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetContactsAsyncRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactsAsyncRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactsAsyncRawData' from JSON`,
  );
}

/** @internal */
export const GetContactsAsyncResponse$inboundSchema: z.ZodMiniType<
  GetContactsAsyncResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => GetContactsAsyncMeta$inboundSchema)),
  ),
  data: models.TaskIdResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetContactsAsyncErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetContactsAsyncRawData$inboundSchema)),
});

export function getContactsAsyncResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetContactsAsyncResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactsAsyncResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactsAsyncResponse' from JSON`,
  );
}
