/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetAccountGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetAccountRequest = {
  accountId: string;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetAccountPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetAccountMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetAccountPagination | null | undefined;
};

export type GetAccountErrors = {};

export type GetAccountRawData = {};

/**
 * Account record matching the provided ID
 */
export type GetAccountResponse = {
  meta?: GetAccountMeta | null | undefined;
  data: models.AccountResponseDto;
  errors: GetAccountErrors | null;
  rawData: GetAccountRawData | null;
};

/** @internal */
export type GetAccountRequest$Outbound = {
  accountId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetAccountRequest$outboundSchema: z.ZodMiniType<
  GetAccountRequest$Outbound,
  GetAccountRequest
> = z.object({
  accountId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getAccountRequestToJSON(
  getAccountRequest: GetAccountRequest,
): string {
  return JSON.stringify(
    GetAccountRequest$outboundSchema.parse(getAccountRequest),
  );
}

/** @internal */
export const GetAccountPagination$inboundSchema: z.ZodMiniType<
  GetAccountPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getAccountPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountPagination' from JSON`,
  );
}

/** @internal */
export const GetAccountMeta$inboundSchema: z.ZodMiniType<
  GetAccountMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetAccountPagination$inboundSchema)),
  ),
});

export function getAccountMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountMeta' from JSON`,
  );
}

/** @internal */
export const GetAccountErrors$inboundSchema: z.ZodMiniType<
  GetAccountErrors,
  unknown
> = z.object({});

export function getAccountErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountErrors' from JSON`,
  );
}

/** @internal */
export const GetAccountRawData$inboundSchema: z.ZodMiniType<
  GetAccountRawData,
  unknown
> = z.object({});

export function getAccountRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountRawData' from JSON`,
  );
}

/** @internal */
export const GetAccountResponse$inboundSchema: z.ZodMiniType<
  GetAccountResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetAccountMeta$inboundSchema))),
  data: models.AccountResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetAccountErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetAccountRawData$inboundSchema)),
});

export function getAccountResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetAccountResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAccountResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAccountResponse' from JSON`,
  );
}
