/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCustomersRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  email?: string | undefined;
  name?: string | undefined;
  number?: string | undefined;
};

export type GetCustomersErrors = {};

export type GetCustomersRawData = {};

export type GetCustomersResponse = {
  meta: models.MetaResponse;
  data: Array<models.ContactResponseDto>;
  errors: GetCustomersErrors;
  rawData: GetCustomersRawData;
};

/** @internal */
export type GetCustomersRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  email?: string | undefined;
  name?: string | undefined;
  number?: string | undefined;
};

/** @internal */
export const GetCustomersRequest$outboundSchema: z.ZodMiniType<
  GetCustomersRequest$Outbound,
  GetCustomersRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  email: z.optional(z.string()),
  name: z.optional(z.string()),
  number: z.optional(z.string()),
});

export function getCustomersRequestToJSON(
  getCustomersRequest: GetCustomersRequest,
): string {
  return JSON.stringify(
    GetCustomersRequest$outboundSchema.parse(getCustomersRequest),
  );
}

/** @internal */
export const GetCustomersErrors$inboundSchema: z.ZodMiniType<
  GetCustomersErrors,
  unknown
> = z.object({});

export function getCustomersErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersErrors' from JSON`,
  );
}

/** @internal */
export const GetCustomersRawData$inboundSchema: z.ZodMiniType<
  GetCustomersRawData,
  unknown
> = z.object({});

export function getCustomersRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersRawData' from JSON`,
  );
}

/** @internal */
export const GetCustomersResponse$inboundSchema: z.ZodMiniType<
  GetCustomersResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.ContactResponseDto$inboundSchema),
  errors: z.lazy(() => GetCustomersErrors$inboundSchema),
  rawData: z.lazy(() => GetCustomersRawData$inboundSchema),
});

export function getCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomersResponse' from JSON`,
  );
}
