/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

/**
 * Filter sales orders by status
 */
export const GetSalesOrdersStatus = {
  Draft: "DRAFT",
  InReview: "IN_REVIEW",
  Open: "OPEN",
  Closed: "CLOSED",
  Voided: "VOIDED",
} as const;
/**
 * Filter sales orders by status
 */
export type GetSalesOrdersStatus = ClosedEnum<typeof GetSalesOrdersStatus>;

export type GetSalesOrdersRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  /**
   * ISO 8601 timestamp; only records modified after this date are returned
   */
  lastModifiedAt?: string | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * Filter sales orders by status
   */
  status?: GetSalesOrdersStatus | undefined;
};

export type GetSalesOrdersPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetSalesOrdersMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetSalesOrdersPagination | null | undefined;
};

export type GetSalesOrdersErrors = {};

export type GetSalesOrdersRawData = {};

/**
 * List of sales orders for the authenticated end user's connected target system
 */
export type GetSalesOrdersResponse = {
  meta?: GetSalesOrdersMeta | null | undefined;
  data: Array<models.SalesOrderResponseDto>;
  errors: GetSalesOrdersErrors | null;
  rawData: GetSalesOrdersRawData | null;
};

/** @internal */
export const GetSalesOrdersStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetSalesOrdersStatus
> = z.enum(GetSalesOrdersStatus);

/** @internal */
export type GetSalesOrdersRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  status?: string | undefined;
};

/** @internal */
export const GetSalesOrdersRequest$outboundSchema: z.ZodMiniType<
  GetSalesOrdersRequest$Outbound,
  GetSalesOrdersRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  status: z.optional(GetSalesOrdersStatus$outboundSchema),
});

export function getSalesOrdersRequestToJSON(
  getSalesOrdersRequest: GetSalesOrdersRequest,
): string {
  return JSON.stringify(
    GetSalesOrdersRequest$outboundSchema.parse(getSalesOrdersRequest),
  );
}

/** @internal */
export const GetSalesOrdersPagination$inboundSchema: z.ZodMiniType<
  GetSalesOrdersPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getSalesOrdersPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrdersPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrdersPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrdersPagination' from JSON`,
  );
}

/** @internal */
export const GetSalesOrdersMeta$inboundSchema: z.ZodMiniType<
  GetSalesOrdersMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetSalesOrdersPagination$inboundSchema)),
  ),
});

export function getSalesOrdersMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrdersMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrdersMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrdersMeta' from JSON`,
  );
}

/** @internal */
export const GetSalesOrdersErrors$inboundSchema: z.ZodMiniType<
  GetSalesOrdersErrors,
  unknown
> = z.object({});

export function getSalesOrdersErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrdersErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrdersErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrdersErrors' from JSON`,
  );
}

/** @internal */
export const GetSalesOrdersRawData$inboundSchema: z.ZodMiniType<
  GetSalesOrdersRawData,
  unknown
> = z.object({});

export function getSalesOrdersRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrdersRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrdersRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrdersRawData' from JSON`,
  );
}

/** @internal */
export const GetSalesOrdersResponse$inboundSchema: z.ZodMiniType<
  GetSalesOrdersResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetSalesOrdersMeta$inboundSchema))),
  data: z.array(models.SalesOrderResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetSalesOrdersErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetSalesOrdersRawData$inboundSchema)),
});

export function getSalesOrdersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSalesOrdersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSalesOrdersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSalesOrdersResponse' from JSON`,
  );
}
