/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetGoodsReceiptsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetGoodsReceiptsErrors = {};

export type GetGoodsReceiptsRawData = {};

export type GetGoodsReceiptsResponse = {
  meta: models.MetaResponse;
  data: Array<models.GoodsReceiptResponseDto>;
  errors: GetGoodsReceiptsErrors;
  rawData: GetGoodsReceiptsRawData;
};

/** @internal */
export type GetGoodsReceiptsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetGoodsReceiptsRequest$outboundSchema: z.ZodMiniType<
  GetGoodsReceiptsRequest$Outbound,
  GetGoodsReceiptsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getGoodsReceiptsRequestToJSON(
  getGoodsReceiptsRequest: GetGoodsReceiptsRequest,
): string {
  return JSON.stringify(
    GetGoodsReceiptsRequest$outboundSchema.parse(getGoodsReceiptsRequest),
  );
}

/** @internal */
export const GetGoodsReceiptsErrors$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptsErrors,
  unknown
> = z.object({});

export function getGoodsReceiptsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptsErrors' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptsRawData$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptsRawData,
  unknown
> = z.object({});

export function getGoodsReceiptsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptsRawData' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptsResponse$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.GoodsReceiptResponseDto$inboundSchema),
  errors: z.lazy(() => GetGoodsReceiptsErrors$inboundSchema),
  rawData: z.lazy(() => GetGoodsReceiptsRawData$inboundSchema),
});

export function getGoodsReceiptsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptsResponse' from JSON`,
  );
}
