/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetTaxRateGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetTaxRateRequest = {
  taxRateId: string;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetTaxRatePagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetTaxRateMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetTaxRatePagination | null | undefined;
};

export type GetTaxRateErrors = {};

export type GetTaxRateRawData = {};

/**
 * Tax rate record matching the provided ID
 */
export type GetTaxRateResponse = {
  meta?: GetTaxRateMeta | null | undefined;
  data: models.TaxRateResponseDto;
  errors: GetTaxRateErrors | null;
  rawData: GetTaxRateRawData | null;
};

/** @internal */
export type GetTaxRateRequest$Outbound = {
  taxRateId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetTaxRateRequest$outboundSchema: z.ZodMiniType<
  GetTaxRateRequest$Outbound,
  GetTaxRateRequest
> = z.object({
  taxRateId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getTaxRateRequestToJSON(
  getTaxRateRequest: GetTaxRateRequest,
): string {
  return JSON.stringify(
    GetTaxRateRequest$outboundSchema.parse(getTaxRateRequest),
  );
}

/** @internal */
export const GetTaxRatePagination$inboundSchema: z.ZodMiniType<
  GetTaxRatePagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getTaxRatePaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRatePagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRatePagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRatePagination' from JSON`,
  );
}

/** @internal */
export const GetTaxRateMeta$inboundSchema: z.ZodMiniType<
  GetTaxRateMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetTaxRatePagination$inboundSchema)),
  ),
});

export function getTaxRateMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRateMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRateMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRateMeta' from JSON`,
  );
}

/** @internal */
export const GetTaxRateErrors$inboundSchema: z.ZodMiniType<
  GetTaxRateErrors,
  unknown
> = z.object({});

export function getTaxRateErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRateErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRateErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRateErrors' from JSON`,
  );
}

/** @internal */
export const GetTaxRateRawData$inboundSchema: z.ZodMiniType<
  GetTaxRateRawData,
  unknown
> = z.object({});

export function getTaxRateRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRateRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRateRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRateRawData' from JSON`,
  );
}

/** @internal */
export const GetTaxRateResponse$inboundSchema: z.ZodMiniType<
  GetTaxRateResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetTaxRateMeta$inboundSchema))),
  data: models.TaxRateResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetTaxRateErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetTaxRateRawData$inboundSchema)),
});

export function getTaxRateResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetTaxRateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetTaxRateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetTaxRateResponse' from JSON`,
  );
}
