/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetDimensionsByDimensionRequest = {
  dimension: string;
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetDimensionsByDimensionErrors = {};

export type GetDimensionsByDimensionRawData = {};

export type GetDimensionsByDimensionResponse = {
  meta: models.MetaResponse;
  data: Array<models.DimensionMetaResponseDto>;
  errors: GetDimensionsByDimensionErrors;
  rawData: GetDimensionsByDimensionRawData;
};

/** @internal */
export type GetDimensionsByDimensionRequest$Outbound = {
  dimension: string;
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetDimensionsByDimensionRequest$outboundSchema: z.ZodMiniType<
  GetDimensionsByDimensionRequest$Outbound,
  GetDimensionsByDimensionRequest
> = z.object({
  dimension: z.string(),
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getDimensionsByDimensionRequestToJSON(
  getDimensionsByDimensionRequest: GetDimensionsByDimensionRequest,
): string {
  return JSON.stringify(
    GetDimensionsByDimensionRequest$outboundSchema.parse(
      getDimensionsByDimensionRequest,
    ),
  );
}

/** @internal */
export const GetDimensionsByDimensionErrors$inboundSchema: z.ZodMiniType<
  GetDimensionsByDimensionErrors,
  unknown
> = z.object({});

export function getDimensionsByDimensionErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetDimensionsByDimensionErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDimensionsByDimensionErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDimensionsByDimensionErrors' from JSON`,
  );
}

/** @internal */
export const GetDimensionsByDimensionRawData$inboundSchema: z.ZodMiniType<
  GetDimensionsByDimensionRawData,
  unknown
> = z.object({});

export function getDimensionsByDimensionRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetDimensionsByDimensionRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDimensionsByDimensionRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDimensionsByDimensionRawData' from JSON`,
  );
}

/** @internal */
export const GetDimensionsByDimensionResponse$inboundSchema: z.ZodMiniType<
  GetDimensionsByDimensionResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.DimensionMetaResponseDto$inboundSchema),
  errors: z.lazy(() => GetDimensionsByDimensionErrors$inboundSchema),
  rawData: z.lazy(() => GetDimensionsByDimensionRawData$inboundSchema),
});

export function getDimensionsByDimensionResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetDimensionsByDimensionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetDimensionsByDimensionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetDimensionsByDimensionResponse' from JSON`,
  );
}
