/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetContactV2Request = {
  contactId: string;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
};

export type GetContactV2Pagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetContactV2Meta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetContactV2Pagination | null | undefined;
};

export type GetContactV2Errors = {};

export type GetContactV2RawData = {};

/**
 * Contact record matching the provided ID
 */
export type GetContactV2Response = {
  meta?: GetContactV2Meta | null | undefined;
  data: models.ContactResponseDtoV2;
  errors: GetContactV2Errors | null;
  rawData: GetContactV2RawData | null;
};

/** @internal */
export type GetContactV2Request$Outbound = {
  contactId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetContactV2Request$outboundSchema: z.ZodMiniType<
  GetContactV2Request$Outbound,
  GetContactV2Request
> = z.object({
  contactId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getContactV2RequestToJSON(
  getContactV2Request: GetContactV2Request,
): string {
  return JSON.stringify(
    GetContactV2Request$outboundSchema.parse(getContactV2Request),
  );
}

/** @internal */
export const GetContactV2Pagination$inboundSchema: z.ZodMiniType<
  GetContactV2Pagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getContactV2PaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetContactV2Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactV2Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactV2Pagination' from JSON`,
  );
}

/** @internal */
export const GetContactV2Meta$inboundSchema: z.ZodMiniType<
  GetContactV2Meta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetContactV2Pagination$inboundSchema)),
  ),
});

export function getContactV2MetaFromJSON(
  jsonString: string,
): SafeParseResult<GetContactV2Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactV2Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactV2Meta' from JSON`,
  );
}

/** @internal */
export const GetContactV2Errors$inboundSchema: z.ZodMiniType<
  GetContactV2Errors,
  unknown
> = z.object({});

export function getContactV2ErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetContactV2Errors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactV2Errors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactV2Errors' from JSON`,
  );
}

/** @internal */
export const GetContactV2RawData$inboundSchema: z.ZodMiniType<
  GetContactV2RawData,
  unknown
> = z.object({});

export function getContactV2RawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetContactV2RawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactV2RawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactV2RawData' from JSON`,
  );
}

/** @internal */
export const GetContactV2Response$inboundSchema: z.ZodMiniType<
  GetContactV2Response,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetContactV2Meta$inboundSchema))),
  data: models.ContactResponseDtoV2$inboundSchema,
  errors: types.nullable(z.lazy(() => GetContactV2Errors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetContactV2RawData$inboundSchema)),
});

export function getContactV2ResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetContactV2Response, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetContactV2Response$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetContactV2Response' from JSON`,
  );
}
