/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetOfferLineItemRequest = {
  offerId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetOfferLineItemPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetOfferLineItemMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetOfferLineItemPagination | null | undefined;
};

export type GetOfferLineItemErrors = {};

export type GetOfferLineItemRawData = {};

export type GetOfferLineItemResponse = {
  meta?: GetOfferLineItemMeta | null | undefined;
  data: models.OfferLineItemResponseDto;
  errors: GetOfferLineItemErrors | null;
  rawData: GetOfferLineItemRawData | null;
};

/** @internal */
export type GetOfferLineItemRequest$Outbound = {
  offerId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetOfferLineItemRequest$outboundSchema: z.ZodMiniType<
  GetOfferLineItemRequest$Outbound,
  GetOfferLineItemRequest
> = z.object({
  offerId: z.string(),
  lineItemId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getOfferLineItemRequestToJSON(
  getOfferLineItemRequest: GetOfferLineItemRequest,
): string {
  return JSON.stringify(
    GetOfferLineItemRequest$outboundSchema.parse(getOfferLineItemRequest),
  );
}

/** @internal */
export const GetOfferLineItemPagination$inboundSchema: z.ZodMiniType<
  GetOfferLineItemPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getOfferLineItemPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetOfferLineItemPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOfferLineItemPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOfferLineItemPagination' from JSON`,
  );
}

/** @internal */
export const GetOfferLineItemMeta$inboundSchema: z.ZodMiniType<
  GetOfferLineItemMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetOfferLineItemPagination$inboundSchema)),
  ),
});

export function getOfferLineItemMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetOfferLineItemMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOfferLineItemMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOfferLineItemMeta' from JSON`,
  );
}

/** @internal */
export const GetOfferLineItemErrors$inboundSchema: z.ZodMiniType<
  GetOfferLineItemErrors,
  unknown
> = z.object({});

export function getOfferLineItemErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetOfferLineItemErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOfferLineItemErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOfferLineItemErrors' from JSON`,
  );
}

/** @internal */
export const GetOfferLineItemRawData$inboundSchema: z.ZodMiniType<
  GetOfferLineItemRawData,
  unknown
> = z.object({});

export function getOfferLineItemRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetOfferLineItemRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOfferLineItemRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOfferLineItemRawData' from JSON`,
  );
}

/** @internal */
export const GetOfferLineItemResponse$inboundSchema: z.ZodMiniType<
  GetOfferLineItemResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => GetOfferLineItemMeta$inboundSchema)),
  ),
  data: models.OfferLineItemResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => GetOfferLineItemErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetOfferLineItemRawData$inboundSchema)),
});

export function getOfferLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetOfferLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetOfferLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetOfferLineItemResponse' from JSON`,
  );
}
