/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBookingProposalRequest = {
  bookingProposalId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetBookingProposalErrors = {};

export type GetBookingProposalRawData = {};

export type GetBookingProposalResponse = {
  meta: models.MetaResponse;
  data: Array<models.BookingProposalResponseDto>;
  errors: GetBookingProposalErrors;
  rawData: GetBookingProposalRawData;
};

/** @internal */
export type GetBookingProposalRequest$Outbound = {
  bookingProposalId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetBookingProposalRequest$outboundSchema: z.ZodMiniType<
  GetBookingProposalRequest$Outbound,
  GetBookingProposalRequest
> = z.object({
  bookingProposalId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getBookingProposalRequestToJSON(
  getBookingProposalRequest: GetBookingProposalRequest,
): string {
  return JSON.stringify(
    GetBookingProposalRequest$outboundSchema.parse(getBookingProposalRequest),
  );
}

/** @internal */
export const GetBookingProposalErrors$inboundSchema: z.ZodMiniType<
  GetBookingProposalErrors,
  unknown
> = z.object({});

export function getBookingProposalErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingProposalErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingProposalErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingProposalErrors' from JSON`,
  );
}

/** @internal */
export const GetBookingProposalRawData$inboundSchema: z.ZodMiniType<
  GetBookingProposalRawData,
  unknown
> = z.object({});

export function getBookingProposalRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingProposalRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingProposalRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingProposalRawData' from JSON`,
  );
}

/** @internal */
export const GetBookingProposalResponse$inboundSchema: z.ZodMiniType<
  GetBookingProposalResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.BookingProposalResponseDto$inboundSchema),
  errors: z.lazy(() => GetBookingProposalErrors$inboundSchema),
  rawData: z.lazy(() => GetBookingProposalRawData$inboundSchema),
});

export function getBookingProposalResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBookingProposalResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBookingProposalResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBookingProposalResponse' from JSON`,
  );
}
