/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCompaniesGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type GetCompaniesRequest = {
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetCompaniesPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetCompaniesMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetCompaniesPagination | null | undefined;
};

export type GetCompaniesErrors = {};

export type GetCompaniesRawData = {};

/**
 * List of companies for the authenticated end user's connected target system
 */
export type GetCompaniesResponse = {
  meta?: GetCompaniesMeta | null | undefined;
  data: Array<models.CompanyResponseDto>;
  errors: GetCompaniesErrors | null;
  rawData: GetCompaniesRawData | null;
};

/** @internal */
export type GetCompaniesRequest$Outbound = {
  environmentName?: string | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetCompaniesRequest$outboundSchema: z.ZodMiniType<
  GetCompaniesRequest$Outbound,
  GetCompaniesRequest
> = z.object({
  environmentName: z.optional(z.string()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getCompaniesRequestToJSON(
  getCompaniesRequest: GetCompaniesRequest,
): string {
  return JSON.stringify(
    GetCompaniesRequest$outboundSchema.parse(getCompaniesRequest),
  );
}

/** @internal */
export const GetCompaniesPagination$inboundSchema: z.ZodMiniType<
  GetCompaniesPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getCompaniesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetCompaniesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompaniesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompaniesPagination' from JSON`,
  );
}

/** @internal */
export const GetCompaniesMeta$inboundSchema: z.ZodMiniType<
  GetCompaniesMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetCompaniesPagination$inboundSchema)),
  ),
});

export function getCompaniesMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetCompaniesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompaniesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompaniesMeta' from JSON`,
  );
}

/** @internal */
export const GetCompaniesErrors$inboundSchema: z.ZodMiniType<
  GetCompaniesErrors,
  unknown
> = z.object({});

export function getCompaniesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetCompaniesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompaniesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompaniesErrors' from JSON`,
  );
}

/** @internal */
export const GetCompaniesRawData$inboundSchema: z.ZodMiniType<
  GetCompaniesRawData,
  unknown
> = z.object({});

export function getCompaniesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCompaniesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompaniesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompaniesRawData' from JSON`,
  );
}

/** @internal */
export const GetCompaniesResponse$inboundSchema: z.ZodMiniType<
  GetCompaniesResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetCompaniesMeta$inboundSchema))),
  data: z.array(models.CompanyResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetCompaniesErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetCompaniesRawData$inboundSchema)),
});

export function getCompaniesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCompaniesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompaniesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompaniesResponse' from JSON`,
  );
}
