/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export const GetBillsStatus = {
  Draft: "DRAFT",
  Corrective: "CORRECTIVE",
  Submitted: "SUBMITTED",
  DocumentCreated: "DOCUMENT_CREATED",
  Open: "OPEN",
  PartiallyPaid: "PARTIALLY_PAID",
  Paid: "PAID",
  PartiallyOverdue: "PARTIALLY_OVERDUE",
  Overdue: "OVERDUE",
  Voided: "VOIDED",
} as const;
export type GetBillsStatus = ClosedEnum<typeof GetBillsStatus>;

export const GetBillsPaymentStatus = {
  NoOpenItem: "NO_OPEN_ITEM",
  Pending: "PENDING",
  PartlyPaid: "PARTLY_PAID",
  Paid: "PAID",
  Debited: "DEBITED",
  CreditNoteCleared: "CREDIT_NOTE_CLEARED",
  ClearedWithCreditNote: "CLEARED_WITH_CREDIT_NOTE",
  BadDebt: "BAD_DEBT",
  PartialCancellation: "PARTIAL_CANCELLATION",
  Canceled: "CANCELED",
  Unknown: "UNKNOWN",
} as const;
export type GetBillsPaymentStatus = ClosedEnum<typeof GetBillsPaymentStatus>;

export const GetBillsOrderField = {
  BillDate: "billDate",
  BillNumber: "billNumber",
  CreatedDate: "createdDate",
  UpdatedDate: "updatedDate",
} as const;
export type GetBillsOrderField = ClosedEnum<typeof GetBillsOrderField>;

export const GetBillsOrderDir = {
  Asc: "ASC",
  Desc: "DESC",
} as const;
export type GetBillsOrderDir = ClosedEnum<typeof GetBillsOrderDir>;

export type GetBillsRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: GetBillsStatus | undefined;
  paymentStatus?: GetBillsPaymentStatus | undefined;
  rawData?: boolean | undefined;
  orderField?: GetBillsOrderField | undefined;
  orderDir?: GetBillsOrderDir | undefined;
};

export type GetBillsErrors = {};

export type GetBillsRawData = {};

export type GetBillsResponse = {
  meta: models.MetaResponse;
  data: Array<models.BillResponseDto>;
  errors: GetBillsErrors;
  rawData: GetBillsRawData;
};

/** @internal */
export const GetBillsStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsStatus
> = z.enum(GetBillsStatus);

/** @internal */
export const GetBillsPaymentStatus$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsPaymentStatus
> = z.enum(GetBillsPaymentStatus);

/** @internal */
export const GetBillsOrderField$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsOrderField
> = z.enum(GetBillsOrderField);

/** @internal */
export const GetBillsOrderDir$outboundSchema: z.ZodMiniEnum<
  typeof GetBillsOrderDir
> = z.enum(GetBillsOrderDir);

/** @internal */
export type GetBillsRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  status?: string | undefined;
  paymentStatus?: string | undefined;
  rawData?: boolean | undefined;
  orderField?: string | undefined;
  orderDir?: string | undefined;
};

/** @internal */
export const GetBillsRequest$outboundSchema: z.ZodMiniType<
  GetBillsRequest$Outbound,
  GetBillsRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  status: z.optional(GetBillsStatus$outboundSchema),
  paymentStatus: z.optional(GetBillsPaymentStatus$outboundSchema),
  rawData: z.optional(z.boolean()),
  orderField: z.optional(GetBillsOrderField$outboundSchema),
  orderDir: z.optional(GetBillsOrderDir$outboundSchema),
});

export function getBillsRequestToJSON(
  getBillsRequest: GetBillsRequest,
): string {
  return JSON.stringify(GetBillsRequest$outboundSchema.parse(getBillsRequest));
}

/** @internal */
export const GetBillsErrors$inboundSchema: z.ZodMiniType<
  GetBillsErrors,
  unknown
> = z.object({});

export function getBillsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsErrors' from JSON`,
  );
}

/** @internal */
export const GetBillsRawData$inboundSchema: z.ZodMiniType<
  GetBillsRawData,
  unknown
> = z.object({});

export function getBillsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsRawData' from JSON`,
  );
}

/** @internal */
export const GetBillsResponse$inboundSchema: z.ZodMiniType<
  GetBillsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.BillResponseDto$inboundSchema),
  errors: z.lazy(() => GetBillsErrors$inboundSchema),
  rawData: z.lazy(() => GetBillsRawData$inboundSchema),
});

export function getBillsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBillsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillsResponse' from JSON`,
  );
}
