/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetGoodsReceiptRequest = {
  goodsReceiptId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetGoodsReceiptErrors = {};

export type GetGoodsReceiptRawData = {};

export type GetGoodsReceiptResponse = {
  meta: models.MetaResponse;
  data: models.GoodsReceiptResponseDto;
  errors: GetGoodsReceiptErrors;
  rawData: GetGoodsReceiptRawData;
};

/** @internal */
export type GetGoodsReceiptRequest$Outbound = {
  goodsReceiptId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetGoodsReceiptRequest$outboundSchema: z.ZodMiniType<
  GetGoodsReceiptRequest$Outbound,
  GetGoodsReceiptRequest
> = z.pipe(
  z.object({
    goodsReceiptId: z.string(),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getGoodsReceiptRequestToJSON(
  getGoodsReceiptRequest: GetGoodsReceiptRequest,
): string {
  return JSON.stringify(
    GetGoodsReceiptRequest$outboundSchema.parse(getGoodsReceiptRequest),
  );
}

/** @internal */
export const GetGoodsReceiptErrors$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptErrors,
  unknown
> = z.object({});

export function getGoodsReceiptErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptErrors' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptRawData$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptRawData,
  unknown
> = z.object({});

export function getGoodsReceiptRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptRawData' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptResponse$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.GoodsReceiptResponseDto$inboundSchema,
  errors: z.lazy(() => GetGoodsReceiptErrors$inboundSchema),
  rawData: z.lazy(() => GetGoodsReceiptRawData$inboundSchema),
});

export function getGoodsReceiptResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptResponse' from JSON`,
  );
}
