/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetCreditNotesGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export const GetCreditNotesLimit = {
  Five: 5,
  Ten: 10,
  Twenty: 20,
  Fifty: 50,
  OneHundred: 100,
} as const;
export type GetCreditNotesLimit = ClosedEnum<typeof GetCreditNotesLimit>;

export type GetCreditNotesRequest = {
  page?: number | undefined;
  limit?: GetCreditNotesLimit | undefined;
  /**
   * ISO 8601 timestamp; only records modified after this date are returned
   */
  lastModifiedAt?: string | undefined;
  /**
   * Environment name (required for multi-environment systems such as Business Central)
   */
  environmentName?: string | undefined;
  /**
   * ID of the company (required for multi-company target systems)
   */
  companyId?: string | undefined;
  /**
   * When true, returns the unprocessed response from the upstream target system
   */
  rawData?: boolean | undefined;
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
};

export type GetCreditNotesPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetCreditNotesMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetCreditNotesPagination | null | undefined;
};

export type GetCreditNotesErrors = {};

export type GetCreditNotesRawData = {};

/**
 * List of credit notes for the authenticated end user's connected target system
 */
export type GetCreditNotesResponse = {
  meta?: GetCreditNotesMeta | null | undefined;
  data: Array<models.CreditNoteResponseDto>;
  errors: GetCreditNotesErrors | null;
  rawData: GetCreditNotesRawData | null;
};

/** @internal */
export const GetCreditNotesLimit$outboundSchema: z.ZodMiniEnum<
  typeof GetCreditNotesLimit
> = z.enum(GetCreditNotesLimit);

/** @internal */
export type GetCreditNotesRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

/** @internal */
export const GetCreditNotesRequest$outboundSchema: z.ZodMiniType<
  GetCreditNotesRequest$Outbound,
  GetCreditNotesRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(GetCreditNotesLimit$outboundSchema),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
});

export function getCreditNotesRequestToJSON(
  getCreditNotesRequest: GetCreditNotesRequest,
): string {
  return JSON.stringify(
    GetCreditNotesRequest$outboundSchema.parse(getCreditNotesRequest),
  );
}

/** @internal */
export const GetCreditNotesPagination$inboundSchema: z.ZodMiniType<
  GetCreditNotesPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getCreditNotesPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesPagination' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesMeta$inboundSchema: z.ZodMiniType<
  GetCreditNotesMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetCreditNotesPagination$inboundSchema)),
  ),
});

export function getCreditNotesMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesMeta' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesErrors$inboundSchema: z.ZodMiniType<
  GetCreditNotesErrors,
  unknown
> = z.object({});

export function getCreditNotesErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesErrors' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesRawData$inboundSchema: z.ZodMiniType<
  GetCreditNotesRawData,
  unknown
> = z.object({});

export function getCreditNotesRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesRawData' from JSON`,
  );
}

/** @internal */
export const GetCreditNotesResponse$inboundSchema: z.ZodMiniType<
  GetCreditNotesResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => GetCreditNotesMeta$inboundSchema))),
  data: z.array(models.CreditNoteResponseDto$inboundSchema),
  errors: types.nullable(z.lazy(() => GetCreditNotesErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => GetCreditNotesRawData$inboundSchema)),
});

export function getCreditNotesResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetCreditNotesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCreditNotesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCreditNotesResponse' from JSON`,
  );
}
