/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetSuppliersRequest = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  email?: string | undefined;
  name?: string | undefined;
  number?: string | undefined;
};

export type GetSuppliersErrors = {};

export type GetSuppliersRawData = {};

export type GetSuppliersResponse = {
  meta: models.MetaResponse;
  data: Array<models.ContactResponseDto>;
  errors: GetSuppliersErrors;
  rawData: GetSuppliersRawData;
};

/** @internal */
export type GetSuppliersRequest$Outbound = {
  page?: number | undefined;
  limit?: number | undefined;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  email?: string | undefined;
  name?: string | undefined;
  number?: string | undefined;
};

/** @internal */
export const GetSuppliersRequest$outboundSchema: z.ZodMiniType<
  GetSuppliersRequest$Outbound,
  GetSuppliersRequest
> = z.object({
  page: z.optional(z.number()),
  limit: z.optional(z.number()),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
  email: z.optional(z.string()),
  name: z.optional(z.string()),
  number: z.optional(z.string()),
});

export function getSuppliersRequestToJSON(
  getSuppliersRequest: GetSuppliersRequest,
): string {
  return JSON.stringify(
    GetSuppliersRequest$outboundSchema.parse(getSuppliersRequest),
  );
}

/** @internal */
export const GetSuppliersErrors$inboundSchema: z.ZodMiniType<
  GetSuppliersErrors,
  unknown
> = z.object({});

export function getSuppliersErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetSuppliersErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSuppliersErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSuppliersErrors' from JSON`,
  );
}

/** @internal */
export const GetSuppliersRawData$inboundSchema: z.ZodMiniType<
  GetSuppliersRawData,
  unknown
> = z.object({});

export function getSuppliersRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetSuppliersRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSuppliersRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSuppliersRawData' from JSON`,
  );
}

/** @internal */
export const GetSuppliersResponse$inboundSchema: z.ZodMiniType<
  GetSuppliersResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.ContactResponseDto$inboundSchema),
  errors: z.lazy(() => GetSuppliersErrors$inboundSchema),
  rawData: z.lazy(() => GetSuppliersRawData$inboundSchema),
});

export function getSuppliersResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSuppliersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSuppliersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSuppliersResponse' from JSON`,
  );
}
