/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetGoodsReceiptLineItemsRequest = {
  goodsReceiptId: string;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetGoodsReceiptLineItemsErrors = {};

export type GetGoodsReceiptLineItemsRawData = {};

export type GetGoodsReceiptLineItemsResponse = {
  meta: models.MetaResponse;
  data: Array<models.GoodsReceiptLineItemResponse>;
  errors: GetGoodsReceiptLineItemsErrors;
  rawData: GetGoodsReceiptLineItemsRawData;
};

/** @internal */
export type GetGoodsReceiptLineItemsRequest$Outbound = {
  goodsReceiptId: string;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetGoodsReceiptLineItemsRequest$outboundSchema: z.ZodMiniType<
  GetGoodsReceiptLineItemsRequest$Outbound,
  GetGoodsReceiptLineItemsRequest
> = z.object({
  goodsReceiptId: z.string(),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getGoodsReceiptLineItemsRequestToJSON(
  getGoodsReceiptLineItemsRequest: GetGoodsReceiptLineItemsRequest,
): string {
  return JSON.stringify(
    GetGoodsReceiptLineItemsRequest$outboundSchema.parse(
      getGoodsReceiptLineItemsRequest,
    ),
  );
}

/** @internal */
export const GetGoodsReceiptLineItemsErrors$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptLineItemsErrors,
  unknown
> = z.object({});

export function getGoodsReceiptLineItemsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptLineItemsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptLineItemsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptLineItemsErrors' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptLineItemsRawData$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptLineItemsRawData,
  unknown
> = z.object({});

export function getGoodsReceiptLineItemsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptLineItemsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptLineItemsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptLineItemsRawData' from JSON`,
  );
}

/** @internal */
export const GetGoodsReceiptLineItemsResponse$inboundSchema: z.ZodMiniType<
  GetGoodsReceiptLineItemsResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.GoodsReceiptLineItemResponse$inboundSchema),
  errors: z.lazy(() => GetGoodsReceiptLineItemsErrors$inboundSchema),
  rawData: z.lazy(() => GetGoodsReceiptLineItemsRawData$inboundSchema),
});

export function getGoodsReceiptLineItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGoodsReceiptLineItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGoodsReceiptLineItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGoodsReceiptLineItemsResponse' from JSON`,
  );
}
