/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetBillRequest = {
  billId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
};

export type GetBillErrors = {};

export type GetBillRawData = {};

export type GetBillResponse = {
  meta: models.MetaResponse;
  data: Array<models.BillResponseDto>;
  errors: GetBillErrors;
  rawData: GetBillRawData;
};

/** @internal */
export type GetBillRequest$Outbound = {
  billId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
};

/** @internal */
export const GetBillRequest$outboundSchema: z.ZodMiniType<
  GetBillRequest$Outbound,
  GetBillRequest
> = z.pipe(
  z.object({
    billId: z.string(),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    rawData: z.optional(z.boolean()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function getBillRequestToJSON(getBillRequest: GetBillRequest): string {
  return JSON.stringify(GetBillRequest$outboundSchema.parse(getBillRequest));
}

/** @internal */
export const GetBillErrors$inboundSchema: z.ZodMiniType<
  GetBillErrors,
  unknown
> = z.object({});

export function getBillErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetBillErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillErrors' from JSON`,
  );
}

/** @internal */
export const GetBillRawData$inboundSchema: z.ZodMiniType<
  GetBillRawData,
  unknown
> = z.object({});

export function getBillRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetBillRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillRawData' from JSON`,
  );
}

/** @internal */
export const GetBillResponse$inboundSchema: z.ZodMiniType<
  GetBillResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: z.array(models.BillResponseDto$inboundSchema),
  errors: z.lazy(() => GetBillErrors$inboundSchema),
  rawData: z.lazy(() => GetBillRawData$inboundSchema),
});

export function getBillResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetBillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetBillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetBillResponse' from JSON`,
  );
}
