/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type GetPurchaseOrderLineItemsRequest = {
  purchaseOrderId: string;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

export type GetPurchaseOrderLineItemsPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type GetPurchaseOrderLineItemsMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: GetPurchaseOrderLineItemsPagination | null | undefined;
};

export type GetPurchaseOrderLineItemsErrors = {};

export type GetPurchaseOrderLineItemsRawData = {};

export type GetPurchaseOrderLineItemsResponse = {
  meta?: GetPurchaseOrderLineItemsMeta | null | undefined;
  data: Array<models.PurchaseOrderLineItemResponseDto>;
  errors: GetPurchaseOrderLineItemsErrors | null;
  rawData: GetPurchaseOrderLineItemsRawData | null;
};

/** @internal */
export type GetPurchaseOrderLineItemsRequest$Outbound = {
  purchaseOrderId: string;
  lastModifiedAt?: string | undefined;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  rawData?: boolean | undefined;
};

/** @internal */
export const GetPurchaseOrderLineItemsRequest$outboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsRequest$Outbound,
  GetPurchaseOrderLineItemsRequest
> = z.object({
  purchaseOrderId: z.string(),
  lastModifiedAt: z.optional(z.string()),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  rawData: z.optional(z.boolean()),
});

export function getPurchaseOrderLineItemsRequestToJSON(
  getPurchaseOrderLineItemsRequest: GetPurchaseOrderLineItemsRequest,
): string {
  return JSON.stringify(
    GetPurchaseOrderLineItemsRequest$outboundSchema.parse(
      getPurchaseOrderLineItemsRequest,
    ),
  );
}

/** @internal */
export const GetPurchaseOrderLineItemsPagination$inboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function getPurchaseOrderLineItemsPaginationFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderLineItemsPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetPurchaseOrderLineItemsPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderLineItemsPagination' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrderLineItemsMeta$inboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => GetPurchaseOrderLineItemsPagination$inboundSchema)),
  ),
});

export function getPurchaseOrderLineItemsMetaFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderLineItemsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrderLineItemsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderLineItemsMeta' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrderLineItemsErrors$inboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsErrors,
  unknown
> = z.object({});

export function getPurchaseOrderLineItemsErrorsFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderLineItemsErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrderLineItemsErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderLineItemsErrors' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrderLineItemsRawData$inboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsRawData,
  unknown
> = z.object({});

export function getPurchaseOrderLineItemsRawDataFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderLineItemsRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrderLineItemsRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderLineItemsRawData' from JSON`,
  );
}

/** @internal */
export const GetPurchaseOrderLineItemsResponse$inboundSchema: z.ZodMiniType<
  GetPurchaseOrderLineItemsResponse,
  unknown
> = z.object({
  meta: z.optional(
    z.nullable(z.lazy(() => GetPurchaseOrderLineItemsMeta$inboundSchema)),
  ),
  data: z.array(models.PurchaseOrderLineItemResponseDto$inboundSchema),
  errors: types.nullable(
    z.lazy(() => GetPurchaseOrderLineItemsErrors$inboundSchema),
  ),
  rawData: types.nullable(
    z.lazy(() => GetPurchaseOrderLineItemsRawData$inboundSchema),
  ),
});

export function getPurchaseOrderLineItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetPurchaseOrderLineItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetPurchaseOrderLineItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetPurchaseOrderLineItemsResponse' from JSON`,
  );
}
