/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type HandleConfigurationCallbackRequest = {
  code: string;
};

/** @internal */
export type HandleConfigurationCallbackRequest$Outbound = {
  code: string;
};

/** @internal */
export const HandleConfigurationCallbackRequest$outboundSchema: z.ZodMiniType<
  HandleConfigurationCallbackRequest$Outbound,
  HandleConfigurationCallbackRequest
> = z.object({
  code: z.string(),
});

export function handleConfigurationCallbackRequestToJSON(
  handleConfigurationCallbackRequest: HandleConfigurationCallbackRequest,
): string {
  return JSON.stringify(
    HandleConfigurationCallbackRequest$outboundSchema.parse(
      handleConfigurationCallbackRequest,
    ),
  );
}
