/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type HandleConfigurationCallbackRequest = {
  code: string;
};

/**
 * Configuration webhook event received and queued for processing
 */
export type HandleConfigurationCallbackResponse = {};

/** @internal */
export type HandleConfigurationCallbackRequest$Outbound = {
  code: string;
};

/** @internal */
export const HandleConfigurationCallbackRequest$outboundSchema: z.ZodMiniType<
  HandleConfigurationCallbackRequest$Outbound,
  HandleConfigurationCallbackRequest
> = z.object({
  code: z.string(),
});

export function handleConfigurationCallbackRequestToJSON(
  handleConfigurationCallbackRequest: HandleConfigurationCallbackRequest,
): string {
  return JSON.stringify(
    HandleConfigurationCallbackRequest$outboundSchema.parse(
      handleConfigurationCallbackRequest,
    ),
  );
}

/** @internal */
export const HandleConfigurationCallbackResponse$inboundSchema: z.ZodMiniType<
  HandleConfigurationCallbackResponse,
  unknown
> = z.object({});

export function handleConfigurationCallbackResponseFromJSON(
  jsonString: string,
): SafeParseResult<HandleConfigurationCallbackResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      HandleConfigurationCallbackResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'HandleConfigurationCallbackResponse' from JSON`,
  );
}
