/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PatchLineItemRequest = {
  invoiceId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.PatchLineItemRequestDto;
};

export type PatchLineItemPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type PatchLineItemMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: PatchLineItemPagination | null | undefined;
};

export type PatchLineItemErrors = {};

export type PatchLineItemRawData = {};

export type PatchLineItemResponse = {
  meta?: PatchLineItemMeta | null | undefined;
  data: models.LineItemResponseDto;
  errors: PatchLineItemErrors | null;
  rawData: PatchLineItemRawData | null;
};

/** @internal */
export type PatchLineItemRequest$Outbound = {
  invoiceId: string;
  lineItemId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.PatchLineItemRequestDto$Outbound;
};

/** @internal */
export const PatchLineItemRequest$outboundSchema: z.ZodMiniType<
  PatchLineItemRequest$Outbound,
  PatchLineItemRequest
> = z.object({
  invoiceId: z.string(),
  lineItemId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.PatchLineItemRequestDto$outboundSchema,
});

export function patchLineItemRequestToJSON(
  patchLineItemRequest: PatchLineItemRequest,
): string {
  return JSON.stringify(
    PatchLineItemRequest$outboundSchema.parse(patchLineItemRequest),
  );
}

/** @internal */
export const PatchLineItemPagination$inboundSchema: z.ZodMiniType<
  PatchLineItemPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function patchLineItemPaginationFromJSON(
  jsonString: string,
): SafeParseResult<PatchLineItemPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchLineItemPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchLineItemPagination' from JSON`,
  );
}

/** @internal */
export const PatchLineItemMeta$inboundSchema: z.ZodMiniType<
  PatchLineItemMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => PatchLineItemPagination$inboundSchema)),
  ),
});

export function patchLineItemMetaFromJSON(
  jsonString: string,
): SafeParseResult<PatchLineItemMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchLineItemMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchLineItemMeta' from JSON`,
  );
}

/** @internal */
export const PatchLineItemErrors$inboundSchema: z.ZodMiniType<
  PatchLineItemErrors,
  unknown
> = z.object({});

export function patchLineItemErrorsFromJSON(
  jsonString: string,
): SafeParseResult<PatchLineItemErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchLineItemErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchLineItemErrors' from JSON`,
  );
}

/** @internal */
export const PatchLineItemRawData$inboundSchema: z.ZodMiniType<
  PatchLineItemRawData,
  unknown
> = z.object({});

export function patchLineItemRawDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchLineItemRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchLineItemRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchLineItemRawData' from JSON`,
  );
}

/** @internal */
export const PatchLineItemResponse$inboundSchema: z.ZodMiniType<
  PatchLineItemResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => PatchLineItemMeta$inboundSchema))),
  data: models.LineItemResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => PatchLineItemErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => PatchLineItemRawData$inboundSchema)),
});

export function patchLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchLineItemResponse' from JSON`,
  );
}
