/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type PatchCustomersRequest = {
  contactId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.PatchContactRequestDto;
};

export type PatchCustomersPagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type PatchCustomersMeta = {
  warnings?: Array<string> | null | undefined;
  pagination?: PatchCustomersPagination | null | undefined;
};

export type PatchCustomersErrors = {};

export type PatchCustomersRawData = {};

export type PatchCustomersResponse = {
  meta?: PatchCustomersMeta | null | undefined;
  data: models.ContactResponseDto;
  errors: PatchCustomersErrors | null;
  rawData: PatchCustomersRawData | null;
};

/** @internal */
export type PatchCustomersRequest$Outbound = {
  contactId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  body: models.PatchContactRequestDto$Outbound;
};

/** @internal */
export const PatchCustomersRequest$outboundSchema: z.ZodMiniType<
  PatchCustomersRequest$Outbound,
  PatchCustomersRequest
> = z.object({
  contactId: z.string(),
  environmentName: z.optional(z.string()),
  companyId: z.optional(z.string()),
  body: models.PatchContactRequestDto$outboundSchema,
});

export function patchCustomersRequestToJSON(
  patchCustomersRequest: PatchCustomersRequest,
): string {
  return JSON.stringify(
    PatchCustomersRequest$outboundSchema.parse(patchCustomersRequest),
  );
}

/** @internal */
export const PatchCustomersPagination$inboundSchema: z.ZodMiniType<
  PatchCustomersPagination,
  unknown
> = z.object({
  total: types.number(),
  perPage: types.number(),
  currentPage: types.number(),
  totalPages: types.number(),
});

export function patchCustomersPaginationFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersPagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersPagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersPagination' from JSON`,
  );
}

/** @internal */
export const PatchCustomersMeta$inboundSchema: z.ZodMiniType<
  PatchCustomersMeta,
  unknown
> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(
    z.nullable(z.lazy(() => PatchCustomersPagination$inboundSchema)),
  ),
});

export function patchCustomersMetaFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersMeta' from JSON`,
  );
}

/** @internal */
export const PatchCustomersErrors$inboundSchema: z.ZodMiniType<
  PatchCustomersErrors,
  unknown
> = z.object({});

export function patchCustomersErrorsFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersErrors' from JSON`,
  );
}

/** @internal */
export const PatchCustomersRawData$inboundSchema: z.ZodMiniType<
  PatchCustomersRawData,
  unknown
> = z.object({});

export function patchCustomersRawDataFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersRawData' from JSON`,
  );
}

/** @internal */
export const PatchCustomersResponse$inboundSchema: z.ZodMiniType<
  PatchCustomersResponse,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => PatchCustomersMeta$inboundSchema))),
  data: models.ContactResponseDto$inboundSchema,
  errors: types.nullable(z.lazy(() => PatchCustomersErrors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => PatchCustomersRawData$inboundSchema)),
});

export function patchCustomersResponseFromJSON(
  jsonString: string,
): SafeParseResult<PatchCustomersResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PatchCustomersResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PatchCustomersResponse' from JSON`,
  );
}
