/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type SystemLoginUrlRequest = {
  targetSystem: string;
  callbackUrl?: string | undefined;
  cancelCallbackUrl?: string | undefined;
  companyId?: string | undefined;
  tenantId?: string | undefined;
  baseUrl?: string | undefined;
  environmentSelection?: boolean | undefined;
};

/** @internal */
export type SystemLoginUrlRequest$Outbound = {
  TARGET_SYSTEM: string;
  callbackUrl?: string | undefined;
  cancelCallbackUrl?: string | undefined;
  companyId?: string | undefined;
  tenantId?: string | undefined;
  baseUrl?: string | undefined;
  environmentSelection?: boolean | undefined;
};

/** @internal */
export const SystemLoginUrlRequest$outboundSchema: z.ZodMiniType<
  SystemLoginUrlRequest$Outbound,
  SystemLoginUrlRequest
> = z.pipe(
  z.object({
    targetSystem: z.string(),
    callbackUrl: z.optional(z.string()),
    cancelCallbackUrl: z.optional(z.string()),
    companyId: z.optional(z.string()),
    tenantId: z.optional(z.string()),
    baseUrl: z.optional(z.string()),
    environmentSelection: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetSystem: "TARGET_SYSTEM",
    });
  }),
);

export function systemLoginUrlRequestToJSON(
  systemLoginUrlRequest: SystemLoginUrlRequest,
): string {
  return JSON.stringify(
    SystemLoginUrlRequest$outboundSchema.parse(systemLoginUrlRequest),
  );
}
