/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type SystemRegistrationGlobals = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
};

export type SystemRegistrationRequest = {
  /**
   * API key
   */
  apiKey?: string | undefined;
  /**
   * Account key
   */
  accountKey?: string | undefined;
  body: models.SystemRegistrationDto;
};

/** @internal */
export type SystemRegistrationRequest$Outbound = {
  apiKey?: string | undefined;
  accountKey?: string | undefined;
  body: models.SystemRegistrationDto$Outbound;
};

/** @internal */
export const SystemRegistrationRequest$outboundSchema: z.ZodMiniType<
  SystemRegistrationRequest$Outbound,
  SystemRegistrationRequest
> = z.object({
  apiKey: z.optional(z.string()),
  accountKey: z.optional(z.string()),
  body: models.SystemRegistrationDto$outboundSchema,
});

export function systemRegistrationRequestToJSON(
  systemRegistrationRequest: SystemRegistrationRequest,
): string {
  return JSON.stringify(
    SystemRegistrationRequest$outboundSchema.parse(systemRegistrationRequest),
  );
}
