/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TestRequest = {
  accountKey: string;
};

/** @internal */
export type TestRequest$Outbound = {
  accountKey: string;
};

/** @internal */
export const TestRequest$outboundSchema: z.ZodMiniType<
  TestRequest$Outbound,
  TestRequest
> = z.object({
  accountKey: z.string(),
});

export function testRequestToJSON(testRequest: TestRequest): string {
  return JSON.stringify(TestRequest$outboundSchema.parse(testRequest));
}
