/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Submission page style updated successfully
 */
export type UpdateSubmissionPageStyleResponse = {};

/** @internal */
export const UpdateSubmissionPageStyleResponse$inboundSchema: z.ZodMiniType<
  UpdateSubmissionPageStyleResponse,
  unknown
> = z.object({});

export function updateSubmissionPageStyleResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateSubmissionPageStyleResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateSubmissionPageStyleResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateSubmissionPageStyleResponse' from JSON`,
  );
}
