/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type UpdateBillRequest = {
  billId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  /**
   * API key
   */
  xApiKey?: string | undefined;
  /**
   * Account key
   */
  xAccountKey?: string | undefined;
  body: models.CreateBillRequestDto;
};

export type UpdateBillErrors = {};

export type UpdateBillRawData = {};

export type UpdateBillResponse = {
  meta: models.MetaResponse;
  data: models.BillResponseDto;
  errors: UpdateBillErrors;
  rawData: UpdateBillRawData;
};

/** @internal */
export type UpdateBillRequest$Outbound = {
  billId: string;
  environmentName?: string | undefined;
  companyId?: string | undefined;
  "X-API-KEY"?: string | undefined;
  "X-ACCOUNT-KEY"?: string | undefined;
  body: models.CreateBillRequestDto$Outbound;
};

/** @internal */
export const UpdateBillRequest$outboundSchema: z.ZodMiniType<
  UpdateBillRequest$Outbound,
  UpdateBillRequest
> = z.pipe(
  z.object({
    billId: z.string(),
    environmentName: z.optional(z.string()),
    companyId: z.optional(z.string()),
    xApiKey: z.optional(z.string()),
    xAccountKey: z.optional(z.string()),
    body: models.CreateBillRequestDto$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      xApiKey: "X-API-KEY",
      xAccountKey: "X-ACCOUNT-KEY",
    });
  }),
);

export function updateBillRequestToJSON(
  updateBillRequest: UpdateBillRequest,
): string {
  return JSON.stringify(
    UpdateBillRequest$outboundSchema.parse(updateBillRequest),
  );
}

/** @internal */
export const UpdateBillErrors$inboundSchema: z.ZodMiniType<
  UpdateBillErrors,
  unknown
> = z.object({});

export function updateBillErrorsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateBillErrors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateBillErrors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateBillErrors' from JSON`,
  );
}

/** @internal */
export const UpdateBillRawData$inboundSchema: z.ZodMiniType<
  UpdateBillRawData,
  unknown
> = z.object({});

export function updateBillRawDataFromJSON(
  jsonString: string,
): SafeParseResult<UpdateBillRawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateBillRawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateBillRawData' from JSON`,
  );
}

/** @internal */
export const UpdateBillResponse$inboundSchema: z.ZodMiniType<
  UpdateBillResponse,
  unknown
> = z.object({
  meta: models.MetaResponse$inboundSchema,
  data: models.BillResponseDto$inboundSchema,
  errors: z.lazy(() => UpdateBillErrors$inboundSchema),
  rawData: z.lazy(() => UpdateBillRawData$inboundSchema),
});

export function updateBillResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateBillResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateBillResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateBillResponse' from JSON`,
  );
}
