/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type BankAccountRequestCommonDtoV2 = {
  id?: string | undefined;
  bic?: string | undefined;
  code?: string | undefined;
  iban?: string | undefined;
  number?: number | undefined;
};

/** @internal */
export type BankAccountRequestCommonDtoV2$Outbound = {
  id?: string | undefined;
  bic?: string | undefined;
  code?: string | undefined;
  iban?: string | undefined;
  number?: number | undefined;
};

/** @internal */
export const BankAccountRequestCommonDtoV2$outboundSchema: z.ZodMiniType<
  BankAccountRequestCommonDtoV2$Outbound,
  BankAccountRequestCommonDtoV2
> = z.object({
  id: z.optional(z.string()),
  bic: z.optional(z.string()),
  code: z.optional(z.string()),
  iban: z.optional(z.string()),
  number: z.optional(z.number()),
});

export function bankAccountRequestCommonDtoV2ToJSON(
  bankAccountRequestCommonDtoV2: BankAccountRequestCommonDtoV2,
): string {
  return JSON.stringify(
    BankAccountRequestCommonDtoV2$outboundSchema.parse(
      bankAccountRequestCommonDtoV2,
    ),
  );
}
