/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type BankAccountRequestCommonDtoV2 = {
  id: string;
  bic: string;
  code: string;
  iban: string;
  number: number;
};

/** @internal */
export type BankAccountRequestCommonDtoV2$Outbound = {
  id: string;
  bic: string;
  code: string;
  iban: string;
  number: number;
};

/** @internal */
export const BankAccountRequestCommonDtoV2$outboundSchema: z.ZodMiniType<
  BankAccountRequestCommonDtoV2$Outbound,
  BankAccountRequestCommonDtoV2
> = z.object({
  id: z.string(),
  bic: z.string(),
  code: z.string(),
  iban: z.string(),
  number: z.number(),
});

export function bankAccountRequestCommonDtoV2ToJSON(
  bankAccountRequestCommonDtoV2: BankAccountRequestCommonDtoV2,
): string {
  return JSON.stringify(
    BankAccountRequestCommonDtoV2$outboundSchema.parse(
      bankAccountRequestCommonDtoV2,
    ),
  );
}
