/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type BankAccountResponseCommonDtoV2 = {
  id: string;
  bic: string;
  code: string;
  iban: string;
  number: number;
};

/** @internal */
export const BankAccountResponseCommonDtoV2$inboundSchema: z.ZodMiniType<
  BankAccountResponseCommonDtoV2,
  unknown
> = z.object({
  id: types.string(),
  bic: types.string(),
  code: types.string(),
  iban: types.string(),
  number: types.number(),
});

export function bankAccountResponseCommonDtoV2FromJSON(
  jsonString: string,
): SafeParseResult<BankAccountResponseCommonDtoV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BankAccountResponseCommonDtoV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BankAccountResponseCommonDtoV2' from JSON`,
  );
}
