/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type Pagination = {
  total: number;
  perPage: number;
  currentPage: number;
  totalPages: number;
};

export type Meta = {
  warnings?: Array<string> | null | undefined;
  pagination?: Pagination | null | undefined;
};

export type Data = {};

export type Errors = {};

export type RawData = {};

export type BaseResponseDto = {
  meta?: Meta | null | undefined;
  data: Data;
  errors: Errors | null;
  rawData: RawData | null;
};

/** @internal */
export const Pagination$inboundSchema: z.ZodMiniType<Pagination, unknown> = z
  .object({
    total: types.number(),
    perPage: types.number(),
    currentPage: types.number(),
    totalPages: types.number(),
  });

export function paginationFromJSON(
  jsonString: string,
): SafeParseResult<Pagination, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Pagination$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Pagination' from JSON`,
  );
}

/** @internal */
export const Meta$inboundSchema: z.ZodMiniType<Meta, unknown> = z.object({
  warnings: z.optional(z.nullable(z.array(types.string()))),
  pagination: z.optional(z.nullable(z.lazy(() => Pagination$inboundSchema))),
});

export function metaFromJSON(
  jsonString: string,
): SafeParseResult<Meta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Meta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Meta' from JSON`,
  );
}

/** @internal */
export const Data$inboundSchema: z.ZodMiniType<Data, unknown> = z.object({});

export function dataFromJSON(
  jsonString: string,
): SafeParseResult<Data, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Data$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Data' from JSON`,
  );
}

/** @internal */
export const Errors$inboundSchema: z.ZodMiniType<Errors, unknown> = z.object(
  {},
);

export function errorsFromJSON(
  jsonString: string,
): SafeParseResult<Errors, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Errors$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Errors' from JSON`,
  );
}

/** @internal */
export const RawData$inboundSchema: z.ZodMiniType<RawData, unknown> = z.object(
  {},
);

export function rawDataFromJSON(
  jsonString: string,
): SafeParseResult<RawData, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RawData$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RawData' from JSON`,
  );
}

/** @internal */
export const BaseResponseDto$inboundSchema: z.ZodMiniType<
  BaseResponseDto,
  unknown
> = z.object({
  meta: z.optional(z.nullable(z.lazy(() => Meta$inboundSchema))),
  data: z.lazy(() => Data$inboundSchema),
  errors: types.nullable(z.lazy(() => Errors$inboundSchema)),
  rawData: types.nullable(z.lazy(() => RawData$inboundSchema)),
});

export function baseResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<BaseResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BaseResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BaseResponseDto' from JSON`,
  );
}
