/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ContactPerson = {
  emailAddresses: Array<string>;
  firstName: string;
  lastName: string;
  phoneNumbers: Array<string>;
  salutation: string;
};

/** @internal */
export const ContactPerson$inboundSchema: z.ZodMiniType<
  ContactPerson,
  unknown
> = z.object({
  emailAddresses: z.array(types.string()),
  firstName: types.string(),
  lastName: types.string(),
  phoneNumbers: z.array(types.string()),
  salutation: types.string(),
});
/** @internal */
export type ContactPerson$Outbound = {
  emailAddresses: Array<string>;
  firstName: string;
  lastName: string;
  phoneNumbers: Array<string>;
  salutation: string;
};

/** @internal */
export const ContactPerson$outboundSchema: z.ZodMiniType<
  ContactPerson$Outbound,
  ContactPerson
> = z.object({
  emailAddresses: z.array(z.string()),
  firstName: z.string(),
  lastName: z.string(),
  phoneNumbers: z.array(z.string()),
  salutation: z.string(),
});

export function contactPersonToJSON(contactPerson: ContactPerson): string {
  return JSON.stringify(ContactPerson$outboundSchema.parse(contactPerson));
}
export function contactPersonFromJSON(
  jsonString: string,
): SafeParseResult<ContactPerson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactPerson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactPerson' from JSON`,
  );
}
