/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { EmailAddress, EmailAddress$inboundSchema } from "./email-address.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { PhoneNumber, PhoneNumber$inboundSchema } from "./phone-number.js";

export type ContactPerson = {
  emailAddresses: Array<EmailAddress> | null;
  firstName: string | null;
  lastName: string | null;
  phoneNumbers: Array<PhoneNumber> | null;
  salutation: string | null;
};

/** @internal */
export const ContactPerson$inboundSchema: z.ZodMiniType<
  ContactPerson,
  unknown
> = z.object({
  emailAddresses: types.nullable(z.array(EmailAddress$inboundSchema)),
  firstName: types.nullable(types.string()),
  lastName: types.nullable(types.string()),
  phoneNumbers: types.nullable(z.array(PhoneNumber$inboundSchema)),
  salutation: types.nullable(types.string()),
});

export function contactPersonFromJSON(
  jsonString: string,
): SafeParseResult<ContactPerson, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactPerson$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactPerson' from JSON`,
  );
}
