/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ContactResponseDto,
  ContactResponseDto$inboundSchema,
} from "./contact-response-dto.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ContactByBatchMetaDataResponseDto = {
  id: string | null;
  accountNumberLength: number | null;
  chartOfAccount: string | null;
  createdDate: string | null;
  entries: Array<ContactResponseDto> | null;
  fiscalYearStartDate: string | null;
  taskId: string | null;
};

/** @internal */
export const ContactByBatchMetaDataResponseDto$inboundSchema: z.ZodMiniType<
  ContactByBatchMetaDataResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  accountNumberLength: types.nullable(types.number()),
  chartOfAccount: types.nullable(types.string()),
  createdDate: types.nullable(types.string()),
  entries: types.nullable(z.array(ContactResponseDto$inboundSchema)),
  fiscalYearStartDate: types.nullable(types.string()),
  taskId: types.nullable(types.string()),
});

export function contactByBatchMetaDataResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ContactByBatchMetaDataResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactByBatchMetaDataResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactByBatchMetaDataResponseDto' from JSON`,
  );
}
