/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  BankAccountResponse,
  BankAccountResponse$inboundSchema,
} from "./bank-account-response.js";
import {
  ContactAddress,
  ContactAddress$inboundSchema,
} from "./contact-address.js";
import {
  ContactPerson,
  ContactPerson$inboundSchema,
} from "./contact-person.js";
import { EmailAddress, EmailAddress$inboundSchema } from "./email-address.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { PhoneNumber, PhoneNumber$inboundSchema } from "./phone-number.js";

export const ContactResponseDtoContactType = {
  ContactPerson: "CONTACT_PERSON",
  Company: "COMPANY",
  Undefined: "UNDEFINED",
} as const;
export type ContactResponseDtoContactType = ClosedEnum<
  typeof ContactResponseDtoContactType
>;

export const ContactResponseDtoRole = {
  Supplier: "SUPPLIER",
  Customer: "CUSTOMER",
  Contact: "CONTACT",
} as const;
export type ContactResponseDtoRole = ClosedEnum<typeof ContactResponseDtoRole>;

export type ContactResponseDto = {
  id: string | null;
  addresses: Array<ContactAddress> | null;
  accountNumber?: number | null | undefined;
  bankAccounts?: Array<BankAccountResponse> | null | undefined;
  companyName: string | null;
  contactPersons: Array<ContactPerson> | null;
  contactType: ContactResponseDtoContactType | null;
  documentId: string | null;
  emailAddresses: Array<EmailAddress> | null;
  number: string | null;
  phoneNumbers: Array<PhoneNumber> | null;
  projectId: string | null;
  role: ContactResponseDtoRole | null;
  updatedDate: string | null;
  vatId?: string | null | undefined;
};

/** @internal */
export const ContactResponseDtoContactType$inboundSchema: z.ZodMiniEnum<
  typeof ContactResponseDtoContactType
> = z.enum(ContactResponseDtoContactType);

/** @internal */
export const ContactResponseDtoRole$inboundSchema: z.ZodMiniEnum<
  typeof ContactResponseDtoRole
> = z.enum(ContactResponseDtoRole);

/** @internal */
export const ContactResponseDto$inboundSchema: z.ZodMiniType<
  ContactResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  addresses: types.nullable(z.array(ContactAddress$inboundSchema)),
  accountNumber: z.optional(z.nullable(types.number())),
  bankAccounts: z.optional(
    z.nullable(z.array(BankAccountResponse$inboundSchema)),
  ),
  companyName: types.nullable(types.string()),
  contactPersons: types.nullable(z.array(ContactPerson$inboundSchema)),
  contactType: types.nullable(ContactResponseDtoContactType$inboundSchema),
  documentId: types.nullable(types.string()),
  emailAddresses: types.nullable(z.array(EmailAddress$inboundSchema)),
  number: types.nullable(types.string()),
  phoneNumbers: types.nullable(z.array(PhoneNumber$inboundSchema)),
  projectId: types.nullable(types.string()),
  role: types.nullable(ContactResponseDtoRole$inboundSchema),
  updatedDate: types.nullable(types.string()),
  vatId: z.optional(z.nullable(types.string())),
});

export function contactResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ContactResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactResponseDto' from JSON`,
  );
}
