/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ContactResponseDto,
  ContactResponseDto$inboundSchema,
} from "./contact-response-dto.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type ContactByBatchMetaDataResponseDto = {
  id: string;
  accountNumberLength: number;
  chartOfAccount: string;
  createdDate: string;
  entries: Array<ContactResponseDto>;
  fiscalYearStartDate: string;
  taskId: string;
};

/** @internal */
export const ContactByBatchMetaDataResponseDto$inboundSchema: z.ZodMiniType<
  ContactByBatchMetaDataResponseDto,
  unknown
> = z.object({
  id: types.string(),
  accountNumberLength: types.number(),
  chartOfAccount: types.string(),
  createdDate: types.string(),
  entries: z.array(ContactResponseDto$inboundSchema),
  fiscalYearStartDate: types.string(),
  taskId: types.string(),
});

export function contactByBatchMetaDataResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ContactByBatchMetaDataResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactByBatchMetaDataResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactByBatchMetaDataResponseDto' from JSON`,
  );
}
