/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  AddressOffer,
  AddressOffer$Outbound,
  AddressOffer$outboundSchema,
} from "./address-offer.js";
import {
  CreateOfferLineItemRequestDto,
  CreateOfferLineItemRequestDto$Outbound,
  CreateOfferLineItemRequestDto$outboundSchema,
} from "./create-offer-line-item-request-dto.js";

export const CreateOfferRequestDtoStatus = {
  Draft: "DRAFT",
  Sent: "SENT",
  Accepted: "ACCEPTED",
  Expired: "EXPIRED",
  Voided: "VOIDED",
  Declined: "DECLINED",
} as const;
export type CreateOfferRequestDtoStatus = ClosedEnum<
  typeof CreateOfferRequestDtoStatus
>;

export type CreateOfferRequestDto = {
  addresses: Array<AddressOffer>;
  contactId: string;
  currency: string;
  lineItems: Array<CreateOfferLineItemRequestDto>;
  name: string;
  offerDate: string;
  offerNumber: string;
  oneLineAddress: string;
  reference: string;
  status: CreateOfferRequestDtoStatus;
  taxText: string;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
};

/** @internal */
export const CreateOfferRequestDtoStatus$outboundSchema: z.ZodMiniEnum<
  typeof CreateOfferRequestDtoStatus
> = z.enum(CreateOfferRequestDtoStatus);

/** @internal */
export type CreateOfferRequestDto$Outbound = {
  addresses: Array<AddressOffer$Outbound>;
  contactId: string;
  currency: string;
  lineItems: Array<CreateOfferLineItemRequestDto$Outbound>;
  name: string;
  offerDate: string;
  offerNumber: string;
  oneLineAddress: string;
  reference: string;
  status: string;
  taxText: string;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
};

/** @internal */
export const CreateOfferRequestDto$outboundSchema: z.ZodMiniType<
  CreateOfferRequestDto$Outbound,
  CreateOfferRequestDto
> = z.object({
  addresses: z.array(AddressOffer$outboundSchema),
  contactId: z.string(),
  currency: z.string(),
  lineItems: z.array(CreateOfferLineItemRequestDto$outboundSchema),
  name: z.string(),
  offerDate: z.string(),
  offerNumber: z.string(),
  oneLineAddress: z.string(),
  reference: z.string(),
  status: CreateOfferRequestDtoStatus$outboundSchema,
  taxText: z.string(),
  totalDiscountAmount: z.number(),
  totalDiscountPercentage: z.number(),
  totalGrossAmount: z.number(),
  totalNetAmount: z.number(),
  totalTaxAmount: z.number(),
});

export function createOfferRequestDtoToJSON(
  createOfferRequestDto: CreateOfferRequestDto,
): string {
  return JSON.stringify(
    CreateOfferRequestDto$outboundSchema.parse(createOfferRequestDto),
  );
}
