/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreatePaymentLine = {
  accountId?: string | undefined;
  amount?: number | undefined;
  contactName?: string | undefined;
  contactId?: string | undefined;
  customerId?: string | undefined;
  description?: string | undefined;
  invoiceId?: string | undefined;
  supplierId?: string | undefined;
  paymentDate?: string | undefined;
};

/** @internal */
export type CreatePaymentLine$Outbound = {
  accountId?: string | undefined;
  amount?: number | undefined;
  contactName?: string | undefined;
  contactId?: string | undefined;
  customerId?: string | undefined;
  description?: string | undefined;
  invoiceId?: string | undefined;
  supplierId?: string | undefined;
  paymentDate?: string | undefined;
};

/** @internal */
export const CreatePaymentLine$outboundSchema: z.ZodMiniType<
  CreatePaymentLine$Outbound,
  CreatePaymentLine
> = z.object({
  accountId: z.optional(z.string()),
  amount: z.optional(z.number()),
  contactName: z.optional(z.string()),
  contactId: z.optional(z.string()),
  customerId: z.optional(z.string()),
  description: z.optional(z.string()),
  invoiceId: z.optional(z.string()),
  supplierId: z.optional(z.string()),
  paymentDate: z.optional(z.string()),
});

export function createPaymentLineToJSON(
  createPaymentLine: CreatePaymentLine,
): string {
  return JSON.stringify(
    CreatePaymentLine$outboundSchema.parse(createPaymentLine),
  );
}
