/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateEventSubscriptionRequestDto = {
  eventType: string;
  callbackUrl: string;
};

/** @internal */
export type CreateEventSubscriptionRequestDto$Outbound = {
  eventType: string;
  callbackUrl: string;
};

/** @internal */
export const CreateEventSubscriptionRequestDto$outboundSchema: z.ZodMiniType<
  CreateEventSubscriptionRequestDto$Outbound,
  CreateEventSubscriptionRequestDto
> = z.object({
  eventType: z.string(),
  callbackUrl: z.string(),
});

export function createEventSubscriptionRequestDtoToJSON(
  createEventSubscriptionRequestDto: CreateEventSubscriptionRequestDto,
): string {
  return JSON.stringify(
    CreateEventSubscriptionRequestDto$outboundSchema.parse(
      createEventSubscriptionRequestDto,
    ),
  );
}
