/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const CreateOfferLineItemRequestDtoType = {
  Comment: "COMMENT",
  Account: "ACCOUNT",
  Item: "ITEM",
  Resource: "RESOURCE",
  Value: "VALUE",
  FixedAsset: "FIXED_ASSET",
  Charge: "CHARGE",
} as const;
export type CreateOfferLineItemRequestDtoType = ClosedEnum<
  typeof CreateOfferLineItemRequestDtoType
>;

export type CreateOfferLineItemRequestDto = {
  accountCode: string;
  accountId: string;
  description: string;
  itemId: string;
  name: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  taxType: string;
  type: CreateOfferLineItemRequestDtoType;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
};

/** @internal */
export const CreateOfferLineItemRequestDtoType$outboundSchema: z.ZodMiniEnum<
  typeof CreateOfferLineItemRequestDtoType
> = z.enum(CreateOfferLineItemRequestDtoType);

/** @internal */
export type CreateOfferLineItemRequestDto$Outbound = {
  accountCode: string;
  accountId: string;
  description: string;
  itemId: string;
  name: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  taxType: string;
  type: string;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
};

/** @internal */
export const CreateOfferLineItemRequestDto$outboundSchema: z.ZodMiniType<
  CreateOfferLineItemRequestDto$Outbound,
  CreateOfferLineItemRequestDto
> = z.object({
  accountCode: z.string(),
  accountId: z.string(),
  description: z.string(),
  itemId: z.string(),
  name: z.string(),
  quantity: z.number(),
  taxCode: z.string(),
  taxRatePercentage: z.number(),
  taxType: z.string(),
  type: CreateOfferLineItemRequestDtoType$outboundSchema,
  totalDiscountAmount: z.number(),
  totalDiscountPercentage: z.number(),
  totalGrossAmount: z.number(),
  totalNetAmount: z.number(),
  totalTaxAmount: z.number(),
  unitAmount: z.number(),
  unitDiscountAmount: z.number(),
  unitDiscountPercentage: z.number(),
  unitName: z.string(),
});

export function createOfferLineItemRequestDtoToJSON(
  createOfferLineItemRequestDto: CreateOfferLineItemRequestDto,
): string {
  return JSON.stringify(
    CreateOfferLineItemRequestDto$outboundSchema.parse(
      createOfferLineItemRequestDto,
    ),
  );
}
