/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  ContactPerson,
  ContactPerson$Outbound,
  ContactPerson$outboundSchema,
} from "./contact-person.js";
import {
  CreateBankAccount,
  CreateBankAccount$Outbound,
  CreateBankAccount$outboundSchema,
} from "./create-bank-account.js";
import {
  CreateContactAddress,
  CreateContactAddress$Outbound,
  CreateContactAddress$outboundSchema,
} from "./create-contact-address.js";
import {
  EmailAddress,
  EmailAddress$Outbound,
  EmailAddress$outboundSchema,
} from "./email-address.js";
import {
  PhoneNumber,
  PhoneNumber$Outbound,
  PhoneNumber$outboundSchema,
} from "./phone-number.js";

export const CreateContactRequestDtoContactType = {
  ContactPerson: "CONTACT_PERSON",
  Company: "COMPANY",
} as const;
export type CreateContactRequestDtoContactType = ClosedEnum<
  typeof CreateContactRequestDtoContactType
>;

export const CreateContactRequestDtoRole = {
  Supplier: "SUPPLIER",
  Customer: "CUSTOMER",
  Contact: "CONTACT",
} as const;
export type CreateContactRequestDtoRole = ClosedEnum<
  typeof CreateContactRequestDtoRole
>;

export type CreateContactRequestDto = {
  addresses: Array<CreateContactAddress>;
  bankAccount: CreateBankAccount;
  companyName: string;
  contactPersons: Array<ContactPerson>;
  contactType: CreateContactRequestDtoContactType;
  documentId: string;
  emailAddresses: Array<EmailAddress>;
  number: string;
  phoneNumbers: Array<PhoneNumber>;
  projectId: string;
  role: CreateContactRequestDtoRole;
  vatId: string;
};

/** @internal */
export const CreateContactRequestDtoContactType$outboundSchema: z.ZodMiniEnum<
  typeof CreateContactRequestDtoContactType
> = z.enum(CreateContactRequestDtoContactType);

/** @internal */
export const CreateContactRequestDtoRole$outboundSchema: z.ZodMiniEnum<
  typeof CreateContactRequestDtoRole
> = z.enum(CreateContactRequestDtoRole);

/** @internal */
export type CreateContactRequestDto$Outbound = {
  addresses: Array<CreateContactAddress$Outbound>;
  bankAccount: CreateBankAccount$Outbound;
  companyName: string;
  contactPersons: Array<ContactPerson$Outbound>;
  contactType: string;
  documentId: string;
  emailAddresses: Array<EmailAddress$Outbound>;
  number: string;
  phoneNumbers: Array<PhoneNumber$Outbound>;
  projectId: string;
  role: string;
  vatId: string;
};

/** @internal */
export const CreateContactRequestDto$outboundSchema: z.ZodMiniType<
  CreateContactRequestDto$Outbound,
  CreateContactRequestDto
> = z.object({
  addresses: z.array(CreateContactAddress$outboundSchema),
  bankAccount: CreateBankAccount$outboundSchema,
  companyName: z.string(),
  contactPersons: z.array(ContactPerson$outboundSchema),
  contactType: CreateContactRequestDtoContactType$outboundSchema,
  documentId: z.string(),
  emailAddresses: z.array(EmailAddress$outboundSchema),
  number: z.string(),
  phoneNumbers: z.array(PhoneNumber$outboundSchema),
  projectId: z.string(),
  role: CreateContactRequestDtoRole$outboundSchema,
  vatId: z.string(),
});

export function createContactRequestDtoToJSON(
  createContactRequestDto: CreateContactRequestDto,
): string {
  return JSON.stringify(
    CreateContactRequestDto$outboundSchema.parse(createContactRequestDto),
  );
}
