/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const Method = {
  Get: "GET",
  Post: "POST",
  Put: "PUT",
  Patch: "PATCH",
  Delete: "DELETE",
} as const;
export type Method = ClosedEnum<typeof Method>;

export type Headers = {};

export type Body = {};

export type Query = {};

export type CreatePassThroughRequestDto = {
  path: string;
  method: Method;
  headers?: Headers | undefined;
  body?: Body | undefined;
  query?: Query | undefined;
};

/** @internal */
export const Method$outboundSchema: z.ZodMiniEnum<typeof Method> = z.enum(
  Method,
);

/** @internal */
export type Headers$Outbound = {};

/** @internal */
export const Headers$outboundSchema: z.ZodMiniType<Headers$Outbound, Headers> =
  z.object({});

export function headersToJSON(headers: Headers): string {
  return JSON.stringify(Headers$outboundSchema.parse(headers));
}

/** @internal */
export type Body$Outbound = {};

/** @internal */
export const Body$outboundSchema: z.ZodMiniType<Body$Outbound, Body> = z.object(
  {},
);

export function bodyToJSON(body: Body): string {
  return JSON.stringify(Body$outboundSchema.parse(body));
}

/** @internal */
export type Query$Outbound = {};

/** @internal */
export const Query$outboundSchema: z.ZodMiniType<Query$Outbound, Query> = z
  .object({});

export function queryToJSON(query: Query): string {
  return JSON.stringify(Query$outboundSchema.parse(query));
}

/** @internal */
export type CreatePassThroughRequestDto$Outbound = {
  path: string;
  method: string;
  headers?: Headers$Outbound | undefined;
  body?: Body$Outbound | undefined;
  query?: Query$Outbound | undefined;
};

/** @internal */
export const CreatePassThroughRequestDto$outboundSchema: z.ZodMiniType<
  CreatePassThroughRequestDto$Outbound,
  CreatePassThroughRequestDto
> = z.object({
  path: z.string(),
  method: Method$outboundSchema,
  headers: z.optional(z.lazy(() => Headers$outboundSchema)),
  body: z.optional(z.lazy(() => Body$outboundSchema)),
  query: z.optional(z.lazy(() => Query$outboundSchema)),
});

export function createPassThroughRequestDtoToJSON(
  createPassThroughRequestDto: CreatePassThroughRequestDto,
): string {
  return JSON.stringify(
    CreatePassThroughRequestDto$outboundSchema.parse(
      createPassThroughRequestDto,
    ),
  );
}
