/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  DiscountPeriodRequest,
  DiscountPeriodRequest$Outbound,
  DiscountPeriodRequest$outboundSchema,
} from "./discount-period-request.js";

export const CreatePaymentTermRequestDtoDueType = {
  DueInDays: "DUE_IN_DAYS",
  DueAsPeriod: "DUE_AS_PERIOD",
} as const;
export type CreatePaymentTermRequestDtoDueType = ClosedEnum<
  typeof CreatePaymentTermRequestDtoDueType
>;

export type CreatePaymentTermRequestDto = {
  code: string;
  description: string;
  discountDays: number;
  discountDays2: number;
  discountPercentage: number;
  discountPercentage2: number;
  discountPeriods: Array<DiscountPeriodRequest>;
  dueType: CreatePaymentTermRequestDtoDueType;
  name: string;
  paymentDays: number;
  paymentMethod: string;
};

/** @internal */
export const CreatePaymentTermRequestDtoDueType$outboundSchema: z.ZodMiniEnum<
  typeof CreatePaymentTermRequestDtoDueType
> = z.enum(CreatePaymentTermRequestDtoDueType);

/** @internal */
export type CreatePaymentTermRequestDto$Outbound = {
  code: string;
  description: string;
  discountDays: number;
  discountDays2: number;
  discountPercentage: number;
  discountPercentage2: number;
  discountPeriods: Array<DiscountPeriodRequest$Outbound>;
  dueType: string;
  name: string;
  paymentDays: number;
  paymentMethod: string;
};

/** @internal */
export const CreatePaymentTermRequestDto$outboundSchema: z.ZodMiniType<
  CreatePaymentTermRequestDto$Outbound,
  CreatePaymentTermRequestDto
> = z.object({
  code: z.string(),
  description: z.string(),
  discountDays: z.number(),
  discountDays2: z.number(),
  discountPercentage: z.number(),
  discountPercentage2: z.number(),
  discountPeriods: z.array(DiscountPeriodRequest$outboundSchema),
  dueType: CreatePaymentTermRequestDtoDueType$outboundSchema,
  name: z.string(),
  paymentDays: z.number(),
  paymentMethod: z.string(),
});

export function createPaymentTermRequestDtoToJSON(
  createPaymentTermRequestDto: CreatePaymentTermRequestDto,
): string {
  return JSON.stringify(
    CreatePaymentTermRequestDto$outboundSchema.parse(
      createPaymentTermRequestDto,
    ),
  );
}
