/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateSalesOrderLineItemRequestDto = {
  itemId: string;
  description: string;
  itemName: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
};

/** @internal */
export type CreateSalesOrderLineItemRequestDto$Outbound = {
  itemId: string;
  description: string;
  itemName: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
};

/** @internal */
export const CreateSalesOrderLineItemRequestDto$outboundSchema: z.ZodMiniType<
  CreateSalesOrderLineItemRequestDto$Outbound,
  CreateSalesOrderLineItemRequestDto
> = z.object({
  itemId: z.string(),
  description: z.string(),
  itemName: z.string(),
  quantity: z.number(),
  taxCode: z.string(),
  taxRatePercentage: z.number(),
  totalDiscountAmount: z.number(),
  totalDiscountPercentage: z.number(),
  totalGrossAmount: z.number(),
  totalNetAmount: z.number(),
  totalTaxAmount: z.number(),
  unitAmount: z.number(),
  unitDiscountAmount: z.number(),
  unitDiscountPercentage: z.number(),
  unitName: z.string(),
});

export function createSalesOrderLineItemRequestDtoToJSON(
  createSalesOrderLineItemRequestDto: CreateSalesOrderLineItemRequestDto,
): string {
  return JSON.stringify(
    CreateSalesOrderLineItemRequestDto$outboundSchema.parse(
      createSalesOrderLineItemRequestDto,
    ),
  );
}
