/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateAddress = {
  addressLine1?: string | undefined;
  addressLine2?: string | undefined;
  city?: string | undefined;
  postalCode?: string | undefined;
  countryCode?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export type CreateAddress$Outbound = {
  addressLine1?: string | undefined;
  addressLine2?: string | undefined;
  city?: string | undefined;
  postalCode?: string | undefined;
  countryCode?: string | undefined;
  type?: string | undefined;
};

/** @internal */
export const CreateAddress$outboundSchema: z.ZodMiniType<
  CreateAddress$Outbound,
  CreateAddress
> = z.object({
  addressLine1: z.optional(z.string()),
  addressLine2: z.optional(z.string()),
  city: z.optional(z.string()),
  postalCode: z.optional(z.string()),
  countryCode: z.optional(z.string()),
  type: z.optional(z.string()),
});

export function createAddressToJSON(createAddress: CreateAddress): string {
  return JSON.stringify(CreateAddress$outboundSchema.parse(createAddress));
}
