/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  BookingEntryRequestDto,
  BookingEntryRequestDto$Outbound,
  BookingEntryRequestDto$outboundSchema,
} from "./booking-entry-request-dto.js";

export const CreateBookingsRequestDtoChartOfAccount = {
  Skr03: "SKR03",
  Skr04: "SKR04",
  Skr42: "SKR42",
  Skr51: "SKR51",
  Skr14: "SKR14",
} as const;
export type CreateBookingsRequestDtoChartOfAccount = ClosedEnum<
  typeof CreateBookingsRequestDtoChartOfAccount
>;

export type CreateBookingsRequestDto = {
  accountNumberLength?: number | undefined;
  chartOfAccount?: CreateBookingsRequestDtoChartOfAccount | undefined;
  entries?: Array<BookingEntryRequestDto> | undefined;
  fiscalYearStartDate?: string | undefined;
};

/** @internal */
export const CreateBookingsRequestDtoChartOfAccount$outboundSchema:
  z.ZodMiniEnum<typeof CreateBookingsRequestDtoChartOfAccount> = z.enum(
    CreateBookingsRequestDtoChartOfAccount,
  );

/** @internal */
export type CreateBookingsRequestDto$Outbound = {
  accountNumberLength?: number | undefined;
  chartOfAccount?: string | undefined;
  entries?: Array<BookingEntryRequestDto$Outbound> | undefined;
  fiscalYearStartDate?: string | undefined;
};

/** @internal */
export const CreateBookingsRequestDto$outboundSchema: z.ZodMiniType<
  CreateBookingsRequestDto$Outbound,
  CreateBookingsRequestDto
> = z.object({
  accountNumberLength: z.optional(z.number()),
  chartOfAccount: z.optional(
    CreateBookingsRequestDtoChartOfAccount$outboundSchema,
  ),
  entries: z.optional(z.array(BookingEntryRequestDto$outboundSchema)),
  fiscalYearStartDate: z.optional(z.string()),
});

export function createBookingsRequestDtoToJSON(
  createBookingsRequestDto: CreateBookingsRequestDto,
): string {
  return JSON.stringify(
    CreateBookingsRequestDto$outboundSchema.parse(createBookingsRequestDto),
  );
}
