/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateBankAccount = {
  bic?: string | undefined;
  holder?: string | undefined;
  isMainAccount?: boolean | undefined;
  iban?: string | undefined;
  name?: string | undefined;
  sepa?: boolean | undefined;
};

/** @internal */
export type CreateBankAccount$Outbound = {
  bic?: string | undefined;
  holder?: string | undefined;
  isMainAccount?: boolean | undefined;
  iban?: string | undefined;
  name?: string | undefined;
  sepa?: boolean | undefined;
};

/** @internal */
export const CreateBankAccount$outboundSchema: z.ZodMiniType<
  CreateBankAccount$Outbound,
  CreateBankAccount
> = z.object({
  bic: z.optional(z.string()),
  holder: z.optional(z.string()),
  isMainAccount: z.optional(z.boolean()),
  iban: z.optional(z.string()),
  name: z.optional(z.string()),
  sepa: z.optional(z.boolean()),
});

export function createBankAccountToJSON(
  createBankAccount: CreateBankAccount,
): string {
  return JSON.stringify(
    CreateBankAccount$outboundSchema.parse(createBankAccount),
  );
}
