/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  CreateBankAccount,
  CreateBankAccount$Outbound,
  CreateBankAccount$outboundSchema,
} from "./create-bank-account.js";
import {
  CreateContactAddress,
  CreateContactAddress$Outbound,
  CreateContactAddress$outboundSchema,
} from "./create-contact-address.js";
import {
  CreateContactPerson,
  CreateContactPerson$Outbound,
  CreateContactPerson$outboundSchema,
} from "./create-contact-person.js";
import {
  CreateEmailAddress,
  CreateEmailAddress$Outbound,
  CreateEmailAddress$outboundSchema,
} from "./create-email-address.js";
import {
  CreatePhoneNumber,
  CreatePhoneNumber$Outbound,
  CreatePhoneNumber$outboundSchema,
} from "./create-phone-number.js";

export const CreateContactRequestDtoContactType = {
  ContactPerson: "CONTACT_PERSON",
  Company: "COMPANY",
} as const;
export type CreateContactRequestDtoContactType = ClosedEnum<
  typeof CreateContactRequestDtoContactType
>;

export const CreateContactRequestDtoRole = {
  Supplier: "SUPPLIER",
  Customer: "CUSTOMER",
  Contact: "CONTACT",
} as const;
export type CreateContactRequestDtoRole = ClosedEnum<
  typeof CreateContactRequestDtoRole
>;

export type CreateContactRequestDto = {
  addresses?: Array<CreateContactAddress> | undefined;
  bankAccount?: CreateBankAccount | undefined;
  companyName?: string | undefined;
  contactPersons?: Array<CreateContactPerson> | undefined;
  contactType: CreateContactRequestDtoContactType;
  documentId?: string | undefined;
  emailAddresses?: Array<CreateEmailAddress> | undefined;
  number?: string | undefined;
  phoneNumbers?: Array<CreatePhoneNumber> | undefined;
  projectId?: string | undefined;
  role?: CreateContactRequestDtoRole | undefined;
  vatId?: string | undefined;
};

/** @internal */
export const CreateContactRequestDtoContactType$outboundSchema: z.ZodMiniEnum<
  typeof CreateContactRequestDtoContactType
> = z.enum(CreateContactRequestDtoContactType);

/** @internal */
export const CreateContactRequestDtoRole$outboundSchema: z.ZodMiniEnum<
  typeof CreateContactRequestDtoRole
> = z.enum(CreateContactRequestDtoRole);

/** @internal */
export type CreateContactRequestDto$Outbound = {
  addresses?: Array<CreateContactAddress$Outbound> | undefined;
  bankAccount?: CreateBankAccount$Outbound | undefined;
  companyName?: string | undefined;
  contactPersons?: Array<CreateContactPerson$Outbound> | undefined;
  contactType: string;
  documentId?: string | undefined;
  emailAddresses?: Array<CreateEmailAddress$Outbound> | undefined;
  number?: string | undefined;
  phoneNumbers?: Array<CreatePhoneNumber$Outbound> | undefined;
  projectId?: string | undefined;
  role?: string | undefined;
  vatId?: string | undefined;
};

/** @internal */
export const CreateContactRequestDto$outboundSchema: z.ZodMiniType<
  CreateContactRequestDto$Outbound,
  CreateContactRequestDto
> = z.object({
  addresses: z.optional(z.array(CreateContactAddress$outboundSchema)),
  bankAccount: z.optional(CreateBankAccount$outboundSchema),
  companyName: z.optional(z.string()),
  contactPersons: z.optional(z.array(CreateContactPerson$outboundSchema)),
  contactType: CreateContactRequestDtoContactType$outboundSchema,
  documentId: z.optional(z.string()),
  emailAddresses: z.optional(z.array(CreateEmailAddress$outboundSchema)),
  number: z.optional(z.string()),
  phoneNumbers: z.optional(z.array(CreatePhoneNumber$outboundSchema)),
  projectId: z.optional(z.string()),
  role: z.optional(CreateContactRequestDtoRole$outboundSchema),
  vatId: z.optional(z.string()),
});

export function createContactRequestDtoToJSON(
  createContactRequestDto: CreateContactRequestDto,
): string {
  return JSON.stringify(
    CreateContactRequestDto$outboundSchema.parse(createContactRequestDto),
  );
}
