/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DimensionMetaResponseDto = {
  description: string | null;
  dimension: string | null;
};

/** @internal */
export const DimensionMetaResponseDto$inboundSchema: z.ZodMiniType<
  DimensionMetaResponseDto,
  unknown
> = z.object({
  description: types.nullable(types.string()),
  dimension: types.nullable(types.string()),
});

export function dimensionMetaResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DimensionMetaResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DimensionMetaResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DimensionMetaResponseDto' from JSON`,
  );
}
