/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DimensionResponseCommonDtoV2 = {
  id: string;
  code: string;
  dimension: string;
  name: string;
};

/** @internal */
export const DimensionResponseCommonDtoV2$inboundSchema: z.ZodMiniType<
  DimensionResponseCommonDtoV2,
  unknown
> = z.object({
  id: types.string(),
  code: types.string(),
  dimension: types.string(),
  name: types.string(),
});

export function dimensionResponseCommonDtoV2FromJSON(
  jsonString: string,
): SafeParseResult<DimensionResponseCommonDtoV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DimensionResponseCommonDtoV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DimensionResponseCommonDtoV2' from JSON`,
  );
}
