/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DocumentTypesResponseDto = {
  name: string;
  category: string;
};

/** @internal */
export const DocumentTypesResponseDto$inboundSchema: z.ZodMiniType<
  DocumentTypesResponseDto,
  unknown
> = z.object({
  name: types.string(),
  category: types.string(),
});

export function documentTypesResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DocumentTypesResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentTypesResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentTypesResponseDto' from JSON`,
  );
}
