/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type DocumentExtensionsResponseDto = {
  allowedFileExtensions: Array<string> | null;
};

/** @internal */
export const DocumentExtensionsResponseDto$inboundSchema: z.ZodMiniType<
  DocumentExtensionsResponseDto,
  unknown
> = z.pipe(
  z.object({
    allowed_file_extensions: types.nullable(z.array(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "allowed_file_extensions": "allowedFileExtensions",
    });
  }),
);

export function documentExtensionsResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<DocumentExtensionsResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentExtensionsResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentExtensionsResponseDto' from JSON`,
  );
}
