/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const EmailAddressType = {
  Business: "BUSINESS",
  Private: "PRIVATE",
  Office: "OFFICE",
  Invoice: "INVOICE",
  Payment: "PAYMENT",
  Other: "OTHER",
} as const;
export type EmailAddressType = OpenEnum<typeof EmailAddressType>;

export type EmailAddress = {
  email: string;
  type: EmailAddressType;
};

/** @internal */
export const EmailAddressType$inboundSchema: z.ZodMiniType<
  EmailAddressType,
  unknown
> = openEnums.inboundSchema(EmailAddressType);
/** @internal */
export const EmailAddressType$outboundSchema: z.ZodMiniType<
  string,
  EmailAddressType
> = openEnums.outboundSchema(EmailAddressType);

/** @internal */
export const EmailAddress$inboundSchema: z.ZodMiniType<EmailAddress, unknown> =
  z.object({
    email: types.string(),
    type: EmailAddressType$inboundSchema,
  });
/** @internal */
export type EmailAddress$Outbound = {
  email: string;
  type: string;
};

/** @internal */
export const EmailAddress$outboundSchema: z.ZodMiniType<
  EmailAddress$Outbound,
  EmailAddress
> = z.object({
  email: z.string(),
  type: EmailAddressType$outboundSchema,
});

export function emailAddressToJSON(emailAddress: EmailAddress): string {
  return JSON.stringify(EmailAddress$outboundSchema.parse(emailAddress));
}
export function emailAddressFromJSON(
  jsonString: string,
): SafeParseResult<EmailAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailAddress' from JSON`,
  );
}
