/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const EmailAddressV2Type = {
  Business: "BUSINESS",
  Private: "PRIVATE",
  Office: "OFFICE",
  Invoice: "INVOICE",
  Payment: "PAYMENT",
  Other: "OTHER",
} as const;
export type EmailAddressV2Type = ClosedEnum<typeof EmailAddressV2Type>;

export type EmailAddressV2 = {
  email: string | null;
  type: EmailAddressV2Type | null;
};

/** @internal */
export const EmailAddressV2Type$inboundSchema: z.ZodMiniEnum<
  typeof EmailAddressV2Type
> = z.enum(EmailAddressV2Type);
/** @internal */
export const EmailAddressV2Type$outboundSchema: z.ZodMiniEnum<
  typeof EmailAddressV2Type
> = EmailAddressV2Type$inboundSchema;

/** @internal */
export const EmailAddressV2$inboundSchema: z.ZodMiniType<
  EmailAddressV2,
  unknown
> = z.object({
  email: types.nullable(types.string()),
  type: types.nullable(EmailAddressV2Type$inboundSchema),
});
/** @internal */
export type EmailAddressV2$Outbound = {
  email: string | null;
  type: string | null;
};

/** @internal */
export const EmailAddressV2$outboundSchema: z.ZodMiniType<
  EmailAddressV2$Outbound,
  EmailAddressV2
> = z.object({
  email: z.nullable(z.string()),
  type: z.nullable(EmailAddressV2Type$outboundSchema),
});

export function emailAddressV2ToJSON(emailAddressV2: EmailAddressV2): string {
  return JSON.stringify(EmailAddressV2$outboundSchema.parse(emailAddressV2));
}
export function emailAddressV2FromJSON(
  jsonString: string,
): SafeParseResult<EmailAddressV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EmailAddressV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EmailAddressV2' from JSON`,
  );
}
