/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type EnvironmentResponseDto = {
  name: string | null;
  type?: string | null | undefined;
  tenantId?: string | null | undefined;
  applicationFamily?: string | null | undefined;
  countryCode?: string | null | undefined;
};

/** @internal */
export const EnvironmentResponseDto$inboundSchema: z.ZodMiniType<
  EnvironmentResponseDto,
  unknown
> = z.object({
  name: types.nullable(types.string()),
  type: z.optional(z.nullable(types.string())),
  tenantId: z.optional(z.nullable(types.string())),
  applicationFamily: z.optional(z.nullable(types.string())),
  countryCode: z.optional(z.nullable(types.string())),
});

export function environmentResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<EnvironmentResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EnvironmentResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EnvironmentResponseDto' from JSON`,
  );
}
