/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { Dimension, Dimension$inboundSchema } from "./dimension.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ExpenseLineItemResponseCurrency = {
  Aed: "AED",
  Afn: "AFN",
  All: "ALL",
  Amd: "AMD",
  Ang: "ANG",
  Aoa: "AOA",
  Ars: "ARS",
  Aud: "AUD",
  Awg: "AWG",
  Azn: "AZN",
  Bam: "BAM",
  Bbd: "BBD",
  Bdt: "BDT",
  Bgn: "BGN",
  Bhd: "BHD",
  Bif: "BIF",
  Bmd: "BMD",
  Bnd: "BND",
  Bob: "BOB",
  Brl: "BRL",
  Bsd: "BSD",
  Btn: "BTN",
  Bwp: "BWP",
  Byr: "BYR",
  Bzd: "BZD",
  Cad: "CAD",
  Cdf: "CDF",
  Chf: "CHF",
  Clp: "CLP",
  Cny: "CNY",
  Cop: "COP",
  Crc: "CRC",
  Cuc: "CUC",
  Cve: "CVE",
  Czk: "CZK",
  Djf: "DJF",
  Dkk: "DKK",
  Dop: "DOP",
  Dzd: "DZD",
  Eek: "EEK",
  Egp: "EGP",
  Ern: "ERN",
  Etb: "ETB",
  Eur: "EUR",
  Fjd: "FJD",
  Fkp: "FKP",
  Gbp: "GBP",
  Gel: "GEL",
  Ghs: "GHS",
  Gip: "GIP",
  Gmd: "GMD",
  Gnf: "GNF",
  Gqe: "GQE",
  Gtq: "GTQ",
  Gyd: "GYD",
  Hkd: "HKD",
  Hnl: "HNL",
  Hrk: "HRK",
  Htg: "HTG",
  Huf: "HUF",
  Idr: "IDR",
  Ils: "ILS",
  Inr: "INR",
  Iqd: "IQD",
  Irr: "IRR",
  Isk: "ISK",
  Jmd: "JMD",
  Jod: "JOD",
  Jpy: "JPY",
  Kes: "KES",
  Kgs: "KGS",
  Khr: "KHR",
  Kmf: "KMF",
  Kpw: "KPW",
  Krw: "KRW",
  Kwd: "KWD",
  Kyd: "KYD",
  Kzt: "KZT",
  Lak: "LAK",
  Lbp: "LBP",
  Lkr: "LKR",
  Lrd: "LRD",
  Lsl: "LSL",
  Ltl: "LTL",
  Lvl: "LVL",
  Lyd: "LYD",
  Mad: "MAD",
  Mdl: "MDL",
  Mga: "MGA",
  Mkd: "MKD",
  Mmk: "MMK",
  Mnt: "MNT",
  Mop: "MOP",
  Mro: "MRO",
  Mur: "MUR",
  Mvr: "MVR",
  Mwk: "MWK",
  Mxn: "MXN",
  Myr: "MYR",
  Mzm: "MZM",
  Nad: "NAD",
  Ngn: "NGN",
  Nio: "NIO",
  Nok: "NOK",
  Npr: "NPR",
  Nzd: "NZD",
  Omr: "OMR",
  Pab: "PAB",
  Pen: "PEN",
  Pgk: "PGK",
  Php: "PHP",
  Pkr: "PKR",
  Pln: "PLN",
  Pyg: "PYG",
  Qar: "QAR",
  Ron: "RON",
  Rsd: "RSD",
  Rub: "RUB",
  Sar: "SAR",
  Sbd: "SBD",
  Scr: "SCR",
  Sdg: "SDG",
  Sek: "SEK",
  Sgd: "SGD",
  Shp: "SHP",
  Sll: "SLL",
  Sos: "SOS",
  Srd: "SRD",
  Syp: "SYP",
  Szl: "SZL",
  Thb: "THB",
  Tjs: "TJS",
  Tmt: "TMT",
  Tnd: "TND",
  Try: "TRY",
  Ttd: "TTD",
  Twd: "TWD",
  Tzs: "TZS",
  Uah: "UAH",
  Ugx: "UGX",
  Usd: "USD",
  Uyu: "UYU",
  Uzs: "UZS",
  Veb: "VEB",
  Vnd: "VND",
  Vuv: "VUV",
  Wst: "WST",
  Xaf: "XAF",
  Xcd: "XCD",
  Xdr: "XDR",
  Xof: "XOF",
  Xpf: "XPF",
  Yer: "YER",
  Zar: "ZAR",
  Zmk: "ZMK",
  Zwr: "ZWR",
} as const;
export type ExpenseLineItemResponseCurrency = OpenEnum<
  typeof ExpenseLineItemResponseCurrency
>;

export type ExpenseLineItemResponseTaxRate = {
  id: string | null;
  code: string | null;
  name: string | null;
  taxRatePercentage: string | null;
};

export type ExpenseLineItemResponse = {
  id: string | null;
  accountCode: string | null;
  accountId: string | null;
  accountNumber: number | null;
  createdDate: string | null;
  currency: ExpenseLineItemResponseCurrency | null;
  description: string | null;
  dimensions: Array<Dimension> | null;
  documentNumber: string | null;
  exchangeRate: number | null;
  itemId: string | null;
  taxRate: ExpenseLineItemResponseTaxRate | null;
  totalGrossAmount: number | null;
  totalNetAmount: number | null;
  updatedDate: string | null;
};

/** @internal */
export const ExpenseLineItemResponseCurrency$inboundSchema: z.ZodMiniType<
  ExpenseLineItemResponseCurrency,
  unknown
> = openEnums.inboundSchema(ExpenseLineItemResponseCurrency);

/** @internal */
export const ExpenseLineItemResponseTaxRate$inboundSchema: z.ZodMiniType<
  ExpenseLineItemResponseTaxRate,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  code: types.nullable(types.string()),
  name: types.nullable(types.string()),
  taxRatePercentage: types.nullable(types.string()),
});

export function expenseLineItemResponseTaxRateFromJSON(
  jsonString: string,
): SafeParseResult<ExpenseLineItemResponseTaxRate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpenseLineItemResponseTaxRate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpenseLineItemResponseTaxRate' from JSON`,
  );
}

/** @internal */
export const ExpenseLineItemResponse$inboundSchema: z.ZodMiniType<
  ExpenseLineItemResponse,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  accountCode: types.nullable(types.string()),
  accountId: types.nullable(types.string()),
  accountNumber: types.nullable(types.number()),
  createdDate: types.nullable(types.string()),
  currency: types.nullable(ExpenseLineItemResponseCurrency$inboundSchema),
  description: types.nullable(types.string()),
  dimensions: types.nullable(z.array(Dimension$inboundSchema)),
  documentNumber: types.nullable(types.string()),
  exchangeRate: types.nullable(types.number()),
  itemId: types.nullable(types.string()),
  taxRate: types.nullable(
    z.lazy(() => ExpenseLineItemResponseTaxRate$inboundSchema),
  ),
  totalGrossAmount: types.nullable(types.number()),
  totalNetAmount: types.nullable(types.number()),
  updatedDate: types.nullable(types.string()),
});

export function expenseLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<ExpenseLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ExpenseLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ExpenseLineItemResponse' from JSON`,
  );
}
