/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type GoodsReceiptLineItemResponse = {
  id: string;
  createdDate: string;
  description: string;
  itemId: string;
  itemName: string;
  projectId: string;
  purchaseOrderId: string;
  quantityOrdered: number;
  quantityReceived: number;
  updatedDate: string;
};

/** @internal */
export const GoodsReceiptLineItemResponse$inboundSchema: z.ZodMiniType<
  GoodsReceiptLineItemResponse,
  unknown
> = z.object({
  id: types.string(),
  createdDate: types.string(),
  description: types.string(),
  itemId: types.string(),
  itemName: types.string(),
  projectId: types.string(),
  purchaseOrderId: types.string(),
  quantityOrdered: types.number(),
  quantityReceived: types.number(),
  updatedDate: types.string(),
});

export function goodsReceiptLineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<GoodsReceiptLineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoodsReceiptLineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoodsReceiptLineItemResponse' from JSON`,
  );
}
