/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  GoodsReceiptLineItemResponse,
  GoodsReceiptLineItemResponse$inboundSchema,
} from "./goods-receipt-line-item-response.js";

export type GoodsReceiptResponseDto = {
  id: string;
  comment: string;
  createdDate: string;
  description: string;
  lineItems: Array<GoodsReceiptLineItemResponse>;
  reference: string;
  supplierId: string;
  updatedDate: string;
};

/** @internal */
export const GoodsReceiptResponseDto$inboundSchema: z.ZodMiniType<
  GoodsReceiptResponseDto,
  unknown
> = z.object({
  id: types.string(),
  comment: types.string(),
  createdDate: types.string(),
  description: types.string(),
  lineItems: z.array(GoodsReceiptLineItemResponse$inboundSchema),
  reference: types.string(),
  supplierId: types.string(),
  updatedDate: types.string(),
});

export function goodsReceiptResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<GoodsReceiptResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GoodsReceiptResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GoodsReceiptResponseDto' from JSON`,
  );
}
