/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InvoiceDimensionResponseDto = {
  id: string;
  categoryName: string;
  name: string;
};

/** @internal */
export const InvoiceDimensionResponseDto$inboundSchema: z.ZodMiniType<
  InvoiceDimensionResponseDto,
  unknown
> = z.object({
  id: types.string(),
  categoryName: types.string(),
  name: types.string(),
});

export function invoiceDimensionResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceDimensionResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceDimensionResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceDimensionResponseDto' from JSON`,
  );
}
