/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ItemResponseDtoType = {
  Product: "PRODUCT",
  Service: "SERVICE",
} as const;
export type ItemResponseDtoType = ClosedEnum<typeof ItemResponseDtoType>;

export const ItemResponseDtoUnitName = {
  Piece: "PIECE",
  Stuck: "STÜCK",
  NotUnit: "NOT_UNIT",
  CubicMetre: "CUBIC_METRE",
  Day: "DAY",
  Gram: "GRAM",
  Hour: "HOUR",
  Kilogram: "KILOGRAM",
  Kilometre: "KILOMETRE",
  Litre: "LITRE",
  Metre: "METRE",
  Milligram: "MILLIGRAM",
  Millilitre: "MILLILITRE",
  Month: "MONTH",
  Night: "NIGHT",
  Pack: "PACK",
  Percentage: "PERCENTAGE",
  SquareMetre: "SQUARE_METRE",
  Tonne: "TONNE",
  Unit: "UNIT",
} as const;
export type ItemResponseDtoUnitName = ClosedEnum<
  typeof ItemResponseDtoUnitName
>;

export type ItemResponseDto = {
  id: string | null;
  assetAccountId: string | null;
  expenseAccountId: string | null;
  incomeAccountId: string | null;
  inventoryStartDate: string | null;
  itemNumber: string | null;
  lastModifiedDate: string | null;
  name: string | null;
  priceIncludesTax: boolean | null;
  stockCount: number | null;
  taxCode: string | null;
  taxRatePercentage: number | null;
  type: ItemResponseDtoType | null;
  unitName: ItemResponseDtoUnitName | null;
  unitPurchasePrice: number | null;
  unitSalesPrice: number | null;
};

/** @internal */
export const ItemResponseDtoType$inboundSchema: z.ZodMiniEnum<
  typeof ItemResponseDtoType
> = z.enum(ItemResponseDtoType);

/** @internal */
export const ItemResponseDtoUnitName$inboundSchema: z.ZodMiniEnum<
  typeof ItemResponseDtoUnitName
> = z.enum(ItemResponseDtoUnitName);

/** @internal */
export const ItemResponseDto$inboundSchema: z.ZodMiniType<
  ItemResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  assetAccountId: types.nullable(types.string()),
  expenseAccountId: types.nullable(types.string()),
  incomeAccountId: types.nullable(types.string()),
  inventoryStartDate: types.nullable(types.string()),
  itemNumber: types.nullable(types.string()),
  lastModifiedDate: types.nullable(types.string()),
  name: types.nullable(types.string()),
  priceIncludesTax: types.nullable(types.boolean()),
  stockCount: types.nullable(types.number()),
  taxCode: types.nullable(types.string()),
  taxRatePercentage: types.nullable(types.number()),
  type: types.nullable(ItemResponseDtoType$inboundSchema),
  unitName: types.nullable(ItemResponseDtoUnitName$inboundSchema),
  unitPurchasePrice: types.nullable(types.number()),
  unitSalesPrice: types.nullable(types.number()),
});

export function itemResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<ItemResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ItemResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ItemResponseDto' from JSON`,
  );
}
