/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const LineItemResponseType = {
  Goods: "GOODS",
  Services: "SERVICES",
} as const;
export type LineItemResponseType = ClosedEnum<typeof LineItemResponseType>;

export type LineItemResponse = {
  id: string | null;
  accountCode: string | null;
  accountId: string | null;
  accountName: string | null;
  accountNumber: number | null;
  bookingTaxCode: string | null;
  createdDate: string | null;
  description: string | null;
  dimension1: string | null;
  dimension2: string | null;
  discountAmount: number | null;
  discountAmount2: number | null;
  discountPercentage: number | null;
  discountPercentage2: number | null;
  taxCode: string | null;
  taxRatePercentage: number | null;
  totalGrossAmount: number | null;
  totalNetAmount: number | null;
  type?: LineItemResponseType | null | undefined;
  updatedDate: string | null;
};

/** @internal */
export const LineItemResponseType$inboundSchema: z.ZodMiniEnum<
  typeof LineItemResponseType
> = z.enum(LineItemResponseType);

/** @internal */
export const LineItemResponse$inboundSchema: z.ZodMiniType<
  LineItemResponse,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  accountCode: types.nullable(types.string()),
  accountId: types.nullable(types.string()),
  accountName: types.nullable(types.string()),
  accountNumber: types.nullable(types.number()),
  bookingTaxCode: types.nullable(types.string()),
  createdDate: types.nullable(types.string()),
  description: types.nullable(types.string()),
  dimension1: types.nullable(types.string()),
  dimension2: types.nullable(types.string()),
  discountAmount: types.nullable(types.number()),
  discountAmount2: types.nullable(types.number()),
  discountPercentage: types.nullable(types.number()),
  discountPercentage2: types.nullable(types.number()),
  taxCode: types.nullable(types.string()),
  taxRatePercentage: types.nullable(types.number()),
  totalGrossAmount: types.nullable(types.number()),
  totalNetAmount: types.nullable(types.number()),
  type: z.optional(z.nullable(LineItemResponseType$inboundSchema)),
  updatedDate: types.nullable(types.string()),
});

export function lineItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<LineItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => LineItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'LineItemResponse' from JSON`,
  );
}
