/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const OfferLineItemResponseDtoType = {
  Comment: "COMMENT",
  Account: "ACCOUNT",
  Item: "ITEM",
  Resource: "RESOURCE",
  Value: "VALUE",
  FixedAsset: "FIXED_ASSET",
  Charge: "CHARGE",
} as const;
export type OfferLineItemResponseDtoType = OpenEnum<
  typeof OfferLineItemResponseDtoType
>;

export type OfferLineItemResponseDto = {
  id: string;
  accountCode: string;
  accountId: string;
  createdDate: string;
  description: string;
  itemId: string;
  name: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  taxType: string;
  type: OfferLineItemResponseDtoType;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
  updatedDate: string;
};

/** @internal */
export const OfferLineItemResponseDtoType$inboundSchema: z.ZodMiniType<
  OfferLineItemResponseDtoType,
  unknown
> = openEnums.inboundSchema(OfferLineItemResponseDtoType);

/** @internal */
export const OfferLineItemResponseDto$inboundSchema: z.ZodMiniType<
  OfferLineItemResponseDto,
  unknown
> = z.object({
  id: types.string(),
  accountCode: types.string(),
  accountId: types.string(),
  createdDate: types.string(),
  description: types.string(),
  itemId: types.string(),
  name: types.string(),
  quantity: types.number(),
  taxCode: types.string(),
  taxRatePercentage: types.number(),
  taxType: types.string(),
  type: OfferLineItemResponseDtoType$inboundSchema,
  totalDiscountAmount: types.number(),
  totalDiscountPercentage: types.number(),
  totalGrossAmount: types.number(),
  totalNetAmount: types.number(),
  totalTaxAmount: types.number(),
  unitAmount: types.number(),
  unitDiscountAmount: types.number(),
  unitDiscountPercentage: types.number(),
  unitName: types.string(),
  updatedDate: types.string(),
});

export function offerLineItemResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<OfferLineItemResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OfferLineItemResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OfferLineItemResponseDto' from JSON`,
  );
}
