/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AddressOffer, AddressOffer$inboundSchema } from "./address-offer.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OfferLineItemResponseDto,
  OfferLineItemResponseDto$inboundSchema,
} from "./offer-line-item-response-dto.js";

export const OfferResponseDtoStatus = {
  Draft: "DRAFT",
  Sent: "SENT",
  Accepted: "ACCEPTED",
  Expired: "EXPIRED",
  Voided: "VOIDED",
  Declined: "DECLINED",
} as const;
export type OfferResponseDtoStatus = OpenEnum<typeof OfferResponseDtoStatus>;

export type OfferResponseDto = {
  id: string;
  addresses: Array<AddressOffer>;
  contactId: string;
  createdDate: string;
  currency: string;
  lineItems: Array<OfferLineItemResponseDto>;
  name: string;
  offerDate: string;
  offerNumber: string;
  oneLineAddress: string;
  reference: string;
  status: OfferResponseDtoStatus;
  taxText: string;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  updatedDate: string;
};

/** @internal */
export const OfferResponseDtoStatus$inboundSchema: z.ZodMiniType<
  OfferResponseDtoStatus,
  unknown
> = openEnums.inboundSchema(OfferResponseDtoStatus);

/** @internal */
export const OfferResponseDto$inboundSchema: z.ZodMiniType<
  OfferResponseDto,
  unknown
> = z.object({
  id: types.string(),
  addresses: z.array(AddressOffer$inboundSchema),
  contactId: types.string(),
  createdDate: types.string(),
  currency: types.string(),
  lineItems: z.array(OfferLineItemResponseDto$inboundSchema),
  name: types.string(),
  offerDate: types.string(),
  offerNumber: types.string(),
  oneLineAddress: types.string(),
  reference: types.string(),
  status: OfferResponseDtoStatus$inboundSchema,
  taxText: types.string(),
  totalDiscountAmount: types.number(),
  totalDiscountPercentage: types.number(),
  totalGrossAmount: types.number(),
  totalNetAmount: types.number(),
  totalTaxAmount: types.number(),
  updatedDate: types.string(),
});

export function offerResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<OfferResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OfferResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OfferResponseDto' from JSON`,
  );
}
