/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { AddressOffer, AddressOffer$inboundSchema } from "./address-offer.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  OfferLineItemResponseDto,
  OfferLineItemResponseDto$inboundSchema,
} from "./offer-line-item-response-dto.js";

export const OfferResponseDtoStatus = {
  Draft: "DRAFT",
  Sent: "SENT",
  Accepted: "ACCEPTED",
  Expired: "EXPIRED",
  Voided: "VOIDED",
  Declined: "DECLINED",
} as const;
export type OfferResponseDtoStatus = OpenEnum<typeof OfferResponseDtoStatus>;

export type OfferResponseDto = {
  id: string | null;
  addresses: Array<AddressOffer> | null;
  contactId?: string | null | undefined;
  createdDate: string | null;
  currency: string | null;
  lineItems: Array<OfferLineItemResponseDto> | null;
  name: string | null;
  offerDate: string | null;
  offerNumber: string | null;
  oneLineAddress: string | null;
  reference: string | null;
  status: OfferResponseDtoStatus | null;
  taxText: string | null;
  totalDiscountAmount: number | null;
  totalDiscountPercentage: number | null;
  totalGrossAmount: number | null;
  totalNetAmount: number | null;
  totalTaxAmount: number | null;
  updatedDate: string | null;
};

/** @internal */
export const OfferResponseDtoStatus$inboundSchema: z.ZodMiniType<
  OfferResponseDtoStatus,
  unknown
> = openEnums.inboundSchema(OfferResponseDtoStatus);

/** @internal */
export const OfferResponseDto$inboundSchema: z.ZodMiniType<
  OfferResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  addresses: types.nullable(z.array(AddressOffer$inboundSchema)),
  contactId: z.optional(z.nullable(types.string())),
  createdDate: types.nullable(types.string()),
  currency: types.nullable(types.string()),
  lineItems: types.nullable(z.array(OfferLineItemResponseDto$inboundSchema)),
  name: types.nullable(types.string()),
  offerDate: types.nullable(types.string()),
  offerNumber: types.nullable(types.string()),
  oneLineAddress: types.nullable(types.string()),
  reference: types.nullable(types.string()),
  status: types.nullable(OfferResponseDtoStatus$inboundSchema),
  taxText: types.nullable(types.string()),
  totalDiscountAmount: types.nullable(types.number()),
  totalDiscountPercentage: types.nullable(types.number()),
  totalGrossAmount: types.nullable(types.number()),
  totalNetAmount: types.nullable(types.number()),
  totalTaxAmount: types.nullable(types.number()),
  updatedDate: types.nullable(types.string()),
});

export function offerResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<OfferResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => OfferResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'OfferResponseDto' from JSON`,
  );
}
