/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  Address,
  Address$Outbound,
  Address$outboundSchema,
} from "./address.js";
import {
  PatchLineItemRequest,
  PatchLineItemRequest$Outbound,
  PatchLineItemRequest$outboundSchema,
} from "./patch-line-item-request.js";

export const PatchInvoiceRequestDtoStatus = {
  Draft: "DRAFT",
  Submitted: "SUBMITTED",
  Open: "OPEN",
  PartiallyPaid: "PARTIALLY_PAID",
  Paid: "PAID",
  Voided: "VOIDED",
} as const;
export type PatchInvoiceRequestDtoStatus = ClosedEnum<
  typeof PatchInvoiceRequestDtoStatus
>;

export const PatchInvoiceRequestDtoInvoiceType = {
  Standard: "STANDARD",
  Bill: "BILL",
} as const;
export type PatchInvoiceRequestDtoInvoiceType = ClosedEnum<
  typeof PatchInvoiceRequestDtoInvoiceType
>;

export const PatchInvoiceRequestDtoTaxRule = {
  Net: "NET",
  Gross: "GROSS",
  Freetax: "FREETAX",
  Intracommunity: "INTRACOMMUNITY",
  Constructionservice: "CONSTRUCTIONSERVICE",
  Externalservice: "EXTERNALSERVICE",
  Thirdpartycountryservice: "THIRDPARTYCOUNTRYSERVICE",
  Thirdpartycountrydelivery: "THIRDPARTYCOUNTRYDELIVERY",
  Reversecharge: "REVERSECHARGE",
  Vatsales: "VATSALES",
  Export: "EXPORT",
  None: "NONE",
  Default: "DEFAULT",
  Eu: "EU",
  Noteu: "NOTEU",
  Custom: "CUSTOM",
  Ss: "SS",
} as const;
export type PatchInvoiceRequestDtoTaxRule = ClosedEnum<
  typeof PatchInvoiceRequestDtoTaxRule
>;

export const PatchInvoiceRequestDtoShippingType = {
  Service: "SERVICE",
  Serviceperiod: "SERVICEPERIOD",
  Delivery: "DELIVERY",
  Deliveryperiod: "DELIVERYPERIOD",
  None: "NONE",
} as const;
export type PatchInvoiceRequestDtoShippingType = ClosedEnum<
  typeof PatchInvoiceRequestDtoShippingType
>;

export const PatchInvoiceRequestDtoLineAmountTypes = {
  Exclusive: "EXCLUSIVE",
  Inclusive: "INCLUSIVE",
  Notax: "NOTAX",
} as const;
export type PatchInvoiceRequestDtoLineAmountTypes = ClosedEnum<
  typeof PatchInvoiceRequestDtoLineAmountTypes
>;

export type PatchInvoiceRequestDto = {
  invoiceId: string;
  contactId: string;
  name: string;
  reference: string;
  currency: string;
  invoiceDate: string;
  journalCode: string;
  paymentTermId: string;
  fileId: string;
  status: PatchInvoiceRequestDtoStatus;
  invoiceType: PatchInvoiceRequestDtoInvoiceType;
  oneLineAddress: string;
  addresses: Array<Address>;
  taxRule: PatchInvoiceRequestDtoTaxRule;
  taxText: string;
  lineItems: Array<PatchLineItemRequest>;
  discountPercentage: number;
  shippingType: PatchInvoiceRequestDtoShippingType;
  shippingDate: string;
  shippingEndDate: string;
  lineAmountTypes: PatchInvoiceRequestDtoLineAmountTypes;
  dueDate: string;
  paidDate: string;
  paymentTermDuration: number;
};

/** @internal */
export const PatchInvoiceRequestDtoStatus$outboundSchema: z.ZodMiniEnum<
  typeof PatchInvoiceRequestDtoStatus
> = z.enum(PatchInvoiceRequestDtoStatus);

/** @internal */
export const PatchInvoiceRequestDtoInvoiceType$outboundSchema: z.ZodMiniEnum<
  typeof PatchInvoiceRequestDtoInvoiceType
> = z.enum(PatchInvoiceRequestDtoInvoiceType);

/** @internal */
export const PatchInvoiceRequestDtoTaxRule$outboundSchema: z.ZodMiniEnum<
  typeof PatchInvoiceRequestDtoTaxRule
> = z.enum(PatchInvoiceRequestDtoTaxRule);

/** @internal */
export const PatchInvoiceRequestDtoShippingType$outboundSchema: z.ZodMiniEnum<
  typeof PatchInvoiceRequestDtoShippingType
> = z.enum(PatchInvoiceRequestDtoShippingType);

/** @internal */
export const PatchInvoiceRequestDtoLineAmountTypes$outboundSchema:
  z.ZodMiniEnum<typeof PatchInvoiceRequestDtoLineAmountTypes> = z.enum(
    PatchInvoiceRequestDtoLineAmountTypes,
  );

/** @internal */
export type PatchInvoiceRequestDto$Outbound = {
  invoiceId: string;
  contactId: string;
  name: string;
  reference: string;
  currency: string;
  invoiceDate: string;
  journalCode: string;
  paymentTermId: string;
  fileId: string;
  status: string;
  invoiceType: string;
  oneLineAddress: string;
  addresses: Array<Address$Outbound>;
  taxRule: string;
  taxText: string;
  lineItems: Array<PatchLineItemRequest$Outbound>;
  discountPercentage: number;
  shippingType: string;
  shippingDate: string;
  shippingEndDate: string;
  lineAmountTypes: string;
  dueDate: string;
  paidDate: string;
  paymentTermDuration: number;
};

/** @internal */
export const PatchInvoiceRequestDto$outboundSchema: z.ZodMiniType<
  PatchInvoiceRequestDto$Outbound,
  PatchInvoiceRequestDto
> = z.object({
  invoiceId: z.string(),
  contactId: z.string(),
  name: z.string(),
  reference: z.string(),
  currency: z.string(),
  invoiceDate: z.string(),
  journalCode: z.string(),
  paymentTermId: z.string(),
  fileId: z.string(),
  status: PatchInvoiceRequestDtoStatus$outboundSchema,
  invoiceType: PatchInvoiceRequestDtoInvoiceType$outboundSchema,
  oneLineAddress: z.string(),
  addresses: z.array(Address$outboundSchema),
  taxRule: PatchInvoiceRequestDtoTaxRule$outboundSchema,
  taxText: z.string(),
  lineItems: z.array(PatchLineItemRequest$outboundSchema),
  discountPercentage: z.number(),
  shippingType: PatchInvoiceRequestDtoShippingType$outboundSchema,
  shippingDate: z.string(),
  shippingEndDate: z.string(),
  lineAmountTypes: PatchInvoiceRequestDtoLineAmountTypes$outboundSchema,
  dueDate: z.string(),
  paidDate: z.string(),
  paymentTermDuration: z.number(),
});

export function patchInvoiceRequestDtoToJSON(
  patchInvoiceRequestDto: PatchInvoiceRequestDto,
): string {
  return JSON.stringify(
    PatchInvoiceRequestDto$outboundSchema.parse(patchInvoiceRequestDto),
  );
}
