/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  InvoiceDimensionRequestDto,
  InvoiceDimensionRequestDto$Outbound,
  InvoiceDimensionRequestDto$outboundSchema,
} from "./invoice-dimension-request-dto.js";

export const PatchLineItemRequestType = {
  ServiceItem: "SERVICE_ITEM",
  Material: "MATERIAL",
  Custom: "CUSTOM",
  Text: "TEXT",
} as const;
export type PatchLineItemRequestType = ClosedEnum<
  typeof PatchLineItemRequestType
>;

export type PatchLineItemRequest = {
  lineItemId: string;
  itemId?: string | undefined;
  unitName?: string | undefined;
  type?: PatchLineItemRequestType | undefined;
  quantity?: number | undefined;
  taxRatePercentage?: number | undefined;
  unitAmount?: number | undefined;
  grossAmount?: number | undefined;
  taxCode?: string | undefined;
  taxType?: string | undefined;
  description?: string | undefined;
  name?: string | undefined;
  accountCode?: string | undefined;
  accountId?: string | undefined;
  dimensions?: Array<InvoiceDimensionRequestDto> | undefined;
  discountItemPercentage?: number | undefined;
};

/** @internal */
export const PatchLineItemRequestType$outboundSchema: z.ZodMiniEnum<
  typeof PatchLineItemRequestType
> = z.enum(PatchLineItemRequestType);

/** @internal */
export type PatchLineItemRequest$Outbound = {
  lineItemId: string;
  itemId?: string | undefined;
  unitName?: string | undefined;
  type?: string | undefined;
  quantity?: number | undefined;
  taxRatePercentage?: number | undefined;
  unitAmount?: number | undefined;
  grossAmount?: number | undefined;
  taxCode?: string | undefined;
  taxType?: string | undefined;
  description?: string | undefined;
  name?: string | undefined;
  accountCode?: string | undefined;
  accountId?: string | undefined;
  dimensions?: Array<InvoiceDimensionRequestDto$Outbound> | undefined;
  discountItemPercentage?: number | undefined;
};

/** @internal */
export const PatchLineItemRequest$outboundSchema: z.ZodMiniType<
  PatchLineItemRequest$Outbound,
  PatchLineItemRequest
> = z.object({
  lineItemId: z.string(),
  itemId: z.optional(z.string()),
  unitName: z.optional(z.string()),
  type: z.optional(PatchLineItemRequestType$outboundSchema),
  quantity: z.optional(z.number()),
  taxRatePercentage: z.optional(z.number()),
  unitAmount: z.optional(z.number()),
  grossAmount: z.optional(z.number()),
  taxCode: z.optional(z.string()),
  taxType: z.optional(z.string()),
  description: z.optional(z.string()),
  name: z.optional(z.string()),
  accountCode: z.optional(z.string()),
  accountId: z.optional(z.string()),
  dimensions: z.optional(z.array(InvoiceDimensionRequestDto$outboundSchema)),
  discountItemPercentage: z.optional(z.number()),
});

export function patchLineItemRequestToJSON(
  patchLineItemRequest: PatchLineItemRequest,
): string {
  return JSON.stringify(
    PatchLineItemRequest$outboundSchema.parse(patchLineItemRequest),
  );
}
