/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  DiscountPeriodResponse,
  DiscountPeriodResponse$inboundSchema,
} from "./discount-period-response.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PaymentTermResponseDtoDueType = {
  DueInDays: "DUE_IN_DAYS",
  DueAsPeriod: "DUE_AS_PERIOD",
} as const;
export type PaymentTermResponseDtoDueType = OpenEnum<
  typeof PaymentTermResponseDtoDueType
>;

export type PaymentTermResponseDtoUpdatedDate = {};

export type PaymentTermResponseDto = {
  id: string;
  code: string;
  createdDate: string;
  description: string;
  discountDays: number;
  discountDays2: number;
  discountPercentage: number;
  discountPercentage2: number;
  discountPeriods: Array<DiscountPeriodResponse>;
  dueType: PaymentTermResponseDtoDueType;
  name: string;
  paymentDays: number;
  paymentMethod: string;
  updatedDate: PaymentTermResponseDtoUpdatedDate;
};

/** @internal */
export const PaymentTermResponseDtoDueType$inboundSchema: z.ZodMiniType<
  PaymentTermResponseDtoDueType,
  unknown
> = openEnums.inboundSchema(PaymentTermResponseDtoDueType);

/** @internal */
export const PaymentTermResponseDtoUpdatedDate$inboundSchema: z.ZodMiniType<
  PaymentTermResponseDtoUpdatedDate,
  unknown
> = z.object({});

export function paymentTermResponseDtoUpdatedDateFromJSON(
  jsonString: string,
): SafeParseResult<PaymentTermResponseDtoUpdatedDate, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentTermResponseDtoUpdatedDate$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentTermResponseDtoUpdatedDate' from JSON`,
  );
}

/** @internal */
export const PaymentTermResponseDto$inboundSchema: z.ZodMiniType<
  PaymentTermResponseDto,
  unknown
> = z.object({
  id: types.string(),
  code: types.string(),
  createdDate: types.string(),
  description: types.string(),
  discountDays: types.number(),
  discountDays2: types.number(),
  discountPercentage: types.number(),
  discountPercentage2: types.number(),
  discountPeriods: z.array(DiscountPeriodResponse$inboundSchema),
  dueType: PaymentTermResponseDtoDueType$inboundSchema,
  name: types.string(),
  paymentDays: types.number(),
  paymentMethod: types.string(),
  updatedDate: z.lazy(() => PaymentTermResponseDtoUpdatedDate$inboundSchema),
});

export function paymentTermResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<PaymentTermResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentTermResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentTermResponseDto' from JSON`,
  );
}
