/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { PaymentLine, PaymentLine$inboundSchema } from "./payment-line.js";

export const PaymentResponseDtoDocumentType = {
  Invoice: "INVOICE",
  Bill: "BILL",
  BookingProposal: "BOOKING_PROPOSAL",
} as const;
export type PaymentResponseDtoDocumentType = ClosedEnum<
  typeof PaymentResponseDtoDocumentType
>;

export type PaymentResponseDto = {
  id: string | null;
  currency: string | null;
  createdDate: string | null;
  documentType: PaymentResponseDtoDocumentType | null;
  exchangeRate: number | null;
  journalCode: string | null;
  updatedDate: string | null;
  paymentType: string | null;
  paymentLines: Array<PaymentLine> | null;
};

/** @internal */
export const PaymentResponseDtoDocumentType$inboundSchema: z.ZodMiniEnum<
  typeof PaymentResponseDtoDocumentType
> = z.enum(PaymentResponseDtoDocumentType);

/** @internal */
export const PaymentResponseDto$inboundSchema: z.ZodMiniType<
  PaymentResponseDto,
  unknown
> = z.object({
  id: types.nullable(types.string()),
  currency: types.nullable(types.string()),
  createdDate: types.nullable(types.string()),
  documentType: types.nullable(PaymentResponseDtoDocumentType$inboundSchema),
  exchangeRate: types.nullable(types.number()),
  journalCode: types.nullable(types.string()),
  updatedDate: types.nullable(types.string()),
  paymentType: types.nullable(types.string()),
  paymentLines: types.nullable(z.array(PaymentLine$inboundSchema)),
});

export function paymentResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<PaymentResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentResponseDto' from JSON`,
  );
}
