/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PhoneNumberV2Type = {
  Business: "BUSINESS",
  Mobile: "MOBILE",
  Office: "OFFICE",
  Fax: "FAX",
  Private: "PRIVATE",
  Other: "OTHER",
} as const;
export type PhoneNumberV2Type = ClosedEnum<typeof PhoneNumberV2Type>;

export type PhoneNumberV2 = {
  number: string | null;
  type: PhoneNumberV2Type | null;
};

/** @internal */
export const PhoneNumberV2Type$inboundSchema: z.ZodMiniEnum<
  typeof PhoneNumberV2Type
> = z.enum(PhoneNumberV2Type);
/** @internal */
export const PhoneNumberV2Type$outboundSchema: z.ZodMiniEnum<
  typeof PhoneNumberV2Type
> = PhoneNumberV2Type$inboundSchema;

/** @internal */
export const PhoneNumberV2$inboundSchema: z.ZodMiniType<
  PhoneNumberV2,
  unknown
> = z.object({
  number: types.nullable(types.string()),
  type: types.nullable(PhoneNumberV2Type$inboundSchema),
});
/** @internal */
export type PhoneNumberV2$Outbound = {
  number: string | null;
  type: string | null;
};

/** @internal */
export const PhoneNumberV2$outboundSchema: z.ZodMiniType<
  PhoneNumberV2$Outbound,
  PhoneNumberV2
> = z.object({
  number: z.nullable(z.string()),
  type: z.nullable(PhoneNumberV2Type$outboundSchema),
});

export function phoneNumberV2ToJSON(phoneNumberV2: PhoneNumberV2): string {
  return JSON.stringify(PhoneNumberV2$outboundSchema.parse(phoneNumberV2));
}
export function phoneNumberV2FromJSON(
  jsonString: string,
): SafeParseResult<PhoneNumberV2, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PhoneNumberV2$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PhoneNumberV2' from JSON`,
  );
}
