/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type SalesOrderLineItemResponseDto = {
  id: string;
  itemId: string;
  createdDate: string;
  description: string;
  itemName: string;
  quantity: number;
  taxCode: string;
  taxRatePercentage: number;
  totalDiscountAmount: number;
  totalDiscountPercentage: number;
  totalGrossAmount: number;
  totalNetAmount: number;
  totalTaxAmount: number;
  unitAmount: number;
  unitDiscountAmount: number;
  unitDiscountPercentage: number;
  unitName: string;
  updatedDate: string;
};

/** @internal */
export const SalesOrderLineItemResponseDto$inboundSchema: z.ZodMiniType<
  SalesOrderLineItemResponseDto,
  unknown
> = z.object({
  id: types.string(),
  itemId: types.string(),
  createdDate: types.string(),
  description: types.string(),
  itemName: types.string(),
  quantity: types.number(),
  taxCode: types.string(),
  taxRatePercentage: types.number(),
  totalDiscountAmount: types.number(),
  totalDiscountPercentage: types.number(),
  totalGrossAmount: types.number(),
  totalNetAmount: types.number(),
  totalTaxAmount: types.number(),
  unitAmount: types.number(),
  unitDiscountAmount: types.number(),
  unitDiscountPercentage: types.number(),
  unitName: types.string(),
  updatedDate: types.string(),
});

export function salesOrderLineItemResponseDtoFromJSON(
  jsonString: string,
): SafeParseResult<SalesOrderLineItemResponseDto, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SalesOrderLineItemResponseDto$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SalesOrderLineItemResponseDto' from JSON`,
  );
}
