/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type SubmissionPageLocalizationDto = {
  locale?: string | undefined;
  titleText?: string | undefined;
  freeText?: string | undefined;
  submitButtonText?: string | undefined;
  cancelButtonText?: string | undefined;
};

/** @internal */
export type SubmissionPageLocalizationDto$Outbound = {
  locale?: string | undefined;
  titleText?: string | undefined;
  freeText?: string | undefined;
  submitButtonText?: string | undefined;
  cancelButtonText?: string | undefined;
};

/** @internal */
export const SubmissionPageLocalizationDto$outboundSchema: z.ZodMiniType<
  SubmissionPageLocalizationDto$Outbound,
  SubmissionPageLocalizationDto
> = z.object({
  locale: z.optional(z.string()),
  titleText: z.optional(z.string()),
  freeText: z.optional(z.string()),
  submitButtonText: z.optional(z.string()),
  cancelButtonText: z.optional(z.string()),
});

export function submissionPageLocalizationDtoToJSON(
  submissionPageLocalizationDto: SubmissionPageLocalizationDto,
): string {
  return JSON.stringify(
    SubmissionPageLocalizationDto$outboundSchema.parse(
      submissionPageLocalizationDto,
    ),
  );
}
