/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  CustomValues,
  CustomValues$Outbound,
  CustomValues$outboundSchema,
} from "./custom-values.js";

export type SystemRegistrationDto = {
  targetSystem: string;
  clientId: string;
  clientSecret: string;
  customValues: Array<CustomValues>;
};

/** @internal */
export type SystemRegistrationDto$Outbound = {
  targetSystem: string;
  clientId: string;
  clientSecret: string;
  customValues: Array<CustomValues$Outbound>;
};

/** @internal */
export const SystemRegistrationDto$outboundSchema: z.ZodMiniType<
  SystemRegistrationDto$Outbound,
  SystemRegistrationDto
> = z.object({
  targetSystem: z.string(),
  clientId: z.string(),
  clientSecret: z.string(),
  customValues: z.array(CustomValues$outboundSchema),
});

export function systemRegistrationDtoToJSON(
  systemRegistrationDto: SystemRegistrationDto,
): string {
  return JSON.stringify(
    SystemRegistrationDto$outboundSchema.parse(systemRegistrationDto),
  );
}
