/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type TaxRateRequestDtoV2 = {
  id?: string | undefined;
  code?: string | undefined;
  description?: string | undefined;
  taxRatePercentage?: number | undefined;
};

/** @internal */
export type TaxRateRequestDtoV2$Outbound = {
  id?: string | undefined;
  code?: string | undefined;
  description?: string | undefined;
  taxRatePercentage?: number | undefined;
};

/** @internal */
export const TaxRateRequestDtoV2$outboundSchema: z.ZodMiniType<
  TaxRateRequestDtoV2$Outbound,
  TaxRateRequestDtoV2
> = z.object({
  id: z.optional(z.string()),
  code: z.optional(z.string()),
  description: z.optional(z.string()),
  taxRatePercentage: z.optional(z.number()),
});

export function taxRateRequestDtoV2ToJSON(
  taxRateRequestDtoV2: TaxRateRequestDtoV2,
): string {
  return JSON.stringify(
    TaxRateRequestDtoV2$outboundSchema.parse(taxRateRequestDtoV2),
  );
}
